------------------------------------------------------------------------------
fx_version "cerulean"
game "gta5"
lua54 "yes"
author "Twiitchter"
description "Ingenium"
version "1.0.7"
------------------------------------------------------------------------------
provide "polyzone"
provide "pma-voice"

ui_page "nui/dist/index.html"
------------------------------------------------------------------------------
-- Static reference data files distributed to clients
-- These are downloaded automatically by FiveM and can be read locally
files {
    'data/peds.json',
    'data/tattoos.json',
    'data/appearance-constants.json',
    'data/weapons.json',
    'data/vehicles.json',
    'data/items.json'
}
------------------------------------------------------------------------------
shared_scripts {
    "_config/config.lua",
    "_config/defaults.lua",
    "_config/banking.lua",
    "_config/chat.lua",
    "_config/dev.lua",
    "_config/disable.lua",
    "_config/discord.example.lua",
    "_config/discord.lua",
    "_config/files.lua",
    "_config/forced_animations.lua",
    "_config/gamemode.lua",
    "_config/garage.lua",
    "_config/ipls.lua",
    "_config/jobs.lua",
    "_config/peds.lua",
    "_config/phones.lua",
    "_config/screenshot.lua",
    "_config/urls.lua",
    "_config/vehicles.lua",
    "_config/voip.lua",
    "shared/_ig.lua",
    "shared/_log.lua",
    "shared/_locale.lua",
    "shared/_protect.lua",
    "locale/de.lua",
    "locale/en.lua",
    "locale/es.lua",
    "locale/fr.lua",
    "locale/pt.lua",
    "shared/[Third Party]/_callbacks.lua",
    "shared/[Tools]/_check.lua",
    "shared/[Tools]/_file.lua",
    "shared/[Tools]/_gamemode.lua",
    "shared/[Tools]/_json.lua",
    "shared/[Tools]/_math.lua",
    "shared/[Tools]/_rng.lua",
    "shared/[Tools]/_table.lua",
    "shared/[Tools]/_util.lua",
    "shared/[Voice]/_pma_wrapper.lua",
    "shared/[Voice]/_voip.lua",
    "shared/[Third Party]/*.lua",
    "shared/[Tools]/*.lua",
    "shared/[Voice]/*.lua",
}
------------------------------------------------------------------------------
client_scripts {
    "client/_var.lua",
    "client/_data.lua",
    "client/_functions.lua",
    "client/_callback.lua",
    "client/[Garage]/_var.lua",
    "client/[Target]/_var.lua",
    "client/_affiliation.lua",
    "client/_ammo.lua",
    "client/_animations.lua",
    "client/_appearance.lua",
    "client/_blips.lua",
    "client/_cameras.lua",
    "client/_chat.lua",
    "client/_commands.lua",
    "client/_death.lua",
    "client/_discord.lua",
    "client/_doors.lua",
    "client/_drops.lua",
    "client/_fx.lua",
    "client/_inventory.lua",
    "client/_ipls.lua",
    "client/_items.lua",
    "client/_markers.lua",
    "client/_modifiers.lua",
    "client/_objects.lua",
    "client/_persistance.lua",
    "client/_screenshot.lua",
    "client/_skills.lua",
    "client/_states.lua",
    "client/_status.lua",
    "client/_tattoo.lua",
    "client/_text.lua",
    "client/_time.lua",
    "client/_ui.lua",
    "client/_vehicle.lua",
    "client/_vehicle_persistence.lua",
    "client/_weapon.lua",
    "client/_weather.lua",
    "client/[Zones]/PolyZone.lua",
    "client/[Zones]/BoxZone.lua",
    "client/[Zones]/CircleZone.lua",
    "client/[Zones]/ComboZone.lua",
    "client/[Zones]/EntityZone.lua",
    "client/[Zones]/_zone.lua",
    "client/[Zones]/_zone_manager.lua",
    "client/[Zones]/_zone_test_example.lua",
    "client/[Callbacks]/_animations_forced.lua",
    "client/[Callbacks]/_appearance.lua",
    "client/[Callbacks]/_banking.lua",
    "client/[Callbacks]/_character.lua",
    "client/[Callbacks]/_chat.lua",
    "client/[Callbacks]/_commands.lua",
    "client/[Callbacks]/_inventory.lua",
    "client/[Chat]/_aces.lua",
    "client/[Commands]/_locate_vehicles.lua",
    "client/[Dev]/_ammunation.lua",
    "client/[Dev]/_doorcreator.lua",
    "client/[Dev]/_examples.lua",
    "client/[Dev]/_vehicleseats.lua",
    "client/[Drops]/_drop_integration.lua",
    "client/[Drops]/_drop_targets.lua",
    "client/[Events]/_character.lua",
    "client/[Events]/_gamemode.lua",
    "client/[Events]/_runchecks.lua",
    "client/[Events]/_vehicle.lua",
    "client/[Events]/_vehicles.lua",
    "client/[Garage]/_client.lua",
    "client/[Garage]/_machine.lua",
    "client/[Target]/_api.lua",
    "client/[Target]/_defaults.lua",
    "client/[Target]/_lib.lua",
    "client/[Target]/_main.lua",
    "client/[Target]/_utils.lua",
    "client/[Voice]/_voip.lua",
    "client/[ToDo]/_persitance.lua",
    "client/[ToDo]/_traits.lua",
    "client/[Threads]/_forced_animations.lua",
    "client/[Threads]/_player_load_restriction.lua",
    "client/[Threads]/_rp_controls.lua",
    "client/[Threads]/_rp_features.lua",
    "client/[Threads]/_weapon.lua",
    "client/client.lua",
    "client/[Callbacks]/_data.lua",
    "client/[Callbacks]/*.lua",
    "client/[Chat]/*.lua",
    "client/[Commands]/*.lua",
    "client/[Dev]/*.lua",
    "client/[Drops]/*.lua",
    "client/[Events]/*.lua",
    "client/[Garage]/*.lua",
    "client/[Target]/*.lua",
    "client/[Threads]/*.lua",
    "client/[ToDo]/*.lua",
    "client/[Voice]/*.lua",
    "client/[Zones]/*.lua",
    "nui/lua/*.lua",
    "nui/lua/**/*.lua"
}
------------------------------------------------------------------------------
server_scripts {
    "server/_var.lua",
    "server/_data.lua",
    "server/_callback.lua",
    "server/_functions.lua",
    "server/[Garage]/_var.lua",
    "server/[API]/_api.lua",
    "server/[Appearance]/_pricing.lua",
    "server/[Callbacks]/_animations_forced.lua",
    "server/[Callbacks]/_appearance.lua",
    "server/[Callbacks]/_banking.lua",
    "server/[Callbacks]/_inventory.lua",
    "server/[Callbacks]/_players.lua",
    "server/[Callbacks]/_vehicles.lua",
    "server/[Classes]/_blank_object.lua",
    "server/[Classes]/_existing_object.lua",
    "server/[Classes]/_job.lua",
    "server/[Classes]/_npc.lua",
    "server/[Classes]/_offline_player.lua",
    "server/[Classes]/_owned_vehicle.lua",
    "server/[Classes]/_player.lua",
    "server/[Classes]/_vehicle.lua",
    "server/[Data - No Save Needed]/_appearance.lua",
    "server/[Data - No Save Needed]/_modkit.lua",
    "server/[Data - No Save Needed]/_names.lua",
    "server/[Data - No Save Needed]/_npc.lua",
    "server/[Data - No Save Needed]/_objects.lua",
    "server/[Data - No Save Needed]/_peds.lua",
    "server/[Data - No Save Needed]/_tattoo.lua",
    "server/[Data - No Save Needed]/_vehicle.lua",
    "server/[Data - No Save Needed]/_weapons.lua",
    "server/[Commands]/_locate_vehicles.lua",
    "server/[Deferals]/_deferals.lua",
    "server/[Dev]/_commands.lua",
    "server/[Doors]/_doors.lua",
    "server/[Events]/_character.lua",
    "server/[Events]/_character_lifecycle.lua",
    "server/[Events]/_feedback.lua",
    "server/[Events]/_vehicle.lua",
    "server/[Garage]/_callbacks.lua",
    "server/[Objects]/_jobs.lua",
    "server/[Objects]/_npcs.lua",
    "server/[Objects]/_objects.lua",
    "server/[Objects]/_players.lua",
    "server/[Objects]/_vehicles.lua",
    "server/[Onesync]/_events.lua",
    "server/[Onesync]/_sbch.lua",
    "server/[SQL]/_bank.lua",
    "server/[SQL]/_banking.lua",
    "server/[SQL]/_character.lua",
    "server/[SQL]/_gen.lua",
    "server/[SQL]/_handler.lua",
    "server/[SQL]/_jobs.lua",
    "server/[SQL]/_saves.lua",
    "server/[SQL]/_users.lua",
    "server/[SQL]/_vehicles.lua",
    "server/[Security]/_statebag_protection.lua",
    "server/[Security]/_transaction_security.lua",
    "server/[Third Party]/_adaptivecards.lua",
    "server/[Third Party]/_discord.lua",
    "server/[Third Party]/_queue_commands.lua",
    "server/[Third Party]/_queue_config_new.lua",
    "server/[Third Party]/_queue_system.lua",
    "server/[Tools]/_logging.lua",
    "server/[Tools]/_memory.lua",
    "server/[Validation]/_validator.lua",
    "server/[Voice]/_voip.lua",
    "server/_bank.lua",
    "server/_chat.lua",
    "server/_commands.lua",
    "server/_cron.lua",
    "server/_events.lua",
    "server/_instance.lua",
    "server/_payroll.lua",
    "server/_persistance.lua",
    "server/_save_routine.lua",
    "server/_screenshot.lua",
    "server/_tebex.lua",
    "server/_time.lua",
    "server/_vehicle_persistence.lua",
    "server/[Data - Save to File]/_drops.lua",
    "server/[Data - Save to File]/_gsr.lua",
    "server/[Data - Save to File]/_items.lua",
    "server/[Data - Save to File]/_jobs.lua",
    "server/[Data - Save to File]/_notes.lua",
    "server/[Data - Save to File]/_pickups.lua",
    "server/server.lua",
    "server/[Callbacks]/_data.lua",
    "server/[API]/*.lua",
    "server/[Appearance]/*.lua",
    "server/[Callbacks]/*.lua",
    "server/[Classes]/*.lua",
    "server/[Commands]/*.lua",
    "server/[Data - No Save Needed]/*.lua",
    "server/[Data - Save to File]/*.lua",
    "server/[Deferals]/*.lua",
    "server/[Dev]/*.lua",
    "server/[Doors]/*.lua",
    "server/[Events]/*.lua",
    "server/[Garage]/*.lua",
    "server/[Objects]/*.lua",
    "server/[Onesync]/*.lua",
    "server/[SQL]/*.lua",
    "server/[Security]/*.lua",
    "server/[Third Party]/*.lua",
    "server/[Tools]/*.lua",
    "server/[Validation]/*.lua",
    "server/[Voice]/*.lua",
}
------------------------------------------------------------------------------
dependencies {
    "/onesync",
    "freecam",
    "screenshot-basic",
}
------------------------------------------------------------------------------
files {
    "data/*.json",
    "nui/img/*.png",
    "nui/inventory/dist/assets/*.css",
    "nui/inventory/dist/assets/*.js",
    "nui/dist/*.html",
    "nui/dist/assets/*.css",
    "nui/dist/assets/*.js"
}
------------------------------------------------------------------------------
