-- Auto-generated FiveM native stubs
-- API Set: CLIENT
-- Total natives: 1186
-- Generated by smart classifier

-- ============================================

-- Namespace: DrawDebugText (1 natives)

-- [+] 0xA3BB2E9555C05A8F
function DrawDebugText_2d(text, x, y, z, red, green, blue, alpha) end

-- Namespace: DrawMarker (1 natives)

-- [+] 0xE82728F0DE75D13A
function DrawMarker_2(type, posX, posY, posZ, dirX, dirY, dirZ, rotX, rotY, rotZ, scaleX, scaleY, scaleZ, red, green, blue, alpha, bobUpAndDown, faceCamera, rotationOrder, rotate, textureDict, textureName, drawOnEnts, p24) end

-- Namespace: DrawScaleformMovie (2 natives)

-- [+] 0x87D51D72255D4E78
function DrawScaleformMovie_3d(scaleform, posX, posY, posZ, rotX, rotY, rotZ, p7, sharpness, p9, scaleX, scaleY, scaleZ, p13) end

-- [+] 0x1CE592FDC749D6F5
function DrawScaleformMovie_3dSolid(scaleform, posX, posY, posZ, rotX, rotY, rotZ, p7, p8, p9, scaleX, scaleY, scaleZ, p13) end

-- Namespace: DrawSpritePoly (1 natives)

-- [+] 0x736D7AA1B750856B
function DrawSpritePoly_2(x1, y1, z1, x2, y2, z2, x3, y3, z3, red1, green1, blue1, alpha1, red2, green2, blue2, alpha2, red3, green3, blue3, alpha3, textureDict, textureName, u1, v1, w1, u2, v2, w2, u3, v3, w3) end

-- Namespace: GetAngleBetween (1 natives)

-- [+] 0x186FC4BE848E1C92
function GetAngleBetween_2dVectors(x1, y1, x2, y2) end

-- Namespace: GetGroundZAndNormalFor (1 natives)

-- [+] 0x8BDC7BFC57A81E76
function GetGroundZAndNormalFor_3dCoord(x, y, z, groundZ, normal) end

-- Namespace: GetGroundZFor (1 natives)

-- [+] 0xC906A7DAB05C8D2B
function GetGroundZFor_3dCoord(x, y, z, groundZ, includeWater) end

-- Namespace: GetHeadingFromVector (1 natives)

-- [+] 0x2FFB6B224F4B2926
function GetHeadingFromVector_2d(dx, dy) end

-- Namespace: GetRandomIntInRange (1 natives)

-- [+] 0xF2D49816A804D134
function GetRandomIntInRange_2(startRange, endRange) end

-- Namespace: IsUsingKeyboard (1 natives)

-- [+] 0x13337B38DB572509
function IsUsingKeyboard_2(padIndex) end

-- Namespace: N (203 natives)

-- [+] 0x0218BA067D249DEA
function N_0x0218ba067d249dea() end

-- [+] 0x0225778816FDC28C
function N_0x0225778816fdc28c(p0) end

-- [+] 0x02369D5C8A51FDCF
function N_0x02369d5c8a51fdcf(toggle) end

-- [+] 0x03300B57FCAC6DDB
function N_0x03300b57fcac6ddb(p0) end

-- [+] 0x03F1A106BDA7DD3E
function N_0x03f1a106bda7dd3e() end

-- [+] 0x06462A961E94B67C
function N_0x06462a961e94b67c() end

-- [+] 0x06EE9048FD080382
function N_0x06ee9048fd080382(p0) end

-- [+] 0x0811381EF5062FEC
function N_0x0811381ef5062fec(p0) end

-- [+] 0x0AA27680A0BD43FA
function N_0x0aa27680a0bd43fa() end

-- [+] 0x0AE73D8DF3A762B2
function N_0x0ae73d8df3a762b2(p0) end

-- [+] 0x0E4299C549F0D1F1
function N_0x0e4299c549f0d1f1(toggle) end

-- [+] 0x108BE26959A9D9BB
function N_0x108be26959a9d9bb(toggle) end

-- [+] 0x1178E104409FE58C
function N_0x1178e104409fe58c(p0, p1) end

-- [+] 0x12DED8CA53D47EA5
function N_0x12ded8ca53d47ea5(p0) end

-- [+] 0x14D29BB12D47F68C
function N_0x14d29bb12d47f68c(p0, p1, p2, p3, p4) end

-- [+] 0x14FC5833464340A8
function N_0x14fc5833464340a8() end

-- [+] 0x1612C45F9E3E0D44
function N_0x1612c45f9e3e0d44() end

-- [+] 0x17FCA7199A530203
function N_0x17fca7199a530203() end

-- [+] 0x19BFED045C647C49
function N_0x19bfed045c647c49(ped) end

-- [+] 0x1BBC135A4D25EDDE
function N_0x1bbc135a4d25edde(p0) end

-- [+] 0x1CBA05AE7BD7EE05
function N_0x1cba05ae7bd7ee05(p0) end

-- [+] 0x1E9057A74FD73E23
function N_0x1e9057a74fd73e23() end

-- [+] 0x1F2300CB7FA7B7F6
function N_0x1f2300cb7fa7b7f6() end

-- [+] 0x20746F7B1032A3C7
function N_0x20746f7b1032a3c7(p0, p1, p2, p3) end

-- [+] 0x20C6C7E4EB082A7F
function N_0x20c6c7e4eb082a7f(p0) end

-- [+] 0x2107A3773771186D
function N_0x2107a3773771186d() end

-- [+] 0x21C235BC64831E5A
function N_0x21c235bc64831e5a(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9) end

-- [+] 0x23227DF0B2115469
function N_0x23227df0b2115469() end

-- [+] 0x23F09EADC01449D6
function N_0x23f09eadc01449d6(padIndex) end

-- [+] 0x247ACBC4ABBC9D1C
function N_0x247acbc4abbc9d1c(p0) end

-- [+] 0x259BA6D4E6F808F1
function N_0x259ba6d4e6f808f1(p0) end

-- [+] 0x25AAA32BDC98F2A3
function N_0x25aaa32bdc98f2a3() end

-- [+] 0x25FC3E33A31AD0C9
function N_0x25fc3e33a31ad0c9(p0) end

-- [+] 0x271017B9BA825366
function N_0x271017b9ba825366(p0, p1) end

-- [+] 0x27CFB1B1E078CB2D
function N_0x27cfb1b1e078cb2d() end

-- [+] 0x27FEB5254759CDE3
function N_0x27feb5254759cde3(textureDict, p1) end

-- [+] 0x28B022A17B068A3A
function N_0x28b022a17b068a3a(p0, p1) end

-- [+] 0x2A251AA48B2B46DB
function N_0x2a251aa48b2b46db() end

-- [+] 0x2B40A97646381508
function N_0x2b40a97646381508(p0) end

-- [+] 0x2C42340F916C5930
function N_0x2c42340f916c5930(p0) end

-- [+] 0x2D3B147AFAD49DE0
function N_0x2d3b147afad49de0(textureDict, textureName, x, y, width, height, p6, red, green, blue, alpha, p11) end

-- [+] 0x2F137B508DE238F2
function N_0x2f137b508de238f2(p0) end

-- [+] 0x2F7F2B26DD3F18EE
function N_0x2f7f2b26dd3f18ee(p0, p1) end

-- [+] 0x2FCB133CA50A49EB
function N_0x2fcb133ca50a49eb(p0) end

-- [+] 0x30432A0118736E00
function N_0x30432a0118736e00() end

-- [+] 0x3044240D2E0FA842
function N_0x3044240d2e0fa842() end

-- [+] 0x31125FD509D9043F
function N_0x31125fd509d9043f(p0) end

-- [+] 0x324C5AA411DA7737
function N_0x324c5aa411da7737(p0) end

-- [+] 0x346EF3ECAAAB149E
function N_0x346ef3ecaaab149e() end

-- [+] 0x36F6626459D91457
function N_0x36f6626459d91457(p0) end

-- [+] 0x380B4968D1E09E55
function N_0x380b4968d1e09e55() end

-- [+] 0x393BD2275CEB7793
function N_0x393bd2275ceb7793() end

-- [+] 0x39455BF4F4F55186
function N_0x39455bf4f4f55186(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12) end

-- [+] 0x397BAA01068BAA96
function N_0x397baa01068baa96() end

-- [+] 0x3C788E7F6438754D
function N_0x3c788e7f6438754d(checkpointHandle, x, y, z) end

-- [+] 0x4008EDF7D6E48175
function N_0x4008edf7d6e48175(p0) end

-- [+] 0x43FA7CBE20DAB219
function N_0x43fa7cbe20dab219(p0) end

-- [+] 0x469F2ECDEC046337
function N_0x469f2ecdec046337(p0) end

-- [+] 0x46D1A61A21F566FC
function N_0x46d1a61a21f566fc(p0) end

-- [+] 0x472397322E92A856
function N_0x472397322e92a856() end

-- [+] 0x4879E4FE39074CDF
function N_0x4879e4fe39074cdf() end

-- [+] 0x48F069265A0E4BEC
function N_0x48f069265a0e4bec(p0, name) end

-- [+] 0x4AF92ACD3141D96C
function N_0x4af92acd3141d96c() end

-- [+] 0x4CEBC1ED31E8925E
function N_0x4cebc1ed31e8925e(cutsceneName) end

-- [+] 0x4E52E752C76E7E7A
function N_0x4e52e752c76e7e7a(p0) end

-- [+] 0x4FCD976DA686580C
function N_0x4fcd976da686580c(p0) end

-- [+] 0x5068F488DDB54DD8
function N_0x5068f488ddb54dd8() end

-- [+] 0x54E22EA2C1956A8D
function N_0x54e22ea2c1956a8d(p0) end

-- [+] 0x54F157E0336A3822
function N_0x54f157e0336a3822(ped, p1, p2) end

-- [+] 0x583DF8E3D4AFBD98
function N_0x583df8e3d4afbd98() end

-- [+] 0x59424BD75174C9B1
function N_0x59424bd75174c9b1() end

-- [+] 0x5A43C76F7FC7BA5F
function N_0x5a43c76f7fc7ba5f() end

-- [+] 0x5B0316762AFD4A64
function N_0x5b0316762afd4a64() end

-- [+] 0x5B1F2E327B6B6FE1
function N_0x5b1f2e327b6b6fe1() end

-- [+] 0x5B73C77D9EB66E24
function N_0x5b73c77d9eb66e24(p0) end

-- [+] 0x5C41E6BABC9E2112
function N_0x5c41e6babc9e2112(p0) end

-- [+] 0x5C48A1D6E3B33179
function N_0x5c48a1d6e3b33179(cam) end

-- [+] 0x5D96CFB59DA076A0
function N_0x5d96cfb59da076a0(vehicle, p1, p2) end

-- [+] 0x5DBF05DB5926D089
function N_0x5dbf05db5926d089(p0) end

-- [+] 0x5DEBD9C4DC995692
function N_0x5debd9c4dc995692() end

-- [+] 0x5EDEF0CF8C1DAB3C
function N_0x5edef0cf8c1dab3c() end

-- [+] 0x5F6DF3D92271E8A1
function N_0x5f6df3d92271e8a1(toggle) end

-- [+] 0x615D3925E87A3B26
function N_0x615d3925e87a3b26(checkpoint) end

-- [+] 0x61F95E5BB3E0A8C6
function N_0x61f95e5bb3e0a8c6(p0) end

-- [+] 0x62374889A4D59F72
function N_0x62374889a4d59f72() end

-- [+] 0x62ECFCFDEE7885D6
function N_0x62ecfcfdee7885d6() end

-- [+] 0x63EB2B972A218CAC
function N_0x63eb2b972a218cac() end

-- [+] 0x649C97D52332341A
function N_0x649c97d52332341a(p0) end

-- [+] 0x65D2EBB47E1CEC21
function N_0x65d2ebb47e1cec21(toggle) end

-- [+] 0x693478ACBD7F18E7
function N_0x693478acbd7f18e7() end

-- [+] 0x6A51F78772175A51
function N_0x6a51f78772175a51(toggle) end

-- [+] 0x6CD79468A1E595C6
function N_0x6cd79468a1e595c6(padIndex) end

-- [+] 0x6F2135B6129620C1
function N_0x6f2135b6129620c1(toggle) end

-- [+] 0x6FDDF453C0C756EC
function N_0x6fddf453c0c756ec() end

-- [+] 0x703CC7F60CBB2B57
function N_0x703cc7f60cbb2b57(p0) end

-- [+] 0x705A276EBFF3133D
function N_0x705a276ebff3133d() end

-- [+] 0x71E7B2E657449AAD
function N_0x71e7b2e657449aad() end

-- [+] 0x7295C203DD659DFE
function N_0x7295C203DD659DFE() end

-- [+] 0x759650634F07B6B4
function N_0x759650634f07b6b4(p0) end

-- [+] 0x7A42B2E236E71415
function N_0x7a42b2e236e71415() end

-- [+] 0x7AC24EAB6D74118D
function N_0x7ac24eab6d74118d(p0) end

-- [+] 0x7EC6F9A478A6A512
function N_0x7ec6f9a478a6a512() end

-- [+] 0x7F8F6405F4777AF6
function N_0x7f8f6405f4777af6(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9) end

-- [+] 0x7F96F23FA9B73327
function N_0x7f96f23fa9b73327(modelHash) end

-- [+] 0x7FA5D82B8F58EC06
function N_0x7fa5d82b8f58ec06() end

-- [+] 0x814AF7DCAACC597B
function N_0x814af7dcaacc597b(p0) end

-- [+] 0x8269816F6CFD40F8
function N_0x8269816f6cfd40f8(p0, name) end

-- [+] 0x82ACC484FFA3B05F
function N_0x82acc484ffa3b05f(p0) end

-- [+] 0x851CD923176EBA7C
function N_0x851cd923176eba7c() end

-- [+] 0x8951EB9C6906D3C8
function N_0x8951eb9c6906d3c8() end

-- [+] 0x8CDE909A0370BB3A
function N_0x8cde909a0370bb3a(toggle) end

-- [+] 0x8D74E26F54B4E5C3
function N_0x8d74e26f54b4e5c3(p0) end

-- [+] 0x8D9DF6ECA8768583
function N_0x8d9df6eca8768583(threadId) end

-- [+] 0x908311265D42A820
function N_0x908311265d42a820(p0) end

-- [+] 0x916CA67D26FD1E37
function N_0x916ca67d26fd1e37(p0) end

-- [+] 0x91EF6EE6419E5B97
function N_0x91ef6ee6419e5b97(p0) end

-- [+] 0x933BBEEB8C61B5F4
function N_0x933bbeeb8c61b5f4() end

-- [+] 0x949F397A288B28B3
function N_0x949f397a288b28b3(p0) end

-- [+] 0x95A7DABDDBB78AE7
function N_0x95a7dabddbb78ae7(iplName1, iplName2) end

-- [+] 0x9641588DAB93B4B5
function N_0x9641588dab93b4b5(p0) end

-- [+] 0x97E7E2C04245115B
function N_0x97e7e2c04245115b(p0) end

-- [+] 0x98D18905BF723B99
function N_0x98d18905bf723b99() end

-- [+] 0x98EDF76A7271E4F2
function N_0x98edf76a7271e4f2() end

-- [+] 0x9B079E5221D984D3
function N_0x9b079e5221d984d3(p0) end

-- [+] 0x9DFE13ECDC1EC196
function N_0x9dfe13ecdc1ec196(p0, p1) end

-- [+] 0x9F97DA93681F87EA
function N_0x9f97da93681f87ea() end

-- [+] 0xA0AD167E4B39D9A2
function N_0xa0ad167e4b39d9a2(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13) end

-- [+] 0xA0CEFCEA390AAB9B
function N_0xa0cefcea390aab9b(p0) end

-- [+] 0xA0FE76168A189DDB
function N_0xa0fe76168a189ddb() end

-- [+] 0xA2767257A320FC82
function N_0xa2767257a320fc82(p0, p1) end

-- [+] 0xA46B73FAA3460AE1
function N_0xa46b73faa3460ae1(p0) end

-- [+] 0xA4A0065E39C9F25C
function N_0xa4a0065e39c9f25c(p0, p1, fadeInAfterLoad, p3) end

-- [+] 0xA7092AFE81944852
function N_0xa7092afe81944852() end

-- [+] 0xAABD62873FFB1A33
function N_0xaabd62873ffb1a33(p0, p1) end

-- [+] 0xAAE9BE70EC7C69AB
function N_0xaae9be70ec7c69ab(p0, p1, p2, p3, p4, p5, p6, p7) end

-- [+] 0xADD6627C4D325458
function N_0xadd6627c4d325458(p0) end

-- [+] 0xAE51BC858F32BA66
function N_0xae51bc858f32ba66(p0, p1, p2, p3, p4) end

-- [+] 0xB1381B97F70C7B30
function N_0xb1381b97f70c7b30() end

-- [+] 0xB2EBE8CBC58B90E9
function N_0xb2ebe8cbc58b90e9() end

-- [+] 0xB3C641F3630BF6DA
function N_0xb3c641f3630bf6da(p0) end

-- [+] 0xB51B9AB9EF81868C
function N_0xb51b9ab9ef81868c(toggle) end

-- [+] 0xB569F41F3E7E83A4
function N_0xb569f41f3e7e83a4(p0) end

-- [+] 0xBA0127DA25FD54C9
function N_0xba0127da25fd54c9(p0, p1) end

-- [+] 0xBA3D194057C79A7B
function N_0xba3d194057c79a7b(p0) end

-- [+] 0xBA4B8D83BDC75551
function N_0xba4b8d83bdc75551(p0) end

-- [+] 0xBB90E12CAC1DAB25
function N_0xbb90e12cac1dab25(p0) end

-- [+] 0xBCEDB009461DA156
function N_0xbcedb009461da156() end

-- [+] 0xBE197EAA669238F4
function N_0xbe197eaa669238f4(p0, p1, p2, p3) end

-- [+] 0xBEB2D9A1D9A8F55A
function N_0xbeb2d9a1d9a8f55a(p0, p1, p2, p3) end

-- [+] 0xBED8CA5FF5E04113
function N_0xbed8ca5ff5e04113(p0, p1, p2, p3) end

-- [+] 0xBF72910D0F26F025
function N_0xbf72910d0f26f025() end

-- [+] 0xC0416B061F2B7E5E
function N_0xc0416b061f2b7e5e(p0) end

-- [+] 0xC35A6D07C93802B2
function N_0xc35a6d07c93802b2() end

-- [+] 0xC5C8F970D4EDFF71
function N_0xc5c8f970d4edff71(p0) end

-- [+] 0xC61B86C9F61EB404
function N_0xc61b86c9f61eb404(toggle) end

-- [+] 0xC8391C309684595A
function N_0xc8391c309684595a() end

-- [+] 0xC8B5C4A79CC18B94
function N_0xc8b5c4a79cc18b94(cam) end

-- [+] 0xCA465D9CC0D231BA
function N_0xca465d9cc0d231ba(p0) end

-- [+] 0xCA4AE345A153D573
function N_0xca4ae345a153d573(p0) end

-- [+] 0xCB0360EFEFB2580D
function N_0xcb0360efefb2580d(padIndex) end

-- [+] 0xCB82A0BF0E3E3265
function N_0xcb82a0bf0e3e3265(p0) end

-- [+] 0xCCD078C2665D2973
function N_0xccd078c2665d2973(p0) end

-- [+] 0xCED08CBE8EBB97C7
function N_0xced08cbe8ebb97c7(p0, p1) end

-- [+] 0xCFD16F0DB5A3535C
function N_0xcfd16f0db5a3535c(toggle) end

-- [+] 0xD10282B6E3751BA0
function N_0xd10282b6e3751ba0() end

-- [+] 0xD1C55B110E4DF534
function N_0xd1c55b110e4df534(p0) end

-- [+] 0xD642319C54AADEB6
function N_0xd642319c54aadeb6() end

-- [+] 0xD9F692D349249528
function N_0xd9f692d349249528() end

-- [+] 0xDB1EA9411C8911EC
function N_0xdb1ea9411c8911ec(checkpointHandle) end

-- [+] 0xDB90C6CCA48940F1
function N_0xdb90c6cca48940f1(p0) end

-- [+] 0xDD79DF9F4D26E1C9
function N_0xdd79df9f4d26e1c9() end

-- [+] 0xE111A7C0D200CBC5
function N_0xe111a7c0d200cbc5(p0, p1) end

-- [+] 0xE1615EC03B3BB4FD
function N_0xe1615ec03b3bb4fd() end

-- [+] 0xE2892E7E55D7073A
function N_0xe2892e7e55d7073a(p0) end

-- [+] 0xE36A98D8AB3D3C66
function N_0xe36a98d8ab3d3c66(p0) end

-- [+] 0xE3D969D2785FFB5E
function N_0xe3d969d2785ffb5e() end

-- [+] 0xE532EC1A63231B4F
function N_0xe532ec1a63231b4f(p0, p1) end

-- [+] 0xE59343E9E96529E7
function N_0xe59343e9e96529e7() end

-- [+] 0xE63D7C6EECECB66B
function N_0xe63d7c6eececb66b(toggle) end

-- [+] 0xE791DF1F73ED2C8B
function N_0xe791df1f73ed2c8b(p0) end

-- [+] 0xE95B0C7D5BA3B96B
function N_0xe95b0c7d5ba3b96b(ped) end

-- [+] 0xEB078CA2B5E82ADD
function N_0xeb078ca2b5e82add(p0, p1) end

-- [+] 0xEB2104E905C6F2E9
function N_0xeb2104e905c6f2e9() end

-- [+] 0xEBD3205A207939ED
function N_0xebd3205a207939ed(p0) end

-- [+] 0xEC72C258667BE5EA
function N_0xec72c258667be5ea(p0) end

-- [+] 0xEF398BEEE4EF45F9
function N_0xef398beee4ef45f9(p0) end

-- [+] 0xEF39EE20C537E98C
function N_0xef39ee20c537e98c(p0, p1, p2, p3, p4, p5) end

-- [+] 0xEFABC7722293DA7C
function N_0xefabc7722293da7c() end

-- [+] 0xF239400E16C23E08
function N_0xf239400e16c23e08(padIndex, p1) end

-- [+] 0xF2CA003F167E21D2
function N_0xf2ca003f167e21d2() end

-- [+] 0xF3F776ADA161E47D
function N_0xf3f776ada161e47d(p0, p1) end

-- [+] 0xF4A0DADB70F57FA6
function N_0xf4a0dadb70f57fa6() end

-- [+] 0xF51D36185993515D
function N_0xf51d36185993515d(checkpoint, posX, posY, posZ, unkX, unkY, unkZ) end

-- [+] 0xF55E4046F6F831DC
function N_0xf55e4046f6f831dc(p0, p1) end

-- [+] 0xF78B803082D4386F
function N_0xf78b803082d4386f(p0) end

-- [+] 0xF8155A7F03DDFC8E
function N_0xf8155a7f03ddfc8e(p0) end

-- [+] 0xFA1E0E893D915215
function N_0xfa1e0e893d915215(toggle) end

-- [+] 0xFA3FFB0EEBC288A3
function N_0xfa3ffb0eebc288a3(p0) end

-- [+] 0xFAA457EF263E8763
function N_0xfaa457ef263e8763(p0, name) end

-- [+] 0xFB00CA71DA386228
function N_0xfb00ca71da386228() end

-- [+] 0xFB199266061F820A
function N_0xfb199266061f820a() end

-- [+] 0xFCF6788FC4860CD4
function N_0xfcf6788fc4860cd4(checkpoint) end

-- [+] 0xFD3151CD37EA2245
function N_0xfd3151cd37ea2245(entity) end

-- Namespace: RegisterTextLabelToSave (1 natives)

-- [+] 0x6F7794F28C6B2535
function RegisterTextLabelToSave_2(p0, name) end

-- Namespace: SetBinkMovieUnk (1 natives)

-- [+] 0xF816F2933752322D
function SetBinkMovieUnk_2(binkMovie, p1) end

-- Namespace: SwitchToInputMappingScheme (1 natives)

-- [+] 0x4683149ED1DDE7A1
function SwitchToInputMappingScheme_2(name) end

-- Namespace: UNKNOWN (969 natives)

-- [+] 0x73D57CFFDD12C355
function Absf(value) end

-- [+] 0xF0D31AD191A74F87
function Absi(value) end

-- [+] 0x1D08B970013C34B6
function Acos(p0) end

-- [+] 0x34CFC4C2A38E83E3
function ActivateCamWithInterpAndFovCurve(camTo, camFrom, duration, easeLocation, easeRotation, easeFove) end

-- [+] 0x4DCDF92BF64236CD
function ActivityFeedCreate(captionString, condensedCaptionString) end

-- [+] 0x8609C75EC438FB3B
function AddCamSplineNode(camera, x, y, z, xRot, yRot, zRot, length, p8, transitionType) end

-- [+] 0x0FB82563989CF4FB
function AddCamSplineNodeUsingCamera(cam, cam2, length, p3) end

-- [+] 0x0A9F2A468B328E74
function AddCamSplineNodeUsingCameraFrame(cam, cam2, p2, p3) end

-- [+] 0x609278246A29CA34
function AddCamSplineNodeUsingGameplayFrame(cam, p1, p2) end

-- [+] 0xB302244A1839BDAD
function AddDecal(decalType, posX, posY, posZ, dirX, dirY, dirZ, sideX, sideY, sideZ, width, height, rCoef, gCoef, bCoef, opacity, timeout, isLongRange, isDynamic, useComplexColn) end

-- [+] 0x918C7B2D2FF3928B
function AddDispatchSpawnBlockingAngledArea(x1, y1, z1, x2, y2, z2, width) end

-- [+] 0x2D4259F1FEB81DA9
function AddDispatchSpawnBlockingArea(x1, y1, x2, y2) end

-- [+] 0x9CD43EEE12BF4DD0
function AddEntityIcon(entity, icon) end

-- [+] 0x1F464EF988465A81
function AddHospitalRestart(x, y, z, p3, p4) end

-- [+] 0x0BC3144DEB678666
function AddModelToCreatorBudget(modelHash) end

-- [+] 0x126D7F89FE859A5E
function AddOilDecal(x, y, z, groundLvl, width, transparency) end

-- [+] 0x4F5212C7AD880DF8
function AddPetrolDecal(x, y, z, groundLvl, width, transparency) end

-- [+] 0x967278682CB6967A
function AddPetrolTrailDecalInfo(x, y, z, p3) end

-- [+] 0x452736765B31FC4B
function AddPoliceRestart(p0, p1, p2, p3, p4) end

-- [+] 0x67F6413D3220E18D
function AddPopMultiplierArea(x1, y1, z1, x2, y2, z2, p6, p7, p8) end

-- [+] 0x32C7A7E8C43A1F80
function AddPopMultiplierSphere(x, y, z, radius, pedMultiplier, vehicleMultiplier, p6, p7) end

-- [+] 0x69FE6DC87BD2A5E9
function AddReplayStatValue(value) end

-- [+] 0x1A992DA297A4630C
function AddStuntJump(x1, y1, z1, x2, y2, z2, x3, y3, z3, x4, y4, z4, camX, camY, camZ, unk1, unk2, unk3) end

-- [+] 0xBBE5D803A5360CBF
function AddStuntJumpAngled(x1, y1, z1, x2, y2, z2, radius1, x3, y3, z3, x4, y4, z4, radius2, camX, camY, camZ, unk1, unk2, unk3) end

-- [+] 0xB8721407EE9C3FF6
function AddTacticalAnalysisPoint(x, y, z) end

-- [+] 0x1A8E2C8B9CF4549C
function AddTcmodifierOverride(modifierName1, modifierName2) end

-- [+] 0x428BDCB9DA58DA53
function AddVehicleCrewEmblem(vehicle, ped, boneIndex, x1, x2, x3, y1, y2, y3, z1, z2, z3, scale, p13, alpha) end

-- [+] 0xDEA36202FC3382DF
function AllowMissionCreatorWarp(toggle) end

-- [+] 0x8E2A065ABDAE6994
function AllowPlayerSwitchAscent() end

-- [+] 0xAD5FDF34B81BFE79
function AllowPlayerSwitchDescent() end

-- [+] 0x74DE2E8739086740
function AllowPlayerSwitchOutro() end

-- [+] 0x43D1680C6D19A8E9
function AllowPlayerSwitchPan() end

-- [+] 0xDF2E1F7742402E81
function AnimateGameplayCamZoom(p0, distance) end

-- [+] 0xA2746EEAE3E577CD
function AnimatedShakeCam(cam, p1, p2, p3, amplitude) end

-- [+] 0xC2EAE3FB8CDBED31
function AnimatedShakeScriptGlobal(p0, p1, p2, p3) end

-- [+] 0xE35B38A27E8E7179
function AnimpostfxGetUnk(effectName) end

-- [+] 0x36AD3E690DA5ACEB
function AnimpostfxIsRunning(effectName) end

-- [+] 0x2206BF9A37B7F724
function AnimpostfxPlay(effectName, duration, looped) end

-- [+] 0x068E835A1D0DC0E3
function AnimpostfxStop(effectName) end

-- [+] 0xB4EDDC19532BFB85
function AnimpostfxStopAll() end

-- [+] 0xD2209BE128B5418C
function AnimpostfxStopAndDoUnk(effectName) end

-- [+] 0x5AA3BEFA29F03AD4
function AreProfileSettingsValid() end

-- [+] 0x0C515FAB3FF9EA92
function AreStringsEqual(string1, string2) end

-- [+] 0xC843060B5765DCE7
function Asin(value) end

-- [+] 0xA9D1795CD5043663
function Atan(p0) end

-- [+] 0x8927CBF9D22261A4
function Atan2(p0, p1) end

-- [+] 0xFEDB7D269E8C60E3
function AttachCamToEntity(cam, entity, xOffset, yOffset, zOffset, isRelative) end

-- [+] 0x61A3DBA14AB7F411
function AttachCamToPedBone(cam, ped, boneIndex, xOffset, yOffset, zOffset, isRelative) end

-- [+] 0x8DB3F12A02CAEF72
function AttachCamToVehicleBone(cam, vehicle, boneIndex, relativeRotation, rotX, rotY, rotZ, offX, offY, offZ, fixedDirection) end

-- [+] 0x845BAD77CC770633
function AttachTvAudioToEntity(entity) end

-- [+] 0xE0E500246FF73D66
function BeginReplayStats(p0, p1) end

-- [+] 0xF6E48914C7A8694E
function BeginScaleformMovieMethod(scaleform, methodName) end

-- [+] 0xAB58C27C2E6123C6
function BeginScaleformMovieMethodOnFrontend(functionName) end

-- [+] 0xB9449845F73F5E9C
function BeginScaleformMovieMethodOnFrontendHeader(functionName) end

-- [+] 0x98C494FD5BDFBFD5
function BeginScaleformScriptHudMovieMethod(hudComponent, methodName) end

-- [+] 0x9BADDC94EF83B823
function BeginSrl() end

-- [+] 0xA67C35C56EB1BD9D
function BeginTakeHighQualityPhoto() end

-- [+] 0x1DD2139A9A20DCE8
function BeginTakeMissionCreatorPhoto() end

-- [+] 0x80338406F3475E55
function BeginTextCommandScaleformString(textLabel) end

-- [+] 0x9B2BD3773123EA2F
function BlockDispatchServiceResourceCreation(dispatchService, toggle) end

-- [+] 0xFBD96D87AC96D533
function CallScaleformMovieMethod(scaleform, method) end

-- [+] 0xD0837058AE2E4BEE
function CallScaleformMovieMethodWithNumber(scaleform, methodName, param1, param2, param3, param4, param5) end

-- [+] 0xEF662D8D57E290B1
function CallScaleformMovieMethodWithNumberAndString(scaleform, methodName, floatParam1, floatParam2, floatParam3, floatParam4, floatParam5, stringParam1, stringParam2, stringParam3, stringParam4, stringParam5) end

-- [+] 0x51BC1ED3CC44E8F7
function CallScaleformMovieMethodWithString(scaleform, methodName, param1, param2, param3, param4, param5) end

-- [+] 0xB56BBBCC2955D9CB
function CanRequestAssetsForCutsceneEntity() end

-- [+] 0x645D0B458D8E17B5
function CanSetEnterStateForRegisteredEntity(cutsceneEntName, modelHash) end

-- [+] 0xB2CBCD0930DFB420
function CanSetExitStateForCamera(p0) end

-- [+] 0x4C6A6451C79E4662
function CanSetExitStateForRegisteredEntity(cutsceneEntName, modelHash) end

-- [+] 0x58A39BE597CE99CD
function CancelOnscreenKeyboard() end

-- [+] 0xE6B7B0ACD4E4B75E
function CancelStuntJump() end

-- [+] 0x27CB772218215325
function CascadeShadowsClearShadowSampleType() end

-- [+] 0x80ECBC0C856D3B0B
function CascadeShadowsEnableEntityTracker(toggle) end

-- [+] 0x03FC694AE06C5A20
function CascadeShadowsInitSession() end

-- [+] 0x6DDBF9DFFC4AC080
function CascadeShadowsSetAircraftMode(p0) end

-- [+] 0xD2936CAB8B58FCBD
function CascadeShadowsSetCascadeBounds(p0, p1, p2, p3, p4, p5, p6, p7) end

-- [+] 0x5F0F3F56635809EF
function CascadeShadowsSetCascadeBoundsScale(p0) end

-- [+] 0xD39D13C9FEBF0511
function CascadeShadowsSetDynamicDepthMode(p0) end

-- [+] 0x02AC28F3A01FA04A
function CascadeShadowsSetDynamicDepthValue(p0) end

-- [+] 0x5E9DAF5A20F15908
function CascadeShadowsSetEntityTrackerScale(p0) end

-- [+] 0xB11D94BC55F41932
function CascadeShadowsSetShadowSampleType(type) end

-- [+] 0xA516C198B7DCA1E1
function ClampGameplayCamPitch(Any) end

-- [+] 0x8F993D26E0CA5E8E
function ClampGameplayCamYaw(Any) end

-- [+] 0xC79AE21974B01FB2
function CleanupAsyncInstall() end

-- [+] 0x11DB3500F042A8AA
function ClearAngledAreaOfVehicles(x1, y1, z1, x2, y2, z2, width, p7, p8, p9, p10, p11) end

-- [+] 0xA56F01F3765B93A0
function ClearArea(X, Y, Z, radius, p4, ignoreCopCars, ignoreObjects, p7) end

-- [+] 0x957838AAF91BD12D
function ClearAreaLeaveVehicleHealth(x, y, z, radius, p4, p5, p6, p7) end

-- [+] 0x04F8FC8FCF58F88D
function ClearAreaOfCops(x, y, z, radius) end

-- [+] 0xDD9B9B385AAC7F5B
function ClearAreaOfObjects(x, y, z, radius, flags) end

-- [+] 0xBE31FD6CE464AC59
function ClearAreaOfPeds(x, y, z, radius) end

-- [+] 0x0A1CB9094635D1A6
function ClearAreaOfProjectiles(x, y, z, radius) end

-- [+] 0x01C7B9B38428AEB6
function ClearAreaOfVehicles(x, y, z, radius, p4, p5, p6, p7, p8) end

-- [+] 0xE80492A9AC099A93
function ClearBit(address, offset) end

-- [+] 0x957E790EA1727B64
function ClearCloudHat() end

-- [+] 0xFF0B610F6BE0D7AF
function ClearDrawOrigin() end

-- [+] 0x92CCC17A7A2285DA
function ClearExtraTimecycleModifier() end

-- [+] 0x31B73D1EA9F01DA2
function ClearFocus() end

-- [+] 0xCE58B1CFB9290813
function ClearHdArea() end

-- [+] 0x338D2E3477711050
function ClearOverrideWeather() end

-- [+] 0x1B1AB132A16FDA55
function ClearReplayStats() end

-- [+] 0xA2716D40842EAF79
function ClearRestartCustomPosition() end

-- [+] 0xB3CD58CCA6CDA852
function ClearTacticalAnalysisPoints() end

-- [+] 0x0F07E7745A236711
function ClearTimecycleModifier() end

-- [+] 0xBEB3D46BB7F043C0
function ClearTvChannelPlaylist(tvChannel) end

-- [+] 0x0CF97F497FE7D048
function ClearWeatherTypeNowPersistNetwork() end

-- [+] 0xCCC39339BEF76CF5
function ClearWeatherTypePersist() end

-- [+] 0x1E34710ECD4AB0EB
function CompareStrings(str1, str2, matchCase, maxLength) end

-- [+] 0x213AEB2B90CBA7AC
function CopyMemory(dst, src, size) end

-- [+] 0xC3981DCE61D9E13F
function CreateCam(camName, active) end

-- [+] 0xB51194800B257161
function CreateCamWithParams(camName, posX, posY, posZ, rotX, rotY, rotZ, fov, active, rotationOrder) end

-- [+] 0x5E3CF89C6BCCA67D
function CreateCamera(camHash, active) end

-- [+] 0x6ABFA3E16460F22D
function CreateCameraWithParams(camHash, posX, posY, posZ, rotX, rotY, rotZ, fov, active, rotationOrder) end

-- [+] 0x0134F0835AB6BFCB
function CreateCheckpoint(type, posX1, posY1, posZ1, posX2, posY2, posZ2, diameter, red, green, blue, alpha, reserved) end

-- [+] 0x741B0129D4560F31
function CreateCinematicShot(p0, p1, p2, entity) end

-- [+] 0x3F892CAF67444AE7
function CreateIncident(dispatchService, x, y, z, numUnits, radius, outIncidentID) end

-- [+] 0x05983472F0494E60
function CreateIncidentWithEntity(dispatchService, ped, numUnits, radius, outIncidentID) end

-- [+] 0xE2C9439ED45DEA60
function CreateTrackedPoint() end

-- [+] 0x487A82C650EB7799
function CustomMenuCoordinates(p0) end

-- [+] 0xF5ED37F54CD4D52E
function DeleteCheckpoint(checkpoint) end

-- [+] 0x556C1AA270D5A207
function DeleteIncident(incidentId) end

-- [+] 0xDC518000E39DAE1F
function DeleteStuntJump(p0) end

-- [+] 0x8E5FB15663F79120
function DestroyAllCams(bScriptHostCam) end

-- [+] 0x865908C81A2C22E9
function DestroyCam(cam, bScriptHostCam) end

-- [+] 0xB25DC90BAD56CA42
function DestroyTrackedPoint(point) end

-- [+] 0xA2FABBE87F4BAD82
function DetachCam(cam) end

-- [+] 0x1A31FE0049E542F6
function DisableAimCamThisUpdate() end

-- [+] 0x5F4B6931816E599B
function DisableAllControlActions(padIndex) end

-- [+] 0x2AED6301F67007D5
function DisableCamCollisionForEntity(entity) end

-- [+] 0x49482F9FCD825AAA
function DisableCamCollisionForObject(entity) end

-- [+] 0xADFF1B2A555F5FBA
function DisableCinematicBonnetCameraThisUpdate() end

-- [+] 0xFE99B66D079CF6BC
function DisableControlAction(padIndex, control, disable) end

-- [+] 0xC8535819C450EBA8
function DisableHospitalRestart(hospitalIndex, toggle) end

-- [+] 0x7F4724035FDCA1DD
function DisableInputGroup(padIndex) end

-- [+] 0x2BF72AD5B41AA739
function DisableMoonCycleOverride() end

-- [+] 0x3669F1B198DCAA4F
function DisableOcclusionThisFrame() end

-- [+] 0xDE2EF5DA284CC8DF
function DisableOnFootFirstPersonViewThisUpdate() end

-- [+] 0x23285DED6EBD7EA3
function DisablePoliceRestart(policeIndex, toggle) end

-- [+] 0xDE81239437E8C5A8
function DisableScreenblurFade() end

-- [+] 0xEFD97FF47B745B8D
function DisableScriptAmbientEffects(p0) end

-- [+] 0xA5272EBEDD4747F6
function DisableStuntJumpSet(p0) end

-- [+] 0xBD605B8E0E18B3BB
function DisableSwitchOutroFx() end

-- [+] 0xC9F98AC1884E73A2
function DisableVehicleDistantlights(toggle) end

-- [+] 0x00DC833F2568DBF6
function DisplayOnscreenKeyboard(keyboardType, windowTitle, description, defaultText, defaultConcat1, defaultConcat2, defaultConcat3, maxInputLength) end

-- [+] 0xCA78CFA0366592FE
function DisplayOnscreenKeyboardWithLongerInitialString(keyboardType, windowTitle, AnyPtr) end

-- [+] 0x50EEAAD86232EE55
function DoAutoSave() end

-- [+] 0xD4E8E24955024033
function DoScreenFadeIn(duration) end

-- [+] 0x891B5B39AC6302AF
function DoScreenFadeOut(duration) end

-- [+] 0x2DA49C3B79856961
function DoesAnimDictExist(animDict) end

-- [+] 0xA7A932170592B50E
function DoesCamExist(cam) end

-- [+] 0x499EF20C5DB25C59
function DoesCutsceneEntityExist(cutsceneEntName, modelHash) end

-- [+] 0x5E657EF1099EDD65
function DoesLatestBriefStringExist(briefValue) end

-- [+] 0x74AFEF0D2E1E409B
function DoesParticleFxLoopedExist(ptfxHandle) end

-- [+] 0x1327E2FE9746BAEE
function DoesPopMultiplierAreaExist(id) end

-- [+] 0x171BAFB3C60389F4
function DoesPopMultiplierSphereExist(id) end

-- [+] 0x060D935D3981A275
function DoesVehicleHaveCrewEmblem(vehicle, p1) end

-- [+] 0x22A249A53034450A
function DontRenderInGameUi(p0) end

-- [+] 0x7118E83EEB9F7238
function DrawBinkMovie(binkMovie, posX, posY, scaleX, scaleY, rotation, r, g, b, a) end

-- [+] 0xD3A9971CADAC7252
function DrawBox(x1, y1, z1, x2, y2, z2, red, green, blue, alpha) end

-- [+] 0x083A2CA4F2E573BD
function DrawDebugBox(x1, y1, z1, x2, y2, z2, r, g, b, a) end

-- [+] 0x73B1189623049839
function DrawDebugCross(x, y, z, size, red, green, blue, alpha) end

-- [+] 0x7FDFADE676AA3CB0
function DrawDebugLine(x1, y1, z1, x2, y2, z2, r, g, b, a) end

-- [+] 0xD8B9A8AC5608FF94
function DrawDebugLineWithTwoColours(x1, y1, z1, x2, y2, z2, r1, g1, b1, r2, g2, b2, alpha1, alpha2) end

-- [+] 0xAAD68E1AB39DA632
function DrawDebugSphere(x, y, z, radius, red, green, blue, alpha) end

-- [+] 0x3903E216620488E8
function DrawDebugText(text, x, y, z, red, green, blue, alpha) end

-- [+] 0x2BC54A8188768488
function DrawInteractiveSprite(textureDict, textureName, screenX, screenY, width, height, heading, red, green, blue, alpha) end

-- [+] 0xF2A1B2771A01DBD4
function DrawLightWithRange(posX, posY, posZ, colorR, colorG, colorB, range, intensity) end

-- [+] 0xF49E9A9716A04595
function DrawLightWithRangeAndShadow(x, y, z, r, g, b, range, intensity, shadow) end

-- [+] 0x6B7256074AE34680
function DrawLine(x1, y1, z1, x2, y2, z2, red, green, blue, alpha) end

-- [+] 0x1072F115DAB0717E
function DrawLowQualityPhotoToPhone(p0, p1) end

-- [+] 0x28477EC23D892089
function DrawMarker(type, posX, posY, posZ, dirX, dirY, dirZ, rotX, rotY, rotZ, scaleX, scaleY, scaleZ, red, green, blue, alpha, bobUpAndDown, faceCamera, rotationOrder, rotate, textureDict, textureName, drawOnEnts) end

-- [+] 0xAC26716048436851
function DrawPoly(x1, y1, z1, x2, y2, z2, x3, y3, z3, red, green, blue, alpha) end

-- [+] 0x3A618A217E5154F0
function DrawRect(x, y, width, height, r, g, b, a) end

-- [+] 0x54972ADAF0294A93
function DrawScaleformMovie(scaleformHandle, x, y, width, height, red, green, blue, alpha, unk) end

-- [+] 0x0DF606929C105BE1
function DrawScaleformMovieFullscreen(scaleform, red, green, blue, alpha, unk) end

-- [+] 0xCF537FDE4FBD4CE5
function DrawScaleformMovieFullscreenMasked(scaleform1, scaleform2, red, green, blue, alpha) end

-- [+] 0x98C4FE6EC34154CA
function DrawShowroom(p0, ped, p2, posX, posY, posZ) end

-- [+] 0x799017F9E3B10112
function DrawSphere(x, y, z, radius, r, g, b, opacity) end

-- [+] 0xD0F64B265C8C8B33
function DrawSpotLight(posX, posY, posZ, dirX, dirY, dirZ, colorR, colorG, colorB, distance, brightness, hardness, radius, falloff) end

-- [+] 0x5BCA583A583194DB
function DrawSpotLightWithShadow(posX, posY, posZ, dirX, dirY, dirZ, colorR, colorG, colorB, distance, brightness, roundness, radius, falloff, shadowId) end

-- [+] 0xE7FFAE5EBF23D890
function DrawSprite(textureDict, textureName, screenX, screenY, width, height, heading, red, green, blue, alpha) end

-- [+] 0x95812F9B26074726
function DrawSpriteUv(textureDict, textureName, x, y, width, height, u1, v1, u2, v2, heading, red, green, blue, alpha) end

-- [+] 0x29280002282F1928
function DrawTexturedPoly(x1, y1, z1, x2, y2, z2, x3, y3, z3, red, green, blue, alpha, textureDict, textureName, u1, v1, w1, u2, v2, w2, u3, v3, w3) end

-- [+] 0xFDDC2B4ED3C69DF0
function DrawTvChannel(xPos, yPos, xScale, yScale, rotation, red, green, blue, alpha) end

-- [+] 0x9DCE1F0F78260875
function EnableAlienBloodVfx(toggle) end

-- [+] 0xA5FFE9B05F199DE7
function EnableAllControlActions(padIndex) end

-- [+] 0xD821490579791273
function EnableClownBloodVfx(toggle) end

-- [+] 0x351220255D64C155
function EnableControlAction(padIndex, control, enable) end

-- [+] 0xEA7F0AD7E9BA676F
function EnableCrosshairThisFrame() end

-- [+] 0xDC0F817884CDD856
function EnableDispatchService(dispatchService, toggle) end

-- [+] 0x2C328AF17210F009
function EnableMoonCycleOverride(phase) end

-- [+] 0x74C180030FDE4B69
function EnableMovieKeyframeWait(toggle) end

-- [+] 0x873FA65C778AD970
function EnableMovieSubtitles(toggle) end

-- [+] 0xE369A5783B866016
function EnableStuntJumpSet(p0) end

-- [+] 0xD4793DFF3AF2ABCD
function EnableSwitchPauseBeforeDescent() end

-- [+] 0x28A04B411933F8A6
function EnableTennisMode(ped, toggle, p2) end

-- [+] 0x0A123435A26C36CD
function EndPetrolTrailDecals() end

-- [+] 0xA23E821FBDF8A5F2
function EndReplayStats() end

-- [+] 0xC6796A8FFA375E53
function EndScaleformMovieMethod() end

-- [+] 0xC50AA39A577AF886
function EndScaleformMovieMethodReturnValue() end

-- [+] 0x0A41540E63C9EE17
function EndSrl() end

-- [+] 0x362E2D3FE93A9959
function EndTextCommandScaleformString() end

-- [+] 0xAE4E8157D9ECF087
function EndTextCommandUnparsedScaleformString() end

-- [+] 0xD77EDADB0420E6E0
function FadeDecalsInRange(Any) end

-- [+] 0xC9B18B4619F48F7B
function FadeUpPedLight(p0) end

-- [+] 0x6874E2190B0C1972
function FindSpawnPointInDirection(posX, posY, posZ, dirX, dirY, dirZ, distance, spawnPoint) end

-- [+] 0xA41BCD7213805AAC
function ForceCinematicRenderingThisUpdate(enable) end

-- [+] 0xC0AA53F866B3134D
function ForceGameStatePlaying() end

-- [+] 0xF6062E089251C898
function ForceLightningFlash() end

-- [+] 0xDC459CFA0CCE245B
function ForceRenderInGameUi(toggle) end

-- [+] 0xD801CC02177FA3F1
function FreeMemoryForHighQualityPhoto() end

-- [+] 0x6A12D88881435DCA
function FreeMemoryForLowQualityPhoto() end

-- [+] 0x0A46AF8A78DC5E0A
function FreeMemoryForMissionCreatorPhoto() end

-- [+] 0x873C9F3104101DD3
function GetActualScreenResolution(x, y) end

-- [+] 0x8B3CA62B1EF19B62
function GetAllocatedStackSize() end

-- [+] 0xFC859E2374407556
function GetAllowMovementWhileZoomed() end

-- [+] 0xF1307EF624A80D87
function GetAspectRatio(physicalAspect) end

-- [+] 0xB335F761606DB47C
function GetBaseElementMetadata(p1, p2, p3, p4) end

-- [+] 0x4750FC27570311EC
function GetBenchmarkIterationsFromCommandLine() end

-- [+] 0x1B2366C3F2A5C8DF
function GetBenchmarkPassFromCommandLine() end

-- [+] 0xE599A503B3837E1B
function GetBenchmarkTime() end

-- [+] 0x8E17DDD6B9D5BF29
function GetBinkMovieTime(binkMovie) end

-- [+] 0x53158863FCC0893A
function GetBitsInRange(var, rangeStart, rangeEnd) end

-- [+] 0x19CAFA3C87F7C2FF
function GetCamActiveViewModeContext() end

-- [+] 0xA10B2DB49E92A6B0
function GetCamAnimCurrentPhase(cam) end

-- [+] 0xBAC038F7459AE5AE
function GetCamCoord(cam) end

-- [+] 0x06D153C0B99B6128
function GetCamDofStrength(cam) end

-- [+] 0xB60A9CFEB21CA6AA
function GetCamFarClip(cam) end

-- [+] 0x255F8DAFD540D397
function GetCamFarDof(cam) end

-- [+] 0xC3330A45CCCDB26A
function GetCamFov(cam) end

-- [+] 0xC520A34DAFBF24B1
function GetCamNearClip(cam) end

-- [+] 0xC2612D223D915A1C
function GetCamNearDof(cam) end

-- [+] 0x7D304C1C955E3E12
function GetCamRot(cam, rotationOrder) end

-- [+] 0xB22B17DF858716A6
function GetCamSplineNodeIndex(cam) end

-- [+] 0xD9D0E694C8282C96
function GetCamSplineNodePhase(cam) end

-- [+] 0xB5349E36C546509A
function GetCamSplinePhase(cam) end

-- [+] 0xEE778F8C7E1142E2
function GetCamViewModeForContext(context) end

-- [+] 0x20AC25E781AE4A84
function GetCloudHatOpacity() end

-- [+] 0xEC3C9B8D5327B563
function GetControlNormal(padIndex, control) end

-- [+] 0x5B84D09CEC5209C5
function GetControlUnboundNormal(padIndex, control) end

-- [+] 0xD95E79E8686D2C27
function GetControlValue(padIndex, control) end

-- [+] 0x8D7A43EC6A5FEA45
function GetCoordsOfProjectileTypeInArea(x1, y1, z1, x2, y2, z2, projectileHash, projectilePos, ownedByPlayer) end

-- [+] 0xDFB4138EEFED7B81
function GetCoordsOfProjectileTypeWithinDistance(ped, weaponHash, distance, outCoords, ownedByPlayer) end

-- [+] 0x473151EBC762C6DA
function GetCurrentNumberOfCloudPhotos() end

-- [+] 0x0ABC54DE641DC0FC
function GetCutFileNumSections(cutsceneName) end

-- [+] 0x971D7B15BCDBEF99
function GetCutsceneEndTime() end

-- [+] 0x710286BC5EF4D6E1
function GetCutscenePlayTime() end

-- [+] 0x49010A6A396553D8
function GetCutsceneSectionPlaying() end

-- [+] 0xE625BEABBAFFDAB9
function GetCutsceneTime() end

-- [+] 0xEE53B14A19E480D4
function GetCutsceneTotalDuration() end

-- [+] 0x77C3CEC46BE286F6
function GetDebugCamera() end

-- [+] 0x323F647679A09103
function GetDecalWashLevel(decal) end

-- [+] 0x11E65974A982637C
function GetDisabledControlNormal(padIndex, control) end

-- [+] 0x4F8A26A890FD62FB
function GetDisabledControlUnboundNormal(padIndex, control) end

-- [+] 0xF1B760881820C952
function GetDistanceBetweenCoords(x1, y1, z1, x2, y2, z2, useZ) end

-- [+] 0x0A2E9FDB9A8C62F6
function GetEntityIndexOfCutsceneEntity(cutsceneEntName, modelHash) end

-- [+] 0xC0741A26499654CD
function GetEntityIndexOfRegisteredEntity(cutsceneEntName, modelHash) end

-- [+] 0xBB0527EC6341496D
function GetExtraTimecycleModifierIndex() end

-- [+] 0x4C9296CBCD1B971E
function GetFakeWantedLevel() end

-- [+] 0xA200EB1EE790F448
function GetFinalRenderedCamCoord() end

-- [+] 0xDFC8CBC606FDB0FC
function GetFinalRenderedCamFarClip() end

-- [+] 0x9780F32BCAF72431
function GetFinalRenderedCamFarDof() end

-- [+] 0x80EC114669DAEFF4
function GetFinalRenderedCamFov() end

-- [+] 0x162F9D995753DC19
function GetFinalRenderedCamMotionBlurStrength() end

-- [+] 0xD0082607100D7193
function GetFinalRenderedCamNearClip() end

-- [+] 0xA03502FC581F7D9B
function GetFinalRenderedCamNearDof() end

-- [+] 0x5B4E4C817FCC2DFB
function GetFinalRenderedCamRot(rotationOrder) end

-- [+] 0x5F35F6732C3FBBA0
function GetFinalRenderedInWhenFriendlyFov(player) end

-- [+] 0x26903D9CD1175F2C
function GetFinalRenderedInWhenFriendlyRot(player, rotationOrder) end

-- [+] 0x7EC52CC40597D170
function GetFirstPersonAimCamZoomFactor() end

-- [+] 0x89215EC747DF244A
function GetFocusPedOnScreen(p0, p1, p2, p3, p4, p5, p6, p7, p8) end

-- [+] 0x8D4D46230B2C353A
function GetFollowPedCamViewMode() end

-- [+] 0x33E6C8EFD0CD93E9
function GetFollowPedCamZoomLevel() end

-- [+] 0xA4FF579AC0E3AAAE
function GetFollowVehicleCamViewMode() end

-- [+] 0xEE82280AB767B690
function GetFollowVehicleCamZoomLevel() end

-- [+] 0xFC8202EFC642E6F2
function GetFrameCount() end

-- [+] 0x15C40837039FFAF7
function GetFrameTime() end

-- [+] 0x9CD27B0045628463
function GetGameTimer() end

-- [+] 0x14D6F5678D8F1B37
function GetGameplayCamCoord() end

-- [+] 0x65019750A0324133
function GetGameplayCamFov() end

-- [+] 0x743607648ADD4587
function GetGameplayCamRelativeHeading() end

-- [+] 0x3A6867B4845BEDA2
function GetGameplayCamRelativePitch() end

-- [+] 0x837765A25378F0BB
function GetGameplayCamRot(rotationOrder) end

-- [+] 0xF741BD853611592D
function GetGlobalWaterType() end

-- [+] 0x9E82F0F362881B29
function GetGroundZExcludingObjectsFor3dCoord(x, y, z, groundZ, waterAsGround) end

-- [+] 0xD24D37CC275948CC
function GetHashKey(string) end

-- [+] 0xB5D7B26B45720E05
function GetIdealPlayerSwitchType(x1, y1, z1, x2, y2, z2) end

-- [+] 0xCBAD6729F7B1F4FC
function GetIndexOfCurrentLevel() end

-- [+] 0x6E04F06094C87047
function GetIsAutoSaveOff() end

-- [+] 0x84ED31191CC5D2C9
function GetIsHidef() end

-- [+] 0x2F09F7976C512404
function GetIsPetrolDecalInRange(xCoord, yCoord, zCoord, radius) end

-- [+] 0x9689123E3F213AA5
function GetIsPlayerInAnimalForm() end

-- [+] 0x0F70731BACCFBB96
function GetIsUsingAlternateDriveby() end

-- [+] 0x30CF4BDA4FCB1905
function GetIsWidescreen() end

-- [+] 0xF56DFB7B61BE7276
function GetLinePlaneIntersection(x1, y1, z1, x2, y2, z2, planeX, planeY, planeZ, planeNormalX, planeNormalY, planeNormalZ, intersectionParameter) end

-- [+] 0xBB41AFBBBC0A0287
function GetLocalPlayerAimState() end

-- [+] 0x59B9A7AF4C95133C
function GetLocalPlayerGamepadAimState() end

-- [+] 0x0C15B0E443B2349D
function GetLodscale() end

-- [+] 0xDC54A7AF8B3A14EF
function GetMaximumNumberOfCloudPhotos() end

-- [+] 0x34D23450F028B0BF
function GetMaximumNumberOfPhotos() end

-- [+] 0xA33CDCCDA663159E
function GetMissionFlag() end

-- [+] 0x03E8D3D5F549087A
function GetModelDimensions(modelHash, minimum, maximum) end

-- [+] 0x711327CD09C8F162
function GetNextWeatherTypeHashName() end

-- [+] 0xEB4A0C2D56441717
function GetNumDispatchedUnitsForPlayer(dispatchService) end

-- [+] 0x996DD1E1E02F1008
function GetNumSuccessfulStuntJumps() end

-- [+] 0xFEAD16FC8F9DFC0F
function GetNumberOfFreeStacksOfThisSize(stackSize) end

-- [+] 0x4060057271CEBC89
function GetNumberOfStreamingRequests() end

-- [+] 0x20F898A5D9782800
function GetPlayerShortSwitchState() end

-- [+] 0x5B48A06DD0E792A5
function GetPlayerSwitchInterpOutCurrentTime() end

-- [+] 0x08C2D6C52A3104BB
function GetPlayerSwitchInterpOutDuration() end

-- [+] 0x78C0D93253149435
function GetPlayerSwitchJumpCutIndex() end

-- [+] 0x470555300D10B2A5
function GetPlayerSwitchState() end

-- [+] 0xB3C94A90D9FC9E62
function GetPlayerSwitchType() end

-- [+] 0xABB2FA71C83A1B72
function GetPowerSavingModeDuration() end

-- [+] 0x564B884A05EC45A3
function GetPrevWeatherTypeHashName() end

-- [+] 0xC488FF2356EA7791
function GetProfileSetting(profileSetting) end

-- [+] 0x82FDE6A57EE4EE44
function GetProjectileNearPed(ped, weaponHash, distance, outCoords, outProjectile, ownedByPlayer) end

-- [+] 0x96695E368AD855F3
function GetRainLevel() end

-- [+] 0xD2D57F1D764117B1
function GetRandomEventFlag(Any) end

-- [+] 0x313CE5879CEB6FCD
function GetRandomFloatInRange(startRange, endRange) end

-- [+] 0xD53343AA4FB7DD28
function GetRandomIntInRange(startRange, endRange) end

-- [+] 0x5234F9F10919EABA
function GetRenderingCam() end

-- [+] 0x8098C8D6597AAE18
function GetReplayStatAtIndex(index) end

-- [+] 0xDC9274A7EF6B2867
function GetReplayStatCount() end

-- [+] 0x2B626A0150E4D449
function GetReplayStatMissionType() end

-- [+] 0x35FB78DC42B7BD21
function GetRequestingnightvision() end

-- [+] 0xBAF107B6BB2C97F0
function GetSafeZoneSize() end

-- [+] 0xD80A80346A45D761
function GetScaleformMovieMethodReturnValueBool(methodReturn) end

-- [+] 0x2DE7EFA66B906036
function GetScaleformMovieMethodReturnValueInt(method_return) end

-- [+] 0x34E82F05DF2974F5
function GetScreenCoordFromWorldCoord(worldX, worldY, worldZ, screenX, screenY) end

-- [+] 0x888D57E407E63624
function GetScreenResolution(x, y) end

-- [+] 0x5CCABFFCA31DDE33
function GetScreenblurFadeCurrentTime() end

-- [+] 0x6DD8F5AA635EB4B2
function GetScriptGfxPosition(x, y, calculatedX, calculatedY) end

-- [+] 0xA09F896CE912481F
function GetSizeOfSaveData(p0) end

-- [+] 0xC5868A966E5BE3AE
function GetSnowLevel(Any) end

-- [+] 0x1670F8D05056F257
function GetStatusOfLoadMissionCreatorPhoto(p0) end

-- [+] 0x2B5E102E4A42F2BF
function GetStatusOfMissionRepeatSave() end

-- [+] 0x0C0C4E81E1AC60A0
function GetStatusOfSaveHighQualityPhoto() end

-- [+] 0xF5BED327CEA362B1
function GetStatusOfSortedListOperation(scanForSaving) end

-- [+] 0x0D6CA79EEEBD8CA3
function GetStatusOfTakeHighQualityPhoto() end

-- [+] 0x90A78ECAA4E78453
function GetStatusOfTakeMissionCreatorPhoto() end

-- [+] 0x17DF68D720AA77F8
function GetTennisSwingAnimComplete(ped) end

-- [+] 0x35736EE65BD00C11
function GetTextureResolution(textureDict, textureName) end

-- [+] 0xD7D22F5592AED8BA
function GetTimeSinceLastInput(padIndex) end

-- [+] 0xFDF3D97C674AFB66
function GetTimecycleModifierIndex() end

-- [+] 0x459FD2C8D0AB78BC
function GetTimecycleTransitionModifierIndex() end

-- [+] 0xEB3DAC2C86001E5E
function GetTogglePausedRenderphasesStatus() end

-- [+] 0x6856EC3D35C81EA4
function GetTotalSuccessfulStuntJumps() end

-- [+] 0xFC1E275A90D39995
function GetTvChannel() end

-- [+] 0x2170813D3DD8661B
function GetTvVolume() end

-- [+] 0x3D3D8B3BE5A83D35
function GetUsedCreatorModelMemoryPercentage() end

-- [+] 0x2202A3F42C8E5F79
function GetUsingnightvision() end

-- [+] 0x44B80ABAB9D80BD3
function GetUsingseethrough() end

-- [+] 0xFE26117A5841B2FF
function GetVehicleCrewEmblemRequestState(vehicle, p1) end

-- [+] 0xF3BBE884A14BB413
function GetWeatherTypeTransition(weatherType1, weatherType2, percentWeather2) end

-- [+] 0x1F400FEF721170DA
function GetWindDirection() end

-- [+] 0xA8CF1CC0AFCD3F12
function GetWindSpeed() end

-- [+] 0xA4819F5E23E2FFAD
function GolfTrailGetMaxHeight() end

-- [+] 0xA4664972A9B8F8BA
function GolfTrailGetVisualControlPoint(p0) end

-- [+] 0x12995F2E53FFA601
function GolfTrailSetColour(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11) end

-- [+] 0xA51C4B86B71652AE
function GolfTrailSetEnabled(toggle) end

-- [+] 0x06F761EA47C1D3ED
function GolfTrailSetFacing(p0) end

-- [+] 0xB1BB03742917A5D6
function GolfTrailSetFixedControlPoint(type, xPos, yPos, zPos, p4, red, green, blue, alpha) end

-- [+] 0x312342E1A4874F3F
function GolfTrailSetPath(p0, p1, p2, p3, p4, p5, p6, p7, p8) end

-- [+] 0x2485D34E50A22E84
function GolfTrailSetRadius(p0, p1, p2) end

-- [+] 0x9CFDD90B2B844BF7
function GolfTrailSetShaderParams(p0, p1, p2, p3, p4) end

-- [+] 0xDBAA5EC848BA2D46
function GolfTrailSetTessellation(p0, p1) end

-- [+] 0x302C91AB2D477F7E
function GrassLodResetScriptAreas() end

-- [+] 0x6D955F6A9E0295B1
function GrassLodShrinkScriptAreas(x, y, z, radius, p4, p5, p6) end

-- [+] 0x202A5ED9CE01D6E7
function HardAttachCamToEntity(cam, entity, xRot, yRot, zRot, xOffset, yOffset, zOffset, isRelative) end

-- [+] 0x149916F50C34A40D
function HardAttachCamToPedBone(cam, ped, boneIndex, xRot, yRot, zRot, xOffset, yOffset, zOffset, isRelative) end

-- [+] 0xD031A9162D01088C
function HasAnimDictLoaded(animDict) end

-- [+] 0xC4EA073D86FB29B0
function HasAnimSetLoaded(animSet) end

-- [+] 0x14832BF2ABA53FC5
function HasAsyncInstallFinished() end

-- [+] 0x9870ACFB89A90995
function HasBulletImpactedInArea(x, y, z, p3, p4, p5) end

-- [+] 0xDC8C5D7CFEAB8394
function HasBulletImpactedInBox(p0, p1, p2, p3, p4, p5, p6, p7) end

-- [+] 0x071E2A839DE82D90
function HasButtonCombinationJustBeenEntered(hash, amount) end

-- [+] 0x557E43C447E700A8
function HasCheatStringJustBeenEntered(hash) end

-- [+] 0x318234F4F3738AF3
function HasClipSetLoaded(clipSet) end

-- [+] 0x22CCA434E368F03A
function HasCollisionForModelLoaded(model) end

-- [+] 0xA1C996C2A744262E
function HasCutFileLoaded(cutsceneName) end

-- [+] 0x708BDD8CD795B043
function HasCutsceneCutThisFrame() end

-- [+] 0x7C0A893088881D57
function HasCutsceneFinished() end

-- [+] 0xC59F528E9AB9F339
function HasCutsceneLoaded() end

-- [+] 0x98A4EB5D89A0C952
function HasModelLoaded(model) end

-- [+] 0x8702416E512EC454
function HasNamedPtfxAssetLoaded(fxName) end

-- [+] 0xCA7D9B86ECA7481B
function HasPtfxAssetLoaded() end

-- [+] 0xE8B9C0EC9E183F35
function HasResumedFromSuspend() end

-- [+] 0x8217150E1217EBFD
function HasScaleformContainerMovieLoadedIntoParent(scaleformHandle) end

-- [+] 0x0C1C5D756FB5F337
function HasScaleformMovieFilenameLoaded(scaleformName) end

-- [+] 0x85F01B8D5B90570E
function HasScaleformMovieLoaded(scaleformHandle) end

-- [+] 0x9743BCCF7CD6E1F6
function HasScaleformMovieNamedLoaded(scaleformHandle, scaleformName) end

-- [+] 0xDF6E5987D2B4D140
function HasScaleformScriptHudMovieLoaded(hudComponent) end

-- [+] 0x0145F696AAAAD2E4
function HasStreamedTextureDictLoaded(textureDict) end

-- [+] 0x228D3D94F8A11C3C
function HasThisCutsceneLoaded(cutsceneName) end

-- [+] 0x075F1D57402C93BA
function HaveCreditsReachedEnd() end

-- [+] 0x7B8A361C1813FBEF
function IgnoreMenuPreferenceForBonnetCameraThisUpdate() end

-- [+] 0x21FFB63D8C615361
function IgnoreNextRestart(toggle) end

-- [+] 0xB5A4DB34FE89B88A
function InitCreatorBudget() end

-- [+] 0xDDA77EE33C005AAF
function InterpolateCamWithParams(camera, camPosX, camPosY, camPosZ, camRotX, camRotY, camRotZ, fov, duration, posCurveType, rotCurveType, rotOrder, fovCurveType) end

-- [+] 0xF4F2C0D4EE209E20
function InvalidateIdleCam() end

-- [+] 0x9E4CFFF989258472
function InvalidateVehicleIdleCam() end

-- [+] 0x68EDDA28A5976D07
function IsAimCamActive() end

-- [+] 0x74BD83EA840F6BC9
function IsAimCamThirdPersonActive() end

-- [+] 0xEAF0FA793D05C592
function IsAllowedIndependentCameraModes(Any) end

-- [+] 0xA61B4DF533DCB56E
function IsAreaOccupied(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12) end

-- [+] 0x9F1935CA1F724008
function IsAussieVersion() end

-- [+] 0x69240733738C19A0
function IsAutoSaveInProgress() end

-- [+] 0xA921AA820C25702F
function IsBitSet(address, offset) end

-- [+] 0xD7360051C885628B
function IsBonnetCinematicCamRendering() end

-- [+] 0x1A8B5F3C01E2B477
function IsBulletInAngledArea(x1, y1, z1, x2, y2, z2, width, ownedByPlayer) end

-- [+] 0x3F2023999AD51C1F
function IsBulletInArea(x, y, z, radius, ownedByPlayer) end

-- [+] 0xDE0F6D7450D37351
function IsBulletInBox(x1, y1, z1, x2, y2, z2, ownedByPlayer) end

-- [+] 0xDFB2B516207D3534
function IsCamActive(cam) end

-- [+] 0x036F97C908C2B52C
function IsCamInterpolating(cam) end

-- [+] 0xC90621D8A0CEECF2
function IsCamPlayingAnim(cam, animName, animDictionary) end

-- [+] 0x02EC0AF5C5A49B7A
function IsCamRendering(cam) end

-- [+] 0x6B24BFE83A2BE47B
function IsCamShaking(cam) end

-- [+] 0x0290F35C0AD97864
function IsCamSplinePaused(p0) end

-- [+] 0xF5F1E89A970B7796
function IsCinematicCamInputActive() end

-- [+] 0xB15162CB5826E9E8
function IsCinematicCamRendering() end

-- [+] 0xBBC08F6B4CB8FF0A
function IsCinematicCamShaking() end

-- [+] 0xCA9D2AA3E326D720
function IsCinematicIdleCamRendering() end

-- [+] 0xCC9F3371A7C28BC9
function IsCinematicShotActive(p0) end

-- [+] 0xA049A5BE0F04F2F8
function IsCommandLineBenchmarkValueSet() end

-- [+] 0x1CEA6BFDF248E5D9
function IsControlEnabled(padIndex, control) end

-- [+] 0x580417101DDB492F
function IsControlJustPressed(padIndex, control) end

-- [+] 0x50F940259D3841E6
function IsControlJustReleased(padIndex, control) end

-- [+] 0xF3A21BCD95725A4A
function IsControlPressed(padIndex, control) end

-- [+] 0x648EE3E7F38877DD
function IsControlReleased(padIndex, control) end

-- [+] 0x991251AFC3981F84
function IsCutsceneActive() end

-- [+] 0x71B74D2AE19338D0
function IsCutscenePlaybackFlagSet(flag) end

-- [+] 0xD3C2E180A40F031E
function IsCutscenePlaying() end

-- [+] 0xC694D74949CAFD0C
function IsDecalAlive(decal) end

-- [+] 0x91AEF906BCA88877
function IsDisabledControlJustPressed(padIndex, control) end

-- [+] 0x305C8DCD79DA8B0F
function IsDisabledControlJustReleased(padIndex, control) end

-- [+] 0xE2587F8CBBD87B1D
function IsDisabledControlPressed(padIndex, control) end

-- [+] 0xFB6C4072E9A32E92
function IsDisabledControlReleased(padIndex, control) end

-- [+] 0x4D982ADB1978442D
function IsDurangoVersion() end

-- [+] 0x2DDFF3FB9075D747
function IsEntityFocus(entity) end

-- [+] 0x5E346D934122613F
function IsFirstPersonAimCamActive() end

-- [+] 0xC6D3D26810C8E0F9
function IsFollowPedCamActive() end

-- [+] 0xCBBDE6D335D6D496
function IsFollowVehicleCamActive() end

-- [+] 0x7EA2B6AF97ECA6ED
function IsFrontendFading() end

-- [+] 0x70FDA869F3317EA9
function IsGameplayCamLookingBehind() end

-- [+] 0x39B5D1B10383F0C8
function IsGameplayCamRendering() end

-- [+] 0x016C090630DF1F89
function IsGameplayCamShaking() end

-- [+] 0xE520FF1AD2785B40
function IsGameplayHintActive() end

-- [+] 0x684A41975F077262
function IsInPowerSavingMode() end

-- [+] 0x4F32C0D5A90A9B40
function IsInVehicleCamDisabled() end

-- [+] 0xC8BC6461E629BEAA
function IsIncidentValid(incidentId) end

-- [+] 0x88A741E44A2B3495
function IsIplActive(iplName) end

-- [+] 0xB8C0BB75D8A77DB3
function IsJapaneseVersion() end

-- [+] 0x77B612531280010D
function IsLookInverted() end

-- [+] 0x8A75CE2956274ADD
function IsMemoryCardInUse() end

-- [+] 0x2B4A15E44DE0F478
function IsMinigameInProgress() end

-- [+] 0x75816577FEA6DAD5
function IsModelAPed(model) end

-- [+] 0x19AAC8F07BFEC53E
function IsModelAVehicle(model) end

-- [+] 0x35B9E0803292B641
function IsModelInCdimage(model) end

-- [+] 0xC0296A2EDF545E92
function IsModelValid(model) end

-- [+] 0x41CA5A33160EA4AB
function IsNetworkLoadingScene() end

-- [+] 0xA41A05B6CB741B85
function IsNewLoadSceneActive() end

-- [+] 0x01B8247A7A8B9AD1
function IsNewLoadSceneLoaded() end

-- [+] 0x2FAA3A30BEC0F25D
function IsNextWeatherType(weatherType) end

-- [+] 0xA72BC0B675B1519E
function IsOrbisVersion() end

-- [+] 0x48AF36444B965238
function IsPcVersion() end

-- [+] 0xD9D2CFFF49FAB35F
function IsPlayerSwitchInProgress() end

-- [+] 0x1F710BFF7DAE6261
function IsPlaylistUnk(tvChannel, p1) end

-- [+] 0xE54E209C35FFA18D
function IsPointObscuredByAMissionEntity(p0, p1, p2, p3, p4, p5, p6) end

-- [+] 0x1312F4B242609CE3
function IsPopMultiplierAreaUnk(id) end

-- [+] 0xADCDE75E1C60F32D
function IsPositionOccupied(x, y, z, range, p4, checkVehicles, checkPeds, p7, p8, ignoreEntity, p10) end

-- [+] 0x44F28F86433B10A9
function IsPrevWeatherType(weatherType) end

-- [+] 0x5270A8FBC098C3F8
function IsProjectileInArea(x1, y1, z1, x2, y2, z2, ownedByPlayer) end

-- [+] 0xF0BC12401061DEA0
function IsProjectileTypeInAngledArea(x1, y1, z1, x2, y2, z2, width, p7, Any) end

-- [+] 0x2E0DC353342C4A6D
function IsProjectileTypeInArea(x1, y1, z1, x2, y2, z2, type, ownedByPlayer) end

-- [+] 0x34318593248C8FB2
function IsProjectileTypeWithinDistance(x, y, z, projHash, radius, ownedByPlayer) end

-- [+] 0xCCA1072C29D096C2
function IsPs3Version() end

-- [+] 0x86255B1FC929E33E
function IsScaleformMovieDeleting(Any) end

-- [+] 0x768FF8961BA904D6
function IsScaleformMovieMethodReturnValueReady(method_return) end

-- [+] 0x5A859503B0C08678
function IsScreenFadedIn() end

-- [+] 0xB16FCE9DDC7BA182
function IsScreenFadedOut() end

-- [+] 0x5C544BC6C57AC575
function IsScreenFadingIn() end

-- [+] 0x797AC7CB535BA28F
function IsScreenFadingOut() end

-- [+] 0x7B226C785A52A0A9
function IsScreenblurFadeRunning() end

-- [+] 0xC912AF078AF19212
function IsScriptGlobalShaking() end

-- [+] 0xFEFCF11B01287125
function IsSniperBulletInArea(x1, y1, z1, x2, y2, z2) end

-- [+] 0x61A23B7EDA9BDA24
function IsSniperInverted() end

-- [+] 0xE33D59DA70B58FDF
function IsSphereVisible(x, y, z, radius) end

-- [+] 0xD0263801A4C5B0BB
function IsSrlLoaded() end

-- [+] 0x0A27B2B6282F7169
function IsSteamVersion() end

-- [+] 0xBC9823AB80A3DCAC
function IsStreamvolActive() end

-- [+] 0xF22B6C47C6EAB066
function IsStringNull(string) end

-- [+] 0xCA042B6957743895
function IsStringNullOrEmpty(string) end

-- [+] 0x7A3F19700A4D0525
function IsStuntJumpInProgress() end

-- [+] 0x2272B0A1343129F4
function IsStuntJumpMessageShowing() end

-- [+] 0xDFA80CB25D0A19B3
function IsSwitchReadyForDescent() end

-- [+] 0x5B74EA8CFD5E3E7E
function IsSwitchSkippingDescent(Any) end

-- [+] 0x5D5479D115290C3F
function IsTennisMode(ped) end

-- [+] 0x7B30F65D7B710098
function IsThisAMinigameScript() end

-- [+] 0xC45CCDAAC9221CA8
function IsTrackedPointVisible(point) end

-- [+] 0x0AD973CA1E077B60
function IsTvPlaylistItemPlaying(videoCliphash) end

-- [+] 0xA571D46727E2B718
function IsUsingKeyboard(padIndex) end

-- [+] 0xF6201B4DAF662A9D
function IsXbox360Version() end

-- [+] 0x3BBBD13E5041A79E
function LandingMenuIsActive() end

-- [+] 0xBD6E84632DD4CB3F
function LoadAllObjectsNow() end

-- [+] 0xFC4842A34657BFCB
function LoadCloudHat(name, transitionTime) end

-- [+] 0x7E3F55ED251B76D3
function LoadGlobalWaterType(waterType) end

-- [+] 0x4862437A486F91B0
function LoadMissionCreatorPhoto(p0, p1, p2, p3) end

-- [+] 0xB66064452270E8F1
function LoadMovieMeshSet(movieMeshSetName) end

-- [+] 0x4448EB75B4904BDB
function LoadScene(x, y, z) end

-- [+] 0xEF7D17BC6C85264C
function LoadingscreenGetLoadFreemode() end

-- [+] 0x8AA464D4E0F6ACCD
function LoadingscreenGetLoadFreemodeWithEventName() end

-- [+] 0xC6DC823253FBB366
function LoadingscreenIsLoadingFreemode() end

-- [+] 0xC7E7181C09F33B69
function LoadingscreenSetIsLoadingFreemode(toggle) end

-- [+] 0xB0C56BD3D808D863
function LoadingscreenSetLoadFreemode(toggle) end

-- [+] 0xFC309E94546FCDB5
function LoadingscreenSetLoadFreemodeWithEventName(toggle) end

-- [+] 0x84C8D7C2D30D3280
function MoveVehicleDecals(p0, p1) end

-- [+] 0x9243BAC96D64C050
function NetworkSetScriptIsSafeForNetworkGame() end

-- [+] 0x64E630FAF5F60F44
function NetworkStopLoadScene() end

-- [+] 0xC4582015556D1C46
function NetworkUpdateLoadScene() end

-- [+] 0x212A8D0D2BABFAC2
function NewLoadSceneStart(posX, posY, posZ, offsetX, offsetY, offsetZ, radius, p7) end

-- [+] 0xACCFB4ACF53551B0
function NewLoadSceneStartSphere(x, y, z, radius, p4) end

-- [+] 0xC197616D221FF4A4
function NewLoadSceneStop() end

-- [+] 0x3ED1438C1F5C6612
function NextOnscreenKeyboardResultWillDisplayUsingTheseFonts(fontBitField) end

-- [+] 0x7DCF7C708D292D55
function OverrideCamSplineMotionBlur(cam, p1, p2, p3) end

-- [+] 0x40B62FA033EB0346
function OverrideCamSplineVelocity(cam, p1, p2, p3) end

-- [+] 0xEFB55E7C25D3B3BE
function OverrideInteriorSmokeEnd() end

-- [+] 0x1600FD8CF72EBC12
function OverrideInteriorSmokeLevel(level) end

-- [+] 0x2A2A52824DB96700
function OverrideInteriorSmokeName(name) end

-- [+] 0xA76359FC80B2438E
function OverrideLodscaleThisFrame(scaling) end

-- [+] 0x95EB5E34F821BABE
function OverridePedBadgeTexture(ped, txd, txn) end

-- [+] 0x1162EA8AE9D24EEA
function OverrideSaveHouse(p0, p1, p2, p3, p4, p5, p6, p7) end

-- [+] 0xD1C7CB175E012964
function PassKeyboardInputToScaleform(scaleformHandle) end

-- [+] 0x8A35C742130C6080
function PatchDecalDiffuseMap(decalType, textureDict, textureName) end

-- [+] 0x2C2B3493FBF51C71
function PauseDeathArrestRestart(toggle) end

-- [+] 0x70D2CC8A542A973C
function PlayBinkMovie(binkMovie) end

-- [+] 0x9A2D0FB2E7852392
function PlayCamAnim(cam, animName, animDictionary, x, y, z, xRot, yRot, zRot, p9, p10) end

-- [+] 0xE32EFE9AB4A9AA0C
function PlaySynchronizedCamAnim(camera, scene, animName, animDictionary) end

-- [+] 0x8FA9C42FC5D7C64B
function PlayTennisDiveAnim(ped, p1, p2, p3, p4, p5) end

-- [+] 0xE266ED23311F24D4
function PlayTennisSwingAnim(ped, animDict, animName, p3, p4, p5) end

-- [+] 0xF75497BB865F0803
function PointCamAtCoord(cam, x, y, z) end

-- [+] 0x5640BFF86B16E8DC
function PointCamAtEntity(cam, entity, offsetX, offsetY, offsetZ, p5) end

-- [+] 0x68B2B5F33BA63C41
function PointCamAtPedBone(cam, ped, boneIndex, x, y, z, p6) end

-- [+] 0x3C8938D7D872211E
function PopTimecycleModifier() end

-- [+] 0x7472BB270D7B4F3E
function PopulateNow() end

-- [+] 0x3D245789CE12982C
function PrefetchSrl(srl) end

-- [+] 0x11B56FBBF7224868
function PreloadCloudHat(name) end

-- [+] 0xD7021272EB0A451E
function PresetInteriorAmbientCache(timecycleModifierName) end

-- [+] 0x58F735290861E6B4
function PushTimecycleModifier() end

-- [+] 0x9B6E70C5CEEF4EEB
function QueryMovieMeshSetState(p0) end

-- [+] 0x72DE52178C291CB5
function QueueMissionRepeatLoad(Any) end

-- [+] 0x44A0BDC559B35F6E
function QueueMissionRepeatSave() end

-- [+] 0x2A893980E96B659A
function QueueOperationToCreateSortedListOfPhotos(scanForSaving) end

-- [+] 0xEB6891F03362FB12
function QuitGame() end

-- [+] 0xC8F4131414C835A1
function RegisterBoolToSave(p0, name) end

-- [+] 0xE40C1C56DF95C2E8
function RegisterEntityForCutscene(cutsceneEntity, cutsceneEntName, p2, modelHash, p4) end

-- [+] 0x10C2FA78D0E128A1
function RegisterEnumToSave(p0, name) end

-- [+] 0x7CAEC29ECB5DFEBB
function RegisterFloatToSave(p0, name) end

-- [+] 0xA735353C77334EA0
function RegisterInt64ToSave(p0, name) end

-- [+] 0x34C9EE5986258415
function RegisterIntToSave(p0, name) end

-- [+] 0xA44FF770DFBC5DAE
function RegisterNoirScreenEffectThisFrame() end

-- [+] 0xC0714D0A7EEECA54
function RegisterSaveHouse(p0, p1, p2, p3, p4, p5, p6) end

-- [+] 0x2131046957F31B04
function RegisterSynchronisedScriptSpeech() end

-- [+] 0xEDB1232C5BEAE62F
function RegisterTextLabelToSave(p0, name) end

-- [+] 0x04D950EEFA4EED8C
function ReleaseBinkMovie(binkMovie) end

-- [+] 0xEB119AA014E89183
function ReleaseMovieMeshSet(movieMeshSet) end

-- [+] 0xF66A602F829E2A06
function RemoveAnimDict(animDict) end

-- [+] 0x16350528F93024B3
function RemoveAnimSet(animSet) end

-- [+] 0x01F73A131C18CD94
function RemoveClipSet(clipSet) end

-- [+] 0xD00D76A7DFC9D852
function RemoveCutFile(cutsceneName) end

-- [+] 0x440AF51A3462B86F
function RemoveCutscene() end

-- [+] 0xED3F346429CCD659
function RemoveDecal(decal) end

-- [+] 0xCCF71CBDDF5B6CB9
function RemoveDecalsFromObject(obj) end

-- [+] 0xA6F6F70FDC6D144C
function RemoveDecalsFromObjectFacing(obj, x, y, z) end

-- [+] 0xE91F1B65F2B48D57
function RemoveDecalsFromVehicle(vehicle) end

-- [+] 0x5D6B2D4830A67C62
function RemoveDecalsInRange(x, y, z, range) end

-- [+] 0x264AC28B01B353A5
function RemoveDispatchSpawnBlockingArea(p0) end

-- [+] 0xEE6C5AD3ECE0A82D
function RemoveIpl(iplName) end

-- [+] 0xF086AD9354FAC3A3
function RemoveModelFromCreatorBudget(Any) end

-- [+] 0x5F61EBBE1A00F96D
function RemoveNamedPtfxAsset(fxName) end

-- [+] 0xC401503DFE8D53CF
function RemoveParticleFx(ptfxHandle, p1) end

-- [+] 0xB8FEAEEBCC127425
function RemoveParticleFxFromEntity(entity) end

-- [+] 0xDD19FA1C6D657305
function RemoveParticleFxInRange(X, Y, Z, radius) end

-- [+] 0xB129E447A2EDA4BF
function RemovePopMultiplierArea(id, p1) end

-- [+] 0xE6869BECDD8F2403
function RemovePopMultiplierSphere(id, p1) end

-- [+] 0x88C6814073DD4A73
function RemovePtfxAsset() end

-- [+] 0xF44A5456AC3F4F97
function RemoveScaleformScriptHudMovie(hudComponent) end

-- [+] 0xA6A12939F16D85BE
function RemoveStealthKill(hash, p1) end

-- [+] 0x15E33297C3E8DC60
function RemoveTcmodifierOverride(p0) end

-- [+] 0xD2300034310557E4
function RemoveVehicleCrewEmblem(vehicle, p1) end

-- [+] 0x07E5B515DB0636FC
function RenderScriptCams(render, ease, easeTime, easeCoordsAnim, p4) end

-- [+] 0x8BFCEB5EA1B161B6
function ReplayFreeCamGetMaxRange() end

-- [+] 0xC9156DC11411A9EA
function RequestAdditionalCollisionAtCoord(x, y, z) end

-- [+] 0xD3BD40951412FEF6
function RequestAnimDict(animDict) end

-- [+] 0x6EA47DAE7FAD0EED
function RequestAnimSet(animSet) end

-- [+] 0xD2A71E1A77418A49
function RequestClipSet(clipSet) end

-- [+] 0x07503F7948F491A7
function RequestCollisionAtCoord(Any) end

-- [+] 0x923CB32A3B874FCB
function RequestCollisionForModel(model) end

-- [+] 0x06A3524161C502BA
function RequestCutFile(cutsceneName) end

-- [+] 0x7A86743F475D9E09
function RequestCutscene(cutsceneName, flags) end

-- [+] 0xC23DE0E91C30B58C
function RequestCutsceneWithPlaybackList(cutsceneName, playbackFlags, flags) end

-- [+] 0x41B4893843BBDB74
function RequestIpl(iplName) end

-- [+] 0xA0261AEF7ACFC51E
function RequestMenuPedModel(model) end

-- [+] 0x963D27A58DF860AC
function RequestModel(model) end

-- [+] 0x8A7A40100EDFEC58
function RequestModelsInRoom(interior, roomName) end

-- [+] 0xB80D8756B4668AB6
function RequestNamedPtfxAsset(fxName) end

-- [+] 0x944955FB2A3935C8
function RequestPtfxAsset(Any) end

-- [+] 0x11FE353CF9733E6F
function RequestScaleformMovie(scaleformName) end

-- [+] 0xC514489CFB8AF806
function RequestScaleformMovieInstance(scaleformName) end

-- [+] 0xBD06C611BB9048C2
function RequestScaleformMovieSkipRenderWhilePaused(scaleformName) end

-- [+] 0x65E7E78842E74CDB
function RequestScaleformMovieWithIgnoreSuperWidescreen(scaleformName) end

-- [+] 0x9304881D6F6537EA
function RequestScaleformScriptHudMovie(hudComponent) end

-- [+] 0xDFA2EF8E04127DD5
function RequestStreamedTextureDict(textureDict, p1) end

-- [+] 0xE3E2C1B4C59DBC77
function ResetAdaptation(numFrames) end

-- [+] 0x437138B6A830166A
function ResetBenchmarkRecording() end

-- [+] 0x77A84429DD9F0A15
function ResetDispatchIdealSpawnDistance() end

-- [+] 0xAC7BFD5C1D83EA75
function ResetDispatchSpawnBlockingAreas() end

-- [+] 0x5896F2BD5683A4E1
function ResetDispatchSpawnLocation() end

-- [+] 0xEB2DB0CAD13154B3
function ResetDispatchTimeBetweenSpawnAttempts(p0) end

-- [+] 0x643ED62D5EA3BEBD
function ResetInputMappingScheme() end

-- [+] 0x89C8553DD3274AAE
function ResetParticleFxOverride(name) end

-- [+] 0xE1C8709406F2C41C
function ResetPausedRenderphases() end

-- [+] 0xE3A3DB414A373DAB
function ResetScriptGfxAlign() end

-- [+] 0xE574A662ACAEFBB1
function RestartGame() end

-- [+] 0x40AFB081F8ADD4EE
function ReturnTwo(p0) end

-- [+] 0x37DEB0AA183FB6D8
function SaveBenchmarkRecording() end

-- [+] 0x3DEC726C25A11BAC
function SaveHighQualityPhoto(unused) end

-- [+] 0xC58424BA936EB458
function ScaleformMovieMethodAddParamBool(value) end

-- [+] 0xD69736AAE04DB51A
function ScaleformMovieMethodAddParamFloat(value) end

-- [+] 0xC3D0841A0CC546A6
function ScaleformMovieMethodAddParamInt(value) end

-- [+] 0xEC52C631A1831C03
function ScaleformMovieMethodAddParamLatestBriefString(value) end

-- [+] 0x77FE3402004CD1B0
function ScaleformMovieMethodAddParamLiteralString(string) end

-- [+] 0xE83A3E3557A56640
function ScaleformMovieMethodAddParamPlayerNameString(string) end

-- [+] 0xBA7148484BD90365
function ScaleformMovieMethodAddParamTextureNameString(string) end

-- [+] 0x8EF5573A1F801A5C
function ScriptRaceGetPlayerSplitTime(player, p1, p2) end

-- [+] 0x0A60017F841A54F2
function ScriptRaceInit(numCheckpoints, numLaps, numPlayers, localPlayer) end

-- [+] 0x1BB299305C3E8C13
function ScriptRacePlayerHitCheckpoint(ped, checkpoint, lap, time) end

-- [+] 0x1FF6BF9A63E5757F
function ScriptRaceShutdown() end

-- [+] 0x43DBAE39626CE83F
function SeethroughGetMaxThickness() end

-- [+] 0x70A64C0234EF522C
function SeethroughReset() end

-- [+] 0x1086127B3A63505E
function SeethroughSetColorNear(red, green, blue) end

-- [+] 0x9D75795B9DC6EBBF
function SeethroughSetFadeEndDistance(distance) end

-- [+] 0xA78DE25577300BA1
function SeethroughSetFadeStartDistance(distance) end

-- [+] 0xD7D0B00177485411
function SeethroughSetHeatscale(index, heatScale) end

-- [+] 0x19E50EB6E33E1D28
function SeethroughSetHiLightIntensity(intensity) end

-- [+] 0x1636D7FC127B10D2
function SeethroughSetHiLightNoise(noise) end

-- [+] 0x0C8FAC83902A62DF
function SeethroughSetMaxThickness(thickness) end

-- [+] 0xFEBFBFDFB66039DE
function SeethroughSetNoiseAmountMax(amount) end

-- [+] 0xFF5992E1C9E65D05
function SeethroughSetNoiseAmountMin(amount) end

-- [+] 0x1268615ACE24D504
function SetArtificialLightsState(state) end

-- [+] 0xE2B187C0939B3D32
function SetArtificialLightsStateAffectsVehicles(toggle) end

-- [+] 0x23BA6B0C2AD7B0D3
function SetBackfaceculling(toggle) end

-- [+] 0x438822C279B73B93
function SetBeastModeActive(player) end

-- [+] 0x338D9F609FD632DB
function SetBinkMovie(name) end

-- [+] 0x0CB6B3446855B57A
function SetBinkMovieTime(binkMovie, progress) end

-- [+] 0xAFF33B1178172223
function SetBinkMovieVolume(binkMovie, value) end

-- [+] 0x6805D58CAA427B72
function SetBinkShouldSkip(binkMovie, shouldSkip) end

-- [+] 0x933D6A9EEC1BACD0
function SetBit(address, offset) end

-- [+] 0x8EF07E15701D61ED
function SetBitsInRange(var, rangeStart, rangeEnd, p3) end

-- [+] 0x026FB97D0A425F84
function SetCamActive(cam, active) end

-- [+] 0x9FBDA379383A52A4
function SetCamActiveWithInterp(camTo, camFrom, duration, easeLocation, easeRotation) end

-- [+] 0x8C1DC7770C51DC8D
function SetCamAffectsAiming(cam, toggle) end

-- [+] 0x4145A4C44FF3B5A6
function SetCamAnimCurrentPhase(cam, phase) end

-- [+] 0x661B5C8654ADD825
function SetCamControlsMiniMapHeading(cam, toggle) end

-- [+] 0x4D41783FB745E42E
function SetCamCoord(cam, posX, posY, posZ) end

-- [+] 0x1B93E0107865DD40
function SetCamDebugName(camera, name) end

-- [+] 0x7DD234D6F3914C5B
function SetCamDofFnumberOfLens(camera, p1) end

-- [+] 0x47B595D60664CFFA
function SetCamDofFocalLengthMultiplier(camera, multiplier) end

-- [+] 0xC669EEA5D031B7DE
function SetCamDofFocusDistanceBias(camera, p1) end

-- [+] 0xC3654A441402562D
function SetCamDofMaxNearInFocusDistance(camera, p1) end

-- [+] 0x2C654B4943BDDF7C
function SetCamDofMaxNearInFocusDistanceBlendLevel(camera, p1) end

-- [+] 0x3CF48F6F96E749DC
function SetCamDofPlanes(cam, p1, p2, p3, p4) end

-- [+] 0x5EE29B4D7D5DF897
function SetCamDofStrength(cam, dofStrength) end

-- [+] 0x80C8B1846639BB19
function SetCamEffect(p0) end

-- [+] 0xAE306F2A904BF86E
function SetCamFarClip(cam, farClip) end

-- [+] 0xEDD91296CD01AEE0
function SetCamFarDof(cam, farDOF) end

-- [+] 0xB13C14F66A00D047
function SetCamFov(cam, fieldOfView) end

-- [+] 0x45F1DE9C34B93AE6
function SetCamInheritRollVehicle(cam, p1) end

-- [+] 0x6F0F77FBA9A8F2E6
function SetCamMotionBlurStrength(cam, strength) end

-- [+] 0xC7848EFCCC545182
function SetCamNearClip(cam, nearClip) end

-- [+] 0x3FA4BF0A7AB7DE2C
function SetCamNearDof(cam, nearDOF) end

-- [+] 0xBFD8727AEA3CCEBA
function SetCamParams(cam, posX, posY, posZ, rotX, rotY, rotZ, fieldOfView, transitionSpeed, p9, p10, rotationOrder) end

-- [+] 0x85973643155D0B07
function SetCamRot(cam, rotX, rotY, rotZ, rotationOrder) end

-- [+] 0xD93DB43B82BC0D00
function SetCamShakeAmplitude(cam, amplitude) end

-- [+] 0x1381539FEE034CDA
function SetCamSplineDuration(cam, timeDuration) end

-- [+] 0x83B8201ED82A9A2D
function SetCamSplineNodeEase(cam, p1, p2, p3) end

-- [+] 0x7BF1A54AE67AC070
function SetCamSplineNodeExtraFlags(cam, p1, flags) end

-- [+] 0xA6385DEB180F319F
function SetCamSplineNodeVelocityScale(cam, p1, scale) end

-- [+] 0x242B5874F0A4E052
function SetCamSplinePhase(cam, p1) end

-- [+] 0xD1B0F412F109EA5D
function SetCamSplineSmoothingStyle(cam, smoothingStyle) end

-- [+] 0x16A96863A17552BB
function SetCamUseShallowDofMode(cam, toggle) end

-- [+] 0x2A2173E46DAECD12
function SetCamViewModeForContext(context, viewMode) end

-- [+] 0x2707AAE9D9297D89
function SetCheckpointCylinderHeight(checkpoint, nearHeight, farHeight, radius) end

-- [+] 0x4B5B4DA5D79F1943
function SetCheckpointIconHeight(checkpoint, height_multiplier) end

-- [+] 0x44621483FF966526
function SetCheckpointIconScale(checkpoint, scale) end

-- [+] 0x7167371E8AD747F7
function SetCheckpointRgba(checkpoint, red, green, blue, alpha) end

-- [+] 0xB9EA40907C680580
function SetCheckpointRgba2(checkpoint, red, green, blue, alpha) end

-- [+] 0x51669F7D1FB53D9F
function SetCinematicButtonActive(p0) end

-- [+] 0xC724C701C30B2FE7
function SetCinematicCamShakeAmplitude(p0) end

-- [+] 0xDCF0754AC3D6FD4E
function SetCinematicModeActive(toggle) end

-- [+] 0xDC9DA9E8789F5246
function SetCinematicNewsChannelActiveThisUpdate() end

-- [+] 0x02DEAAC8F8EA7FE7
function SetCloudSettingsOverride(overrideSettingsName) end

-- [+] 0xF36199225D6D8C86
function SetCloudsAlpha(opacity) end

-- [+] 0x8290252FFF36ACB5
function SetControlLightEffectColor(padIndex, red, green, blue) end

-- [+] 0xE8A25867FBA3B05E
function SetControlNormal(padIndex, control, amount) end

-- [+] 0xB938B7E6D3C0620C
function SetCreditsActive(toggle) end

-- [+] 0xBBF327DED94E4DEB
function SetCurrentPlayerTcmodifier(modifierName) end

-- [+] 0xFC695459D4D0E219
function SetCursorLocation(x, y) end

-- [+] 0x41FAA8FB2ECE8720
function SetCutsceneCanBeSkipped(p0) end

-- [+] 0x4C61C75BEE8184C2
function SetCutsceneEntityStreamingFlags(cutsceneEntName, p1, p2) end

-- [+] 0x8093F23ABACCC7D4
function SetCutsceneFadeValues(p0, p1, p2, p3) end

-- [+] 0xB812B3FD1C01CF27
function SetCutsceneOrigin(x, y, z, heading, p4) end

-- [+] 0x011883F41211432A
function SetCutsceneOriginAndOrientation(x1, y1, z1, x2, y2, z2, p6) end

-- [+] 0xBA01E7B6DEEFBBC9
function SetCutscenePedComponentVariation(cutsceneEntName, componentId, drawableId, textureId, modelHash) end

-- [+] 0x2A56C06EBEF2B0D9
function SetCutscenePedComponentVariationFromPed(cutsceneEntName, ped, modelHash) end

-- [+] 0x0546524ADE2E9723
function SetCutscenePedPropVariation(cutsceneEntName, componentId, drawableId, textureId, modelHash) end

-- [+] 0x9896CE4721BE84BA
function SetCutsceneTriggerArea(p0, p1, p2, p3, p4, p5) end

-- [+] 0x175B6BFC15CDD0C5
function SetDebugLinesAndSpheresDrawingActive(enabled) end

-- [+] 0x4B5CFC83122DF602
function SetDisableDecalRenderingThisFrame() end

-- [+] 0xD9454B5752C857DC
function SetDisablePetrolDecalsIgnitingThisFrame() end

-- [+] 0x6FE601A64180D423
function SetDispatchIdealSpawnDistance(p0) end

-- [+] 0xD10F442036302D50
function SetDispatchSpawnLocation(x, y, z) end

-- [+] 0x44F7CBC1BEB3327D
function SetDispatchTimeBetweenSpawnAttempts(p0, p1) end

-- [+] 0x48838ED9937A15D1
function SetDispatchTimeBetweenSpawnAttemptsMultiplier(p0, p1) end

-- [+] 0x42CBE54462D92634
function SetDitchPoliceModels(toggle) end

-- [+] 0xAA0008F3BBB8F416
function SetDrawOrigin(x, y, z, p3) end

-- [+] 0x1D5F595CCAE2E238
function SetEntityIconColor(entity, red, green, blue, alpha) end

-- [+] 0xE0E8BEECCA96BA31
function SetEntityIconVisibility(entity, toggle) end

-- [+] 0xA66C71C98D5F2CFB
function SetExplosiveAmmoThisFrame(player) end

-- [+] 0xFF1BED81BFDC0FE0
function SetExplosiveMeleeThisFrame(Any) end

-- [+] 0x5096FD9CCB49056D
function SetExtraTimecycleModifier(modifierName) end

-- [+] 0xDA66D2796BA33F12
function SetFadeInAfterDeathArrest(toggle) end

-- [+] 0xF3D78F59DFE18D79
function SetFadeInAfterLoad(toggle) end

-- [+] 0x1E0B4DC0D990A4E7
function SetFadeOutAfterArrest(toggle) end

-- [+] 0x4A18E01DF2C87B86
function SetFadeOutAfterDeath(toggle) end

-- [+] 0x1454F2448DE30163
function SetFakeWantedLevel(fakeWantedLevel) end

-- [+] 0x11879CDD803D30F4
function SetFireAmmoThisFrame(Any) end

-- [+] 0x0AF7B437918103B3
function SetFirstPersonAimCamNearClipThisUpdate(distance) end

-- [+] 0x70894BD0915C5BCA
function SetFirstPersonAimCamZoomFactor(zoomFactor) end

-- [+] 0xBCFC632DB7673BF0
function SetFirstPersonCamPitchRange(minAngle, maxAngle) end

-- [+] 0x0AB84296FED9CFC6
function SetFlash(p0, p1, fadeIn, duration, fadeOut) end

-- [+] 0xC91C6C55199308CA
function SetFlyCamCoordAndConstrain(cam, x, y, z) end

-- [+] 0x503F5920162365B2
function SetFlyCamHorizontalResponse(cam, p1, p2, p3) end

-- [+] 0xF9D02130ECDD1D77
function SetFlyCamMaxHeight(cam, height) end

-- [+] 0xE827B9382CFB41BA
function SetFlyCamVerticalSpeedMultiplier(cam, p1, p2, p3) end

-- [+] 0x198F77705FA0931D
function SetFocusEntity(entity) end

-- [+] 0xBB7454BAFF08FE25
function SetFocusPosAndVel(x, y, z, offsetX, offsetY, offsetZ) end

-- [+] 0x44A113DD6FFC48D1
function SetFollowPedCamThisUpdate(camName, easeTime) end

-- [+] 0x5A4F9EDF1673F704
function SetFollowPedCamViewMode(viewMode) end

-- [+] 0x5C90CAB09951A12F
function SetFollowTurretSeatCam(seatIndex) end

-- [+] 0xAC253D7842768F48
function SetFollowVehicleCamViewMode(viewMode) end

-- [+] 0x19464CB6E4078C8A
function SetFollowVehicleCamZoomLevel(zoomLevel) end

-- [+] 0xAEEDAD1420C65CC0
function SetForcePedFootstepsTracks(toggle) end

-- [+] 0xA1183BCFEE0F93D1
function SetForcePlayerToJump(player) end

-- [+] 0x4CC7F0FEA5283FE0
function SetForceVehicleTrails(toggle) end

-- [+] 0x577D1284D6873711
function SetGamePaused(toggle) end

-- [+] 0x717CD6E6FAEBBEDC
function SetGamePausesForStreaming(toggle) end

-- [+] 0x8BBACBF51DA047A8
function SetGameplayCamFollowPedThisUpdate(ped) end

-- [+] 0x425A920FDB9A0DDA
function SetGameplayCamHash(camName) end

-- [+] 0x759E13EBC1C15C5A
function SetGameplayCamRawPitch(pitch) end

-- [+] 0x103991D4A307D472
function SetGameplayCamRawYaw(yaw) end

-- [+] 0xB4EC2312F4E5B1F1
function SetGameplayCamRelativeHeading(heading) end

-- [+] 0x6D0858B8EDFD2B7D
function SetGameplayCamRelativePitch(angle, scalingFactor) end

-- [+] 0x48608C3464F58AB4
function SetGameplayCamRelativeRotation(roll, pitch, yaw) end

-- [+] 0xA87E00932DB4D85D
function SetGameplayCamShakeAmplitude(amplitude) end

-- [+] 0x21E253A7F8DA5DFB
function SetGameplayCamVehicleCamera(vehicleName) end

-- [+] 0x11FA5D3479C7DD47
function SetGameplayCamVehicleCameraName(Any) end

-- [+] 0xD51ADCD2D8BC0FB3
function SetGameplayCoordHint(x, y, z, duration, blendOutDuration, blendInDuration, unk) end

-- [+] 0x189E955A8313E298
function SetGameplayEntityHint(entity, xOffset, yOffset, zOffset, p4, p5, p6, p7, p8) end

-- [+] 0xE3433EADAAF7EE40
function SetGameplayHintAnimCloseup(toggle) end

-- [+] 0x5D7B620DAE436138
function SetGameplayHintAnimOffsetx(xOffset) end

-- [+] 0xC92717EF615B6704
function SetGameplayHintAnimOffsety(yOffset) end

-- [+] 0xD1F8363DFAD03848
function SetGameplayHintBaseOrbitPitchOffset(value) end

-- [+] 0xF8BDBF3D573049A1
function SetGameplayHintFollowDistanceScalar(value) end

-- [+] 0x513403FB9C56211F
function SetGameplayHintFov(FOV) end

-- [+] 0x83E87508A2CA2AC6
function SetGameplayObjectHint(p0, p1, p2, p3, p4, p5, p6, p7) end

-- [+] 0x2B486269ACD548D3
function SetGameplayPedHint(p0, x1, y1, z1, p4, duration, blendOutDuration, blendInDuration) end

-- [+] 0xA2297E18F3E71C2E
function SetGameplayVehicleHint(vehicle, offsetX, offsetY, offsetZ, p4, time, easeInTime, easeOutTime) end

-- [+] 0x740E14FAD5842351
function SetGravityLevel(level) end

-- [+] 0xB85F26619073E775
function SetHdArea(x, y, z, radius) end

-- [+] 0xBA3D65906822BED5
function SetHidofOverride(p0, p1, nearplaneOut, nearplaneIn, farplaneOut, farplaneIn) end

-- [+] 0xE9EA16D6E54CDCA4
function SetInVehicleCamStateThisUpdate(p0, p1) end

-- [+] 0xB08B85D860E7BA3C
function SetIncidentRequestedUnits(incidentId, dispatchService, numUnits) end

-- [+] 0xD261BA3E7E998072
function SetIncidentUnk(incidentId, p1) end

-- [+] 0xEDE476E5EE29EDB1
function SetInputExclusive(padIndex, control) end

-- [+] 0xC5F0A8EBD3F361CE
function SetInstancePriorityHint(flag) end

-- [+] 0x9BAE5AD2508DF078
function SetInstancePriorityMode() end

-- [+] 0xE37B76C387BE28ED
function SetInteriorActive(interiorID, toggle) end

-- [+] 0x9A9D1BA639675CF1
function SetIslandEnabled(islandName, toggle) end

-- [+] 0xAF12610C644A35C9
function SetMapdatacullboxEnabled(name, toggle) end

-- [+] 0x19E00D7322C6F85B
function SetMinigameInProgress(toggle) end

-- [+] 0xC4301E5121A0ED73
function SetMissionFlag(toggle) end

-- [+] 0xE532F5D78798DAAB
function SetModelAsNoLongerNeeded(model) end

-- [+] 0xBF59707B3E5ED531
function SetNextPlayerTcmodifier(modifierName) end

-- [+] 0x18F621F7A5B1F85D
function SetNightvision(toggle) end

-- [+] 0xE787BF1C5CF823C9
function SetNoiseoveride(toggle) end

-- [+] 0xCB6A7C3BB17A0C67
function SetNoisinessoveride(value) end

-- [+] 0xA43D5C6FE51ADBEF
function SetOverrideWeather(weatherType) end

-- [+] 0x48B3886C1358D0D5
function SetPadShake(padIndex, duration, frequency) end

-- [+] 0x27E32866E9A5C416
function SetParticleFxBulletImpactScale(scale) end

-- [+] 0xACEE6F360FC1F6B6
function SetParticleFxCamInsideNonplayerVehicle(vehicle, p1) end

-- [+] 0xEEC4047028426510
function SetParticleFxCamInsideVehicle(p0) end

-- [+] 0x726845132380142E
function SetParticleFxLoopedAlpha(ptfxHandle, alpha) end

-- [+] 0x7F8F65877F88783B
function SetParticleFxLoopedColour(ptfxHandle, r, g, b, bLocalOnly) end

-- [+] 0x5F0C4B5B1C393BE2
function SetParticleFxLoopedEvolution(ptfxHandle, propertyName, amount, noNetwork) end

-- [+] 0xDCB194B85EF7B541
function SetParticleFxLoopedFarClipDist(ptfxHandle, range) end

-- [+] 0xF7DDEBEC43483C43
function SetParticleFxLoopedOffsets(ptfxHandle, x, y, z, rotX, rotY, rotZ) end

-- [+] 0xB44250AAA456492D
function SetParticleFxLoopedScale(ptfxHandle, scale) end

-- [+] 0x77168D722C58B2FC
function SetParticleFxNonLoopedAlpha(alpha) end

-- [+] 0x26143A59EF48B262
function SetParticleFxNonLoopedColour(r, g, b) end

-- [+] 0x1E2E01C00837D26E
function SetParticleFxNonLoopedEmitterScale(p0, p1, scale) end

-- [+] 0xEA1E2D93F6F75ED9
function SetParticleFxOverride(oldAsset, newAsset) end

-- [+] 0x96EF97DAEB89BEF5
function SetParticleFxShootoutBoat(p0) end

-- [+] 0x8C95333CFC3340F3
function SetPedPopulationBudget(budgetLevel) end

-- [+] 0x4EBB7E87AA0DBED4
function SetPlayerIsInAnimalForm(toggle) end

-- [+] 0x9D8D44ADBBA61EF2
function SetPlayerRockstarEditorDisabled(toggle) end

-- [+] 0x5F2013F8BC24EE69
function SetPlayerShortSwitchStyle(style) end

-- [+] 0x0FDE9DBFC0A6BC65
function SetPlayerSwitchEstablishingShot(name) end

-- [+] 0xC208B673CE446B61
function SetPlayerSwitchOutro(cameraCoordX, cameraCoordY, cameraCoordZ, camRotationX, camRotationY, camRotationZ, camFov, camFarClip, rotationOrder) end

-- [+] 0xBDEB86F4D5809204
function SetPlayerTcmodifierTransition(value) end

-- [+] 0x798FDEB5B1575088
function SetPlayerpadShakesWhenControllerDisabled(toggle) end

-- [+] 0x643E26EA6E024D92
function SetRainLevel(level) end

-- [+] 0x971927086CFD2158
function SetRandomEventFlag(Any) end

-- [+] 0x444D98F98C11F3EC
function SetRandomSeed(seed) end

-- [+] 0x8B05F884CF7E8020
function SetRandomWeatherType() end

-- [+] 0x77B5F9A36BF96710
function SetReducePedModelBudget(toggle) end

-- [+] 0x80C527893080CCF3
function SetReduceVehicleModelBudget(toggle) end

-- [+] 0x40AEFD1A244741F2
function SetRenderHdOnly(toggle) end

-- [+] 0x706B5EDCAA7FA663
function SetRestartCustomPosition(x, y, z, heading) end

-- [+] 0x2587A48BC88DFADF
function SetRiotModeEnabled(toggle) end

-- [+] 0x4F548CABEAE553BC
function SetSaveHouse(p0, p1, p2) end

-- [+] 0xC9BF75D28165FF77
function SetSaveMenuActive(ignoreVehicle) end

-- [+] 0x1D132D614DD86811
function SetScaleformMovieAsNoLongerNeeded(scaleformHandle) end

-- [+] 0x32F34FF7F617643B
function SetScaleformMovieToUseLargeRt(scaleformMovieId, Any) end

-- [+] 0xE6A9F00D4240B519
function SetScaleformMovieToUseSuperLargeRt(scaleformHandle, toggle) end

-- [+] 0x6D8EB211944DCE08
function SetScaleformMovieToUseSystemTime(scaleform, toggle) end

-- [+] 0xB8A850F20A067EB6
function SetScriptGfxAlign(horizontalAlign, verticalAlign) end

-- [+] 0xF5A2C681787E579D
function SetScriptGfxAlignParams(x, y, w, h) end

-- [+] 0xC6372ECD45D73BCD
function SetScriptGfxDrawBehindPausemenu(flag) end

-- [+] 0x61BB1D9B3A95D802
function SetScriptGfxDrawOrder(order) end

-- [+] 0x7E08924259E08CE0
function SetSeethrough(toggle) end

-- [+] 0x7F06937B0CDCBC1A
function SetSnowLevel(level) end

-- [+] 0xA74A541C6884E7B8
function SetSrlTime(p0) end

-- [+] 0xBE2CACCF5A8AA805
function SetStreamedTextureDictAsNoLongerNeeded(textureDict) end

-- [+] 0x6E0C692677008888
function SetStreaming(toggle) end

-- [+] 0xD79185689F8FD5DF
function SetStuntJumpsCanTrigger(toggle) end

-- [+] 0x57FFF03E423A4C0B
function SetSuperJumpThisFrame() end

-- [+] 0x79C0E43EB9B944E2
function SetTableGamesCameraThisUpdate(hash) end

-- [+] 0x42156508606DE65E
function SetThirdPersonAimCamNearClipThisUpdate(distance) end

-- [+] 0xAA391C728106F7AF
function SetThisScriptCanBePaused(toggle) end

-- [+] 0xB98236CAAECEF897
function SetThisScriptCanRemoveBlipsCreatedByAnyScript(toggle) end

-- [+] 0x1D408577D440E81E
function SetTimeScale(timeScale) end

-- [+] 0x2C933ABF17A1DF41
function SetTimecycleModifier(modifierName) end

-- [+] 0x82E7FFCD5B2326B3
function SetTimecycleModifierStrength(strength) end

-- [+] 0x164ECBB3CF750CB0
function SetTrackedPointInfo(point, x, y, z, radius) end

-- [+] 0x3BCF567485E1971C
function SetTransitionTimecycleModifier(modifierName, transition) end

-- [+] 0x113D2C5DC57E1774
function SetTvAudioFrontend(toggle) end

-- [+] 0xBAABBB23EB6E484E
function SetTvChannel(channel) end

-- [+] 0xF7B38B8305F1FE8B
function SetTvChannelPlaylist(tvChannel, playlistName, restart) end

-- [+] 0x2201C576FACAEBE8
function SetTvChannelPlaylistAtHour(tvChannel, playlistName, hour) end

-- [+] 0x2982BF73F66E9DDC
function SetTvVolume(volume) end

-- [+] 0xA13B0222F3D94A94
function SetUseHiDof() end

-- [+] 0x731A880555DA3647
function SetUseHiDofInCutscene() end

-- [+] 0xCB9E1EB3BE2AF4E9
function SetVehiclePopulationBudget(p0) end

-- [+] 0x29B487C359E19889
function SetWeatherTypeNow(weatherType) end

-- [+] 0xED712CA327900C8A
function SetWeatherTypeNowPersist(weatherType) end

-- [+] 0xFB5045B7C42B75BF
function SetWeatherTypeOvertimePersist(weatherType, time) end

-- [+] 0x704983DF373B198F
function SetWeatherTypePersist(weatherType) end

-- [+] 0x578C752848ECFA0C
function SetWeatherTypeTransition(weatherType1, weatherType2, percentWeather2) end

-- [+] 0xDCD4EA924F42D01A
function SetWidescreenBorders(Any) end

-- [+] 0xAC3A74E8384A9919
function SetWind(speed) end

-- [+] 0xEB0F4468467B4528
function SetWindDirection(direction) end

-- [+] 0xEE09ECEDBABE47FC
function SetWindSpeed(speed) end

-- [+] 0x6A25241C340D3822
function ShakeCam(cam, shakeName, intensity) end

-- [+] 0xDCE214D9ED58F3CF
function ShakeCinematicCam(shakeName, intensity) end

-- [+] 0xFD55E49555E017CF
function ShakeGameplayCam(shakeName, intensity) end

-- [+] 0xF4C8CF9E353AFECA
function ShakeScriptGlobal(p0, p1) end

-- [+] 0x867654CBC7606F2C
function ShootSingleBulletBetweenCoords(x1, y1, z1, x2, y2, z2, damage, pureAccuracy, weaponHash, ownerPed, isAudible, isInvisible, speed) end

-- [+] 0xE3A7742E0B7A2F8B
function ShootSingleBulletBetweenCoordsIgnoreEntity(x1, y1, z1, x2, y2, z2, damage, p7, weaponHash, ownerPed, isAudible, isInvisible, speed, entity) end

-- [+] 0xBFE5756E7407064A
function ShootSingleBulletBetweenCoordsIgnoreEntityNew(x1, y1, z1, x2, y2, z2, damage, p7, weaponHash, ownerPed, isAudible, isInvisible, speed, entity, p14, p15, p16, p17) end

-- [+] 0xD3D15555431AB793
function ShouldUseMetricMeasurements() end

-- [+] 0xCCE26000E9A6FAD7
function ShutdownCreatorBudget() end

-- [+] 0xF2F6A2FA49278625
function SlerpNearQuaternion(t, x, y, z, w, x1, y1, z1, w1, outX, outY, outZ, outW) end

-- [+] 0x92790862E36C2ADA
function StartBenchmarkRecording() end

-- [+] 0x186D5CB5E7B0FF7B
function StartCutscene(flags) end

-- [+] 0x1C9ADDA3244A1FBF
function StartCutsceneAtCoords(x, y, z, flags) end

-- [+] 0x6F60E89A7B64EE1D
function StartNetworkedParticleFxLoopedOnEntity(effectName, entity, xOffset, yOffset, zOffset, xRot, yRot, zRot, scale, xAxis, yAxis, zAxis) end

-- [+] 0xDDE23F30CC5A0F03
function StartNetworkedParticleFxLoopedOnEntityBone(effectName, entity, xOffset, yOffset, zOffset, xRot, yRot, zRot, boneIndex, scale, xAxis, yAxis, zAxis) end

-- [+] 0xF56B8137DF10135D
function StartNetworkedParticleFxNonLoopedAtCoord(effectName, xPos, yPos, zPos, xRot, yRot, zRot, scale, xAxis, yAxis, zAxis) end

-- [+] 0xC95EB1DB6E92113D
function StartNetworkedParticleFxNonLoopedOnEntity(effectName, entity, offsetX, offsetY, offsetZ, rotX, rotY, rotZ, scale, axisX, axisY, axisZ) end

-- [+] 0x02B1F2A72E0F5325
function StartNetworkedParticleFxNonLoopedOnEntityBone(effectName, entity, offsetX, offsetY, offsetZ, rotX, rotY, rotZ, boneIndex, scale, axisX, axisY, axisZ) end

-- [+] 0xA41B6A43642AC2CF
function StartNetworkedParticleFxNonLoopedOnPedBone(effectName, ped, offsetX, offsetY, offsetZ, rotX, rotY, rotZ, boneIndex, scale, axisX, axisY, axisZ) end

-- [+] 0xE184F4F0DC5910E7
function StartParticleFxLoopedAtCoord(effectName, x, y, z, xRot, yRot, zRot, scale, xAxis, yAxis, zAxis, p11) end

-- [+] 0x1AE42C1660FD6517
function StartParticleFxLoopedOnEntity(effectName, entity, xOffset, yOffset, zOffset, xRot, yRot, zRot, scale, xAxis, yAxis, zAxis) end

-- [+] 0xC6EB449E33977F0B
function StartParticleFxLoopedOnEntityBone(effectName, entity, xOffset, yOffset, zOffset, xRot, yRot, zRot, boneIndex, scale, xAxis, yAxis, zAxis) end

-- [+] 0xF28DA9F38CD1787C
function StartParticleFxLoopedOnPedBone(effectName, ped, xOffset, yOffset, zOffset, xRot, yRot, zRot, boneIndex, scale, xAxis, yAxis, zAxis) end

-- [+] 0x25129531F77B9ED3
function StartParticleFxNonLoopedAtCoord(effectName, xPos, yPos, zPos, xRot, yRot, zRot, scale, xAxis, yAxis, zAxis) end

-- [+] 0x0D53A3B8DA0809D2
function StartParticleFxNonLoopedOnEntity(effectName, entity, offsetX, offsetY, offsetZ, rotX, rotY, rotZ, scale, axisX, axisY, axisZ) end

-- [+] 0x0E7E72961BA18619
function StartParticleFxNonLoopedOnPedBone(effectName, ped, offsetX, offsetY, offsetZ, rotX, rotY, rotZ, boneIndex, scale, axisX, axisY, axisZ) end

-- [+] 0x99AC7F0D8B9C893D
function StartPetrolTrailDecals(p0) end

-- [+] 0xFAA23F2CBA159D67
function StartPlayerSwitch(from, to, flags, switchType) end

-- [+] 0x60FE567DF1B1AF9D
function StartSaveArrayWithSize(p0, size, arrayName) end

-- [+] 0xA9575F812C6A7997
function StartSaveData(p0, p1, p2) end

-- [+] 0xBF737600CDDBEADD
function StartSaveStructWithSize(p0, size, structName) end

-- [+] 0xC7DB36C24634F52B
function StopBenchmarkRecording() end

-- [+] 0x63606A61DE68898A
function StopBinkMovie(binkMovie) end

-- [+] 0xF33AB75780BA57DE
function StopCamPointing(cam) end

-- [+] 0xBDECF64367884AC3
function StopCamShaking(cam, p1) end

-- [+] 0x2238E588E588A6D7
function StopCinematicCamShaking(p0) end

-- [+] 0x7660C6E75D3A078E
function StopCinematicShot(Any) end

-- [+] 0xC7272775B4DC786E
function StopCutscene(p0) end

-- [+] 0xDB629FFD9285FA06
function StopCutsceneCamShaking() end

-- [+] 0xD220BDD222AC4A1E
function StopCutsceneImmediately() end

-- [+] 0x0EF93E9F3D08C178
function StopGameplayCamShaking(bStopImmediately) end

-- [+] 0xF46C581C61718916
function StopGameplayHint(bStopImmediately) end

-- [+] 0x38C16A305E8CDC8D
function StopPadShake(padIndex) end

-- [+] 0x8F75998877616996
function StopParticleFxLooped(ptfxHandle, p1) end

-- [+] 0x95C0A5BBDC189AA1
function StopPlayerSwitch() end

-- [+] 0xC819F3CBB62BF692
function StopRenderingScriptCamsUsingCatchUp(bShouldApplyAcrossAllThreads, distanceToBlend, blendType) end

-- [+] 0x04456F95153C6BE4
function StopSaveArray() end

-- [+] 0x74E20C9145FB66FD
function StopSaveData() end

-- [+] 0xEB1774DF12BB9F12
function StopSaveStruct() end

-- [+] 0x1C9D7949FA533490
function StopScriptGlobalShaking(bStopImmediately) end

-- [+] 0x1F3F018BC3AFA77C
function StreamvolCreateFrustum(p0, p1, p2, p3, p4, p5, p6, p7, p8) end

-- [+] 0x0AD9710CEE2F590F
function StreamvolCreateLine(p0, p1, p2, p3, p4, p5, p6) end

-- [+] 0x219C7B8D53E429FD
function StreamvolCreateSphere(x, y, z, rad, p4, p5) end

-- [+] 0x1EE7D8DF4425F053
function StreamvolDelete(unused) end

-- [+] 0x7D41E9D2D17C5B2D
function StreamvolHasLoaded(unused) end

-- [+] 0x07C313F94746702C
function StreamvolIsValid(unused) end

-- [+] 0x5A5F40FE637EB584
function StringToInt(string, outInteger) end

-- [+] 0x1EAE0A6E978894A2
function SupressRandomEventThisFrame(eventType, enable) end

-- [+] 0x3D42B92563939375
function SwitchToInputMappingScheme(name) end

-- [+] 0xAAB3200ED59016BC
function SwitchToMultiFirstpart(ped, flags, switchType) end

-- [+] 0xD8295AF639FD9CB8
function SwitchToMultiSecondpart(ped) end

-- [+] 0x632106CC96E82E91
function Tan(p0) end

-- [+] 0x9DC711BC69C548DF
function TerminateAllScriptsWithThisName(scriptName) end

-- [+] 0xA356990E161C9E65
function TerraingridActivate(toggle) end

-- [+] 0x5CE62918F8D703C7
function TerraingridSetColours(lowR, lowG, lowB, lowAlpha, R, G, B, Alpha, highR, highG, highB, highAlpha) end

-- [+] 0x1C4FC5752BCD8E48
function TerraingridSetParams(x, y, z, p3, rotation, p5, width, height, p8, scale, glowIntensity, normalHeight, heightDiff) end

-- [+] 0xDFC252D8A3E15AB7
function TogglePausedRenderphases(toggle) end

-- [+] 0xFB80AB299D2EE1BD
function ToggleShowOptionalStuntJumpCamera(toggle) end

-- [+] 0xA328A24AAA6B7FDC
function TriggerScreenblurFadeIn(transitionTime) end

-- [+] 0xEFACC8AEF94430D5
function TriggerScreenblurFadeOut(transitionTime) end

-- [+] 0xD3A10FC7FD8D98CD
function Ui3dsceneIsAvailable() end

-- [+] 0xF1CEA8A4198D8E9A
function Ui3dscenePushPreset(presetName) end

-- [+] 0xEA2F2061875EED90
function UiStartedEndUserBenchmark() end

-- [+] 0xA74802FB8D0B7814
function UnloadCloudHat(name, p1) end

-- [+] 0xB7ED70C49521A61D
function UnpatchDecalDiffuseMap(decalType) end

-- [+] 0xDEADC0DEDEADC0DE
function UpdateLightsOnEntity(entity) end

-- [+] 0x0CF2B696BBF945AE
function UpdateOnscreenKeyboard() end

-- [+] 0x6C38AF3693A69A91
function UseParticleFxAsset(name) end

-- [+] 0x271401846BD26E92
function UseScriptCamForAmbientPopulationOriginThisFrame(vehicles, peds) end

-- [+] 0x6493CF69859B116A
function UseVehicleCamStuntSettingsThisUpdate() end

-- [+] 0xF14878FC50BEC6EE
function UsingMissionCreator(toggle) end

-- [+] 0x40C8656EDAEDD569
function WasCutsceneSkipped() end

-- [+] 0x5B712761429DBC14
function WashDecalsFromVehicle(vehicle, p1) end

-- [+] 0x9C30613D50A6ADEF
function WashDecalsInRange(p0, p1, p2, p3, p4) end

-- [+] 0xA8434F1DFF41D6E7
function WaterOverrideFadeIn(p0) end

-- [+] 0xC3C221ADDDE31A11
function WaterOverrideFadeOut(p0) end

-- [+] 0x31727907B2C43C55
function WaterOverrideSetOceannoiseminamplitude(minAmplitude) end

-- [+] 0x405591EC8FD9096D
function WaterOverrideSetOceanwaveamplitude(amplitude) end

-- [+] 0xB3E6360DDE733E82
function WaterOverrideSetOceanwavemaxamplitude(maxAmplitude) end

-- [+] 0xF751B16FB32ABC1D
function WaterOverrideSetOceanwaveminamplitude(minAmplitude) end

-- [+] 0x7C9C0B1EEB1F9072
function WaterOverrideSetRipplebumpiness(bumpiness) end

-- [+] 0xB9854DFDE0D833D6
function WaterOverrideSetRippledisturb(disturb) end

-- [+] 0x9F5E6BB6B34540DA
function WaterOverrideSetRipplemaxbumpiness(maxBumpiness) end

-- [+] 0x6216B116083A7CB4
function WaterOverrideSetRippleminbumpiness(minBumpiness) end

-- [+] 0xB8F87EAD7533B176
function WaterOverrideSetShorewaveamplitude(amplitude) end

-- [+] 0xA7A1127490312C36
function WaterOverrideSetShorewavemaxamplitude(maxAmplitude) end

-- [+] 0xC3EAD29AB273ECE8
function WaterOverrideSetShorewaveminamplitude(minAmplitude) end

-- [+] 0xC54A08C85AE4D410
function WaterOverrideSetStrength(strength) end
