-- Auto-generated FiveM native stubs
-- API Set: SERVER
-- Total natives: 686
-- Generated by smart classifier

-- ============================================

-- Namespace: GetEntityBonePosition (1 natives)

-- [+] 0x46F8696933A63C9B
function GetEntityBonePosition_2(entity, boneIndex) end

-- Namespace: HasEntityClearLosToEntity (1 natives)

-- [+] 0x394BDE2A7BBA031E
function HasEntityClearLosToEntity_2(entity1, entity2, traceType) end

-- Namespace: N (37 natives)

-- [+] 0x0F6F1EBBC4E1D5E6
function N_0x0f6f1ebbc4e1d5e6(scriptIndex, p1) end

-- [+] 0x0FFB3C758E8C07B9
function N_0x0ffb3c758e8c07b9(ped, p1) end

-- [+] 0x1A092BB0C3808B96
function N_0x1a092bb0c3808b96(entity, p1) end

-- [+] 0x1F351CF1C6475734
function N_0x1f351cf1c6475734(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9) end

-- [+] 0x22E21FBCFC88C149
function N_0x22e21fbcfc88c149(scriptIndex, p1) end

-- [+] 0x29682E2CCF21E9B5
function N_0x29682e2ccf21e9b5(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13) end

-- [+] 0x352E2B5CF420BF3B
function N_0x352e2b5cf420bf3b(p0, p1) end

-- [+] 0x36F32DE87082343E
function N_0x36f32de87082343e(p0, p1) end

-- [+] 0x38C1CB1CB119A016
function N_0x38c1cb1cb119a016(p0, p1) end

-- [+] 0x3E38E28A1D80DDF6
function N_0x3e38e28a1d80ddf6(ped) end

-- [+] 0x405DC2AEF6AF95B9
function N_0x405dc2aef6af95b9(roomHashKey) end

-- [+] 0x483ACA1176CA93F1
function N_0x483aca1176ca93f1() end

-- [+] 0x490861B88F4FD846
function N_0x490861b88f4fd846(p0) end

-- [+] 0x4C2330E61D3DEB56
function N_0x4c2330e61d3deb56(interior) end

-- [+] 0x53DDC75BC3AC0A90
function N_0x53ddc75bc3ac0a90(vehicle) end

-- [+] 0x5C3B791D580E0BC2
function N_0x5c3b791d580e0bc2(entity, p1) end

-- [+] 0x6100B3CEFD43452E
function N_0x6100b3cefd43452e(p0) end

-- [+] 0x68B562E124CC0AEF
function N_0x68b562e124cc0aef(p0, p1) end

-- [+] 0x7241CCB7D020DB69
function N_0x7241ccb7d020db69(entity, toggle) end

-- [+] 0x760910B49D2B98EA
function N_0x760910b49d2b98ea() end

-- [+] 0x78E8E3A640178255
function N_0x78e8e3a640178255(entity) end

-- [+] 0x7ECDF98587E92DEC
function N_0x7ecdf98587e92dec(p0) end

-- [+] 0x829CD22E043A2577
function N_0x829cd22e043a2577(p0) end

-- [+] 0x82EBB79E258FA2B7
function N_0x82ebb79e258fa2b7(entity, interiorID) end

-- [+] 0x836B62713E0534CA
function N_0x836b62713e0534ca() end

-- [+] 0x8423541E8B3A1589
function N_0x8423541e8b3a1589(p0, p1, p2) end

-- [+] 0x8634CEF2522D987B
function N_0x8634cef2522d987b(ped, p1, value) end

-- [+] 0x9D252648778160DF
function N_0x9d252648778160df(p0) end

-- [+] 0x9E6542F0CE8E70A3
function N_0x9e6542f0ce8e70a3(toggle) end

-- [+] 0xAA76052DDA9BFC3E
function N_0xaa76052dda9bfc3e(p0, p1, p2, p3, p4, p5, p6) end

-- [+] 0xAB13A5565480B6D9
function N_0xab13a5565480b6d9(ped, p1) end

-- [+] 0xAF348AFCB575A441
function N_0xaf348afcb575a441(roomName) end

-- [+] 0xB17BC6453F6CF5AC
function N_0xb17bc6453f6cf5ac(p0, p1) end

-- [+] 0xC34BC448DA29F5E9
function N_0xc34bc448da29f5e9(entity, toggle) end

-- [+] 0xCEA7C8E1B48FF68C
function N_0xcea7c8e1b48ff68c(p0, p1) end

-- [+] 0xE66377CDDADA4810
function N_0xe66377cddada4810(entity, p1) end

-- [+] 0xFA83CA6776038F64
function N_0xfa83ca6776038f64(x, y, z) end

-- Namespace: SetTaskMoveNetworkSignalFloat (1 natives)

-- [+] 0x373EF409B82697A3
function SetTaskMoveNetworkSignalFloat_2(ped, signalName, value) end

-- Namespace: TriggerScriptEvent (1 natives)

-- [+] 0xA40CC53DF8E50837
function TriggerScriptEvent_2() end

-- Namespace: UNKNOWN (645 natives)

-- [+] 0x55E86AF2712B36A1
function ActivateInteriorEntitySet(interior, entitySetName) end

-- [+] 0x45C597097DD7CB81
function AddCoverBlockingArea(playerX, playerY, playerZ, radiusX, radiusY, radiusZ, p6, p7, p8, p9) end

-- [+] 0xD5C12A75C7B9497F
function AddCoverPoint(p0, p1, p2, p3, p4, p5, p6, p7) end

-- [+] 0xE3AD2BDBAEE269AC
function AddExplosion(x, y, z, explosionType, damageScale, isAudible, isInvisible, cameraShake) end

-- [+] 0x36DD3FE58B5E5212
function AddExplosionWithUserVfx(x, y, z, explosionType, explosionFx, damageScale, isAudible, isInvisible, cameraShake) end

-- [+] 0xFCD5C8E06E502F5A
function AddNavmeshBlockingObject(x, y, z, width, length, height, heading, bPermanent, flags) end

-- [+] 0x387EAD7EE42F6685
function AddNavmeshRequiredRegion(x, y, radius) end

-- [+] 0x172AA1B624FA1013
function AddOwnedExplosion(ped, x, y, z, explosionType, damageScale, isAudible, isInvisible, cameraShake) end

-- [+] 0x23083260DEC3A551
function AddPatrolRouteLink(id1, id2) end

-- [+] 0x8EDF950167586B7C
function AddPatrolRouteNode(id, guardScenario, x1, y1, z1, x2, y2, z2, waitTime) end

-- [+] 0x3F6167F351168730
function AddPickupToInteriorRoomByName(pickup, roomName) end

-- [+] 0x5CF0D8F9BBA0DD75
function AddVehicleSubtaskAttackCoord(ped, x, y, z) end

-- [+] 0x85F462BADC7DA47F
function AddVehicleSubtaskAttackPed(ped, ped2) end

-- [+] 0xC5F68BE9613E2D18
function ApplyForceToEntity(entity, forceType, x, y, z, offX, offY, offZ, nComponent, bLocalForce, bLocalOffset, bScaleByMass, bPlayAudio, bScaleByTimeWarp) end

-- [+] 0x18FF00FC7EFF559E
function ApplyForceToEntityCenterOfMass(entity, forceType, x, y, z) end

-- [+] 0x8415D95B194A3AEA
function AreAllNavmeshRegionsLoaded() end

-- [+] 0xF7B79A50B905A30D
function AreNodesLoadedForArea(x1, y1, x2, y2) end

-- [+] 0x60F9A4393A21F741
function AssistedMovementIsRouteLoaded(route) end

-- [+] 0x13945951E16EF912
function AssistedMovementOverrideLoadDistanceThisFrame(dist) end

-- [+] 0x3548536485DD792B
function AssistedMovementRemoveRoute(route) end

-- [+] 0x817268968605947A
function AssistedMovementRequestRoute(route) end

-- [+] 0xD5002D78B7162E1B
function AssistedMovementSetRouteProperties(route, props) end

-- [+] 0x5C48B75732C8456C
function AttachEntityBoneToEntityBone(entity1, entity2, entityBone, entityBone2, p4, p5) end

-- [+] 0xFD1695C5D3B05439
function AttachEntityBoneToEntityBonePhysically(entity1, entity2, entityBone, entityBone2, p4, p5) end

-- [+] 0x6B9BBD38AB0796DF
function AttachEntityToEntity(entity1, entity2, boneIndex, xPos, yPos, zPos, xRot, yRot, zRot, p9, useSoftPinning, collision, isPed, rotationOrder, syncRot) end

-- [+] 0xC3675780C92F90F9
function AttachEntityToEntityPhysically(entity1, entity2, boneIndex1, boneIndex2, xPos1, yPos1, zPos1, xPos2, yPos2, zPos2, xRot, yRot, zRot, breakForce, fixedRot, p15, collision, teleport, p18) end

-- [+] 0xDC2BACD920D0A0DD
function BgEndContext(contextName) end

-- [+] 0x107E5CC7CA942BC1
function BgEndContextHash(contextHash) end

-- [+] 0x9D5A25BADB742ACD
function BgStartContext(contextName) end

-- [+] 0x75B18E49607874C7
function BgStartContextHash(contextHash) end

-- [+] 0xADD95C7005C4A197
function CalculateTravelDistanceBetweenPoints(x1, y1, z1, x2, y2, z2) end

-- [~] 0x128F79EDCECE4FD5
function CanPedRagdoll(ped) end

-- [+] 0xD9175F941610DB54
function CapInterior(interiorID, toggle) end

-- [+] 0xC35B5CDB2824CF69
function ClearDrivebyTaskUnderneathDrivingTask(ped) end

-- [+] 0xA72CD9CA74A5ECBA
function ClearEntityLastDamageEntity(Any) end

-- [+] 0x2801D0012266DF07
function ClearGpsDisabledZoneAtIndex(index) end

-- [+] 0x85D5422B2039A70D
function ClearInteriorForEntity(entity) end

-- [+] 0xF6DC48E56BE1243A
function ClearPedScriptTaskIfRunningThreatResponseNonTempTask(ped) end

-- [+] 0x176CECF6F920D707
function ClearPedSecondaryTask(ped) end

-- [+] 0xE1EF3C1216AFF2CD
function ClearPedTasks(ped) end

-- [+] 0xAAA34F8A7CB32098
function ClearPedTasksImmediately(ped) end

-- [~] 0xD86D101FCFD00A4B
function ClearRagdollBlockingFlags(ped, flags) end

-- [+] 0xB365FC0C4E27FFA7
function ClearRoomForEntity(entity) end

-- [+] 0x23B59D8912F94246
function ClearRoomForGameViewport() end

-- [+] 0x3841422E9C488D8C
function ClearSequenceTask(Any) end

-- [+] 0xDBBC7A2432524127
function ClearVehicleTasks(vehicle) end

-- [+] 0xB043ECA801B8CBC1
function ClosePatrolRoute() end

-- [+] 0x39E72BC99E6360CB
function CloseSequenceTask(Any) end

-- [+] 0xDCFE42068FE0135A
function ControlMountedWeapon(ped) end

-- [+] 0x150E808B375A385A
function CreateForcedObject(x, y, z, p3, modelHash, p5) end

-- [+] 0x8A97BCA30A0CE478
function CreateModelHide(x, y, z, radius, model, surviveMapReload) end

-- [+] 0x3A52AE588830BF7F
function CreateModelHideExcludingScriptObjects(x, y, z, radius, model, surviveMapReload) end

-- [+] 0x92C47782FDA8B2A3
function CreateModelSwap(x, y, z, radius, originalModel, newModel, bSurviveMapReload) end

-- [+] 0xAF8A443CCC8018DC
function CreatePatrolRoute() end

-- [+] 0x420BD37289EEE162
function DeactivateInteriorEntitySet(interior, entitySetName) end

-- [+] 0xAE3CBE5BF394C9C9
function DeleteEntity(entity) end

-- [+] 0x7767DD9D65E91319
function DeletePatrolRoute(patrolRoute) end

-- [+] 0x7C0043FDFF6436BC
function DetachContainerFromHandlerFrame(vehicle) end

-- [+] 0x961AC54BF0613F5D
function DetachEntity(entity, dynamic, collision) end

-- [+] 0xAF03011701811146
function DetachEntityFromCargobob(vehicle, entity) end

-- [+] 0xADF7BE450512C12F
function DetachVehicleFromAnyCargobob(vehicle) end

-- [+] 0xD0E9CE05A1E68CD8
function DetachVehicleFromAnyTowTruck(vehicle) end

-- [+] 0x0E21D3DF1051399D
function DetachVehicleFromCargobob(cargobob, vehicle) end

-- [+] 0xC2DB6B6708350ED8
function DetachVehicleFromTowTruck(towTruck, vehicle) end

-- [+] 0x90532EDF0D2BDD86
function DetachVehicleFromTrailer(vehicle) end

-- [+] 0x6170941419D7D8EC
function DisableInterior(interiorID, toggle) end

-- [+] 0x4C8872D8CDBE1B8B
function DisableNavmeshInArea(Any) end

-- [+] 0xDDE6DF5AE89981D2
function DoesEntityBelongToThisScript(entity, p2) end

-- [+] 0x7239B21A38F536BA
function DoesEntityExist(entity) end

-- [+] 0x2158E81A6AF65EA9
function DoesEntityHaveAnimDirector(entity) end

-- [+] 0x060D6E96F8B8E48D
function DoesEntityHaveDrawable(entity) end

-- [+] 0xDA95EA3317CC5064
function DoesEntityHavePhysics(entity) end

-- [+] 0x764EB96874EFFDC1
function DoesEntityHaveSkeletonData(entity) end

-- [+] 0x0EAEB0DB4B132399
function DoesNavmeshBlockingObjectExist(p0) end

-- [+] 0x5A59271FFADD33C1
function DoesScenarioExistInArea(x, y, z, radius, b) end

-- [+] 0xF9034C136C9E00D3
function DoesScenarioGroupExist(scenarioGroup) end

-- [+] 0x0A9D0C2A3BBC86C1
function DoesScenarioOfTypeExistInArea(p0, p1, p2, p3, p4, p5) end

-- [+] 0xFC04745FBE67C19A
function DoesScriptExist(scriptName) end

-- [+] 0xF86AA3C56BA31381
function DoesScriptWithNameHashExist(scriptHash) end

-- [+] 0xA98B8E3C088E5A31
function DoesScriptedCoverPointExistAtCoords(x, y, z) end

-- [+] 0x6CE177D014502E8A
function EnableEntityUnk(entity) end

-- [+] 0xA97F257D0151A6AB
function EnableExteriorCullModelThisFrame(mapObjectHash) end

-- [+] 0x50C375537449F369
function EnableScriptCullModelThisFrame(Any) end

-- [+] 0x07F1BE2BCCAA27A7
function FindAnimEventPhase(animDictionary, animName, p2, p3, p4) end

-- [+] 0x40FDEDB72F8293B2
function ForceEntityAiAndAnimationUpdate(entity) end

-- [+] 0x52923C4710DD9907
function ForceRoomForEntity(entity, interior, roomHashKey) end

-- [+] 0x920D853F3E17F1DA
function ForceRoomForGameViewport(interiorID, roomHashKey) end

-- [+] 0x428CA6DBD1094446
function FreezeEntityPosition(entity, toggle) end

-- [+] 0xF90125F1F79ECDF8
function GenerateDirectionsToCoord(x, y, z, p3, direction, vehicle, distToNxJunction) end

-- [+] 0x534AEBA6E5ED4CAB
function GetActiveVehicleMissionType(vehicle) end

-- [+] 0xFEDDF04D62B8D790
function GetAnimDuration(animDict, animName) end

-- [+] 0x352A9F6BCF90081F
function GetClosestFirePos(outPosition, x, y, z) end

-- [+] 0x2EABE3B06F58C1BE
function GetClosestMajorVehicleNode(x, y, z, outPosition, zMeasureMult, zTolerance) end

-- [+] 0x132F52BBA570FE92
function GetClosestRoad(Any) end

-- [+] 0x240A18690AE96513
function GetClosestVehicleNode(x, y, z, outPosition, nodeFlags, zMeasureMult, zTolerance) end

-- [+] 0xFF071FB798B803B0
function GetClosestVehicleNodeWithHeading(x, y, z, outPosition, outHeading, nodeFlags, zMeasureMult, zTolerance) end

-- [+] 0xE465D4AB7CA6AE72
function GetCollisionNormalOfLastHitForEntity(entity) end

-- [+] 0x5A47B3B5E63E94C6
function GetEntityAlpha(entity) end

-- [+] 0x346D81500D088F42
function GetEntityAnimCurrentTime(entity, animDict, animName) end

-- [+] 0x50BD2730B191E360
function GetEntityAnimTotalTime(entity, animDict, animName) end

-- [+] 0x48C2BED9180FE123
function GetEntityAttachedTo(entity) end

-- [+] 0xB328DCC3A3AA401B
function GetEntityBoneCount(entity) end

-- [+] 0xFB71170B7E76ACBA
function GetEntityBoneIndexByName(entity, boneName) end

-- [+] 0xCE6294A232D03786
function GetEntityBoneRotation(entity, boneIndex) end

-- [+] 0xBD8D32550E5CEBFE
function GetEntityBoneRotationLocal(entity, boneIndex) end

-- [+] 0xD95CC5D2AB15A09F
function GetEntityCanBeDamaged(entity) end

-- [+] 0xCCF1E97BEFDAE480
function GetEntityCollisionDisabled(entity) end

-- [+] 0x3FEF770D40960D5A
function GetEntityCoords(entity, alive) end

-- [+] 0x0A794A5A57F8DF91
function GetEntityForwardVector(entity) end

-- [+] 0x8BB4EF4214E0E6D5
function GetEntityForwardX(entity) end

-- [+] 0x866A4A5FAE349510
function GetEntityForwardY(entity) end

-- [+] 0xE83D4F9BA2A38914
function GetEntityHeading(entity) end

-- [+] 0x846BF6291198A71E
function GetEntityHeadingFromEulers(entity) end

-- [+] 0xEEF059FAD016D209
function GetEntityHealth(entity) end

-- [+] 0x5A504562485944DD
function GetEntityHeight(entity, X, Y, Z, atTop, inWorldCoords) end

-- [+] 0x1DD55701034110E5
function GetEntityHeightAboveGround(entity) end

-- [+] 0x14BA4BA137AF6CEC
function GetEntityInsideExplosionArea(explosionType, x1, y1, z1, x2, y2, z2, radius) end

-- [+] 0xB3CD51E3DB86F176
function GetEntityInsideExplosionSphere(explosionType, x, y, z, radius) end

-- [+] 0x4159C2762B5791D6
function GetEntityLodDist(entity) end

-- [+] 0xECB2FC7235A7D137
function GetEntityMatrix(entity, forwardVector, rightVector, upVector, position) end

-- [+] 0x15D757606D170C3C
function GetEntityMaxHealth(entity) end

-- [+] 0x9F47B058362C84B5
function GetEntityModel(entity) end

-- [+] 0x1F922734E259BD26
function GetEntityPickup(entity, modelHash) end

-- [+] 0xD45DC2893621E1FE
function GetEntityPitch(entity) end

-- [+] 0xF6F5161F4534EDFF
function GetEntityPopulationType(entity) end

-- [+] 0xBE8CD9BE829BBEBF
function GetEntityProofs(entity, bulletProof, fireProof, explosionProof, collisionProof, meleeProof, steamProof, p7, drownProof) end

-- [+] 0x7B3703D2D32DFA18
function GetEntityQuaternion(entity, x, y, z, w) end

-- [+] 0x831E0242595560DF
function GetEntityRoll(entity) end

-- [+] 0xAFBD61CC738D9EB9
function GetEntityRotation(entity, rotationOrder) end

-- [+] 0x213B91045D09B983
function GetEntityRotationVelocity(entity) end

-- [+] 0xD5037BA82E12416F
function GetEntitySpeed(entity) end

-- [+] 0x9A8D700A51CB7B0D
function GetEntitySpeedVector(entity, relative) end

-- [+] 0xE81AFC1BC4CC41CE
function GetEntitySubmergedLevel(entity) end

-- [+] 0x8ACD366038D14505
function GetEntityType(entity) end

-- [+] 0x95EED5A694951F9F
function GetEntityUprightValue(entity) end

-- [+] 0x4805D2B1D8CF94A9
function GetEntityVelocity(entity) end

-- [+] 0xD8F66A3A60C62153
function GetEventAtIndex(eventGroup, eventIndex) end

-- [+] 0x2902843FCD2B2D79
function GetEventData(eventGroup, eventIndex, eventData, eventDataSize) end

-- [+] 0x936E6168A9BCEDB5
function GetEventExists(eventGroup, eventIndex) end

-- [+] 0x869DAACBBE9FA006
function GetGpsBlipRouteFound() end

-- [+] 0xBBB45C3CF5C8AA85
function GetGpsBlipRouteLength() end

-- [+] 0x8A1C8B1738FFE87E
function GetHashOfThisScriptName() end

-- [+] 0x3599D741C9AC6310
function GetHeightmapBottomZForArea(x1, y1, x2, y2) end

-- [+] 0x336511A34F2E5185
function GetHeightmapBottomZForPosition(x, y) end

-- [+] 0x8ABE8608576D9CE3
function GetHeightmapTopZForArea(x1, y1, x2, y2) end

-- [+] 0x29C24BFBED8AB8FB
function GetHeightmapTopZForPosition(x, y) end

-- [+] 0xC30338E8088E2E21
function GetIdOfThisThread() end

-- [+] 0xB0F7F8663821D9C3
function GetInteriorAtCoords(x, y, z) end

-- [+] 0x05B7A89BD78797FC
function GetInteriorAtCoordsWithType(x, y, z, interiorType) end

-- [+] 0xF0F77ADB9F67E79D
function GetInteriorAtCoordsWithTypehash(x, y, z) end

-- [+] 0xEC4CF9FCB29A4424
function GetInteriorFromCollision(x, y, z) end

-- [+] 0x2107BA504071A6BB
function GetInteriorFromEntity(entity) end

-- [+] 0xE7D267EC6CA966C3
function GetInteriorFromPrimaryView() end

-- [+] 0xE4A84ABF135EF91A
function GetInteriorGroupId(interior) end

-- [+] 0xF49B58631D9E22D9
function GetInteriorHeading(interior) end

-- [+] 0x252BDC06B73FA6EA
function GetInteriorLocationAndNamehash(interior, position, nameHash) end

-- [+] 0xB0760331C7AA4155
function GetIsTaskActive(ped, taskIndex) end

-- [+] 0xCB4E8BE8A0063C5D
function GetIsWaypointRecordingLoaded(name) end

-- [+] 0x399685DB942336BC
function GetKeyForEntityInRoom(entity) end

-- [+] 0x5C3D0A935F535C4C
function GetLastMaterialHitByEntity(entity) end

-- [+] 0xC6F5C0BCDC74D62D
function GetNavmeshRouteDistanceRemaining(ped, distanceRemaining, isPathReady) end

-- [+] 0x632E831F382A0FA8
function GetNavmeshRouteResult(ped) end

-- [+] 0x7196842CB375CDB3
function GetNearestPlayerToEntity(entity) end

-- [+] 0x4DC9A62F844D9337
function GetNearestPlayerToEntityOnTeam(entity, team) end

-- [+] 0xD3A6A0EF48823A8C
function GetNextGpsDisabledZoneIndex(index) end

-- [+] 0x18C1270EA7F199BC
function GetNoLoadingScreen() end

-- [+] 0xE50E52416CCF948B
function GetNthClosestVehicleNode(x, y, z, nthClosest, outPosition, nodeFlags, Any) end

-- [+] 0x45905BE8654AE067
function GetNthClosestVehicleNodeFavourDirection(x, y, z, desiredX, desiredY, desiredZ, nthClosest, outPosition, outHeading, nodeFlags, Any) end

-- [+] 0x22D7275A79FE8215
function GetNthClosestVehicleNodeId(x, y, z, nthClosest, nodeFlags, zMeasureMult, zTolerance) end

-- [+] 0x6448050E9C2A7207
function GetNthClosestVehicleNodeIdWithHeading(x, y, z, nthClosest, outPosition) end

-- [+] 0x80CA6A8B6C094CC4
function GetNthClosestVehicleNodeWithHeading(x, y, z, nthClosest, outPosition, outHeading, totalLanes, nodeFlags, zMeasureMult, zTolerance) end

-- [+] 0x01708E8DD3FF8C65
function GetNumNavmeshesExistingInArea(posMinX, posMinY, posMinZ, posMaxX, posMaxY, posMaxZ) end

-- [+] 0x5F92A689A06620AA
function GetNumberOfEvents(eventGroup) end

-- [+] 0x50CAD495A460B305
function GetNumberOfFiresInRange(x, y, z, radius) end

-- [+] 0x2C83A9DA6BFFC4F9
function GetNumberOfReferencesOfScriptWithNameHash(scriptHash) end

-- [+] 0xD7E3B9735C0F89D6
function GetObjectIndexFromEntityIndex(entity) end

-- [+] 0x2274BC1C4885E333
function GetOffsetFromEntityGivenWorldCoords(entity, posX, posY, posZ) end

-- [+] 0x1899F328B0E12848
function GetOffsetFromEntityInWorldCoords(entity, offsetX, offsetY, offsetZ) end

-- [+] 0x9E3B3E6D66F6E22F
function GetOffsetFromInteriorInWorldCoords(interior, x, y, z) end

-- [+] 0x8517D4A6CA8513ED
function GetPedDesiredMoveBlendRatio(ped) end

-- [+] 0x04A2A40C73395041
function GetPedIndexFromEntityIndex(entity) end

-- [~] 0x2057EF813397A772
function GetPedRagdollBoneIndex(ped, bone) end

-- [+] 0xE6A877C64CAF1BC5
function GetPedWaypointDistance(p0) end

-- [+] 0x2720AAA75001E094
function GetPedWaypointProgress(ped) end

-- [+] 0x47619ABE8B268C60
function GetPhoneGestureAnimCurrentTime(ped) end

-- [+] 0x1EE0F68A7C25DEC6
function GetPhoneGestureAnimTotalTime(ped) end

-- [+] 0x16F46FB18C8009E4
function GetPointOnRoadSide(x, y, z, p3, outPosition) end

-- [+] 0xF3162836C28F9DA5
function GetPosAlongGpsTypeRoute(result, bStartAtPlayerPos, fDistanceAlongRoute, slotType) end

-- [+] 0x93E0DB8440B73A7D
function GetRandomVehicleNode(x, y, z, radius, p4, p5, p6, outPosition, nodeId) end

-- [+] 0xA0F8A7517A273C05
function GetRoadBoundaryUsingHeading(x, y, z, heading, outPosition) end

-- [+] 0xA6575914D2A0B450
function GetRoomKeyForGameViewport() end

-- [+] 0x47C2A06D4F5F424B
function GetRoomKeyFromEntity(entity) end

-- [+] 0xB61C8E878A4199CA
function GetSafeCoordForPed(x, y, z, onlyOnPavement, outPosition, flags) end

-- [+] 0x77F1BEB8863288D5
function GetScriptTaskStatus(ped, taskHash) end

-- [+] 0x594A1028FC2A3E85
function GetScriptedCoverPointCoords(coverpoint) end

-- [+] 0x00A9010CFE1E3533
function GetSequenceProgress(ped) end

-- [+] 0x2EB41072B4C1E4C0
function GetStreetNameAtCoord(x, y, z, streetName, crossingRoad) end

-- [+] 0xB4F47213DF45A64C
function GetTaskMoveNetworkEvent(ped, eventName) end

-- [+] 0xA7FFBA498E4AAF67
function GetTaskMoveNetworkSignalBool(ped, signalName) end

-- [+] 0x44AB0B3AFECCE242
function GetTaskMoveNetworkSignalFloat(ped, signalName) end

-- [+] 0x4B53F92932ADFAC0
function GetVehicleIndexFromEntityIndex(entity) end

-- [+] 0xA2AE5C478B96E3B6
function GetVehicleNodeIsGpsAllowed(nodeID) end

-- [+] 0x4F5070AA58F69279
function GetVehicleNodeIsSwitchedOff(nodeID) end

-- [+] 0x703123E5E7D429C2
function GetVehicleNodePosition(nodeId, outPosition) end

-- [+] 0x0568566ACBB5DEDC
function GetVehicleNodeProperties(x, y, z, density, flags) end

-- [+] 0x9824CFF8FC66E159
function GetVehicleWaypointProgress(vehicle) end

-- [+] 0x416B62AC8B9E5BBD
function GetVehicleWaypointTargetPoint(vehicle) end

-- [+] 0xA5B769058763E497
function GetWaypointDistanceAlongRoute(p0, p1) end

-- [+] 0x44A8FCB8ED227738
function GetWorldPositionOfEntityBone(entity, boneIndex) end

-- [+] 0xB282DC6EBD803C75
function GiveDelayedWeaponToPed(ped, weaponHash, ammoCount, bForceInHand) end

-- [+] 0x68F8BE6AF5CDF8A6
function GiveLoadoutToPed(ped, Any) end

-- [+] 0xD966D51AA5B28BB9
function GiveWeaponComponentToPed(ped, weaponHash, componentHash) end

-- [+] 0x33E179436C0B31DB
function GiveWeaponComponentToWeaponObject(weaponObject, addonHash) end

-- [+] 0xB1FA61371AF7C4B7
function GiveWeaponObjectToPed(weaponObject, ped) end

-- [+] 0xBF0FD6E56C964FCB
function GiveWeaponToPed(ped, weaponHash, ammoCount, isHidden, bForceInHand) end

-- [+] 0xEAF4CD9EA3E7E922
function HasAnimEventFired(entity, actionHash) end

-- [+] 0xE9676F61BC0B3321
function HasCollisionLoadedAroundEntity(entity) end

-- [+] 0x20B711662962B472
function HasEntityAnimFinished(entity, animDict, animName, p3) end

-- [+] 0x95EB9964FF5C5C65
function HasEntityBeenDamagedByAnyObject(entity) end

-- [+] 0x605F5A140F202491
function HasEntityBeenDamagedByAnyPed(entity) end

-- [+] 0xDFD5033FDBA0A9C8
function HasEntityBeenDamagedByAnyVehicle(entity) end

-- [+] 0xC86D67D52A707CF8
function HasEntityBeenDamagedByEntity(entity, damager, bCheckDamagerVehicle) end

-- [+] 0xFCDFF7B72D23A1AC
function HasEntityClearLosToEntity(entity1, entity2, flags) end

-- [+] 0x0267D00AF114F17A
function HasEntityClearLosToEntityInFront(entity1, entity2) end

-- [+] 0x8BAD02F0368D9E14
function HasEntityCollidedWithAnything(entity) end

-- [+] 0xE6CC9F3BA0FB9EF1
function HasScriptLoaded(scriptName) end

-- [+] 0x5F0F0C783EB16C04
function HasScriptWithNameHashLoaded(scriptHash) end

-- [+] 0x731EC8A916BD11A1
function IsAnEntity(handle) end

-- [+] 0xEEA5AC2EDA7C33E8
function IsCollisionMarkedOutside(x, y, z) end

-- [+] 0x8785E6E40C7A8818
function IsDrivebyTaskUnderneathDrivingTask(ped) end

-- [+] 0x0A7B270912999B3C
function IsEntityAMissionEntity(entity) end

-- [+] 0x524AC5ECEA15343E
function IsEntityAPed(entity) end

-- [+] 0x6AC7003FA6E5575E
function IsEntityAVehicle(entity) end

-- [+] 0x8D68C8FD0FACA94E
function IsEntityAnObject(entity) end

-- [+] 0x20B60995556D004F
function IsEntityAtCoord(entity, xPos, yPos, zPos, xSize, ySize, zSize, highlightArea, do3dCheck, transportMode) end

-- [+] 0x751B70C3D034E187
function IsEntityAtEntity(entity, target, xSize, ySize, zSize, highlightArea, do3dCheck, transportMode) end

-- [+] 0xB346476EF1A64897
function IsEntityAttached(entity) end

-- [+] 0xCF511840CEEDE0CC
function IsEntityAttachedToAnyObject(entity) end

-- [+] 0xB1632E9A5F988D11
function IsEntityAttachedToAnyPed(entity) end

-- [+] 0x26AA915AD89BFB4B
function IsEntityAttachedToAnyVehicle(entity) end

-- [+] 0xEFBE71898A993728
function IsEntityAttachedToEntity(from, to) end

-- [+] 0x5F9532F3B5CC2551
function IsEntityDead(entity) end

-- [+] 0x886E37EC497200B6
function IsEntityInAir(entity) end

-- [+] 0x51210CED3DA1C78A
function IsEntityInAngledArea(entity, x1, y1, z1, x2, y2, z2, width, debug, includez, p10) end

-- [+] 0x54736AA40E271165
function IsEntityInArea(entity, x1, y1, z1, x2, y2, z2, p7, p8, p9) end

-- [+] 0xCFB0A0D8EDD145A3
function IsEntityInWater(entity) end

-- [+] 0xB6463CF6AF527071
function IsEntityInZone(entity, zone) end

-- [+] 0xE31C2C72B8692B64
function IsEntityOccluded(entity) end

-- [+] 0x28D3FED7190D3A0B
function IsEntityOnFire(entity) end

-- [+] 0xE659E47AF827484B
function IsEntityOnScreen(entity) end

-- [+] 0x1F0B79228E461EC9
function IsEntityPlayingAnim(entity, animDict, animName, taskFlag) end

-- [+] 0x1218E6886D3D8327
function IsEntityStatic(entity) end

-- [+] 0x17FFC1B2BA35A494
function IsEntityTouchingEntity(entity, targetEntity) end

-- [+] 0x0F42323798A58C8C
function IsEntityTouchingModel(entity, modelHash) end

-- [+] 0x5333F526F6AB19AA
function IsEntityUpright(entity, angle) end

-- [+] 0x1DBD58820FA61D71
function IsEntityUpsidedown(entity) end

-- [+] 0x47D6F43D77935C75
function IsEntityVisible(entity) end

-- [+] 0xD796CB5BA8F20E32
function IsEntityVisibleToScript(entity) end

-- [+] 0xD05BFF0C0A12C68F
function IsEntityWaitingForWorldCollision(entity) end

-- [+] 0x6070104B699B2EF4
function IsExplosionActiveInArea(explosionType, x1, y1, z1, x2, y2, z2) end

-- [+] 0xA079A6C51525DC4B
function IsExplosionInAngledArea(explosionType, x1, y1, z1, x2, y2, z2, width) end

-- [+] 0x2E2EBA0EE7CED0E0
function IsExplosionInArea(explosionType, x1, y1, z1, x2, y2, z2) end

-- [+] 0xAB0F816885B0E483
function IsExplosionInSphere(explosionType, x, y, z, radius) end

-- [+] 0x92BAC8ACF88CEC26
function IsInteriorCapped(interiorID) end

-- [+] 0xBC5115A5A939DD15
function IsInteriorDisabled(interior) end

-- [+] 0x35F7DD45E8C0A16D
function IsInteriorEntitySetActive(interior, entitySetName) end

-- [+] 0x6726BDCCC1932F0E
function IsInteriorReady(interiorID) end

-- [+] 0xBC72B5D7A1CBD54D
function IsInteriorScene() end

-- [+] 0xA320EF046186FA3B
function IsMountedWeaponTaskUnderneathDrivingTask(ped) end

-- [+] 0xD4D8636C0199A939
function IsMoveBlendRatioRunning(ped) end

-- [+] 0x24A2AD74FA9814E2
function IsMoveBlendRatioSprinting(ped) end

-- [+] 0x349CE7B56DAFD95C
function IsMoveBlendRatioStill(ped) end

-- [+] 0xF133BBBE91E1691F
function IsMoveBlendRatioWalking(ped) end

-- [+] 0xF813C7E63F9062A5
function IsNavmeshLoadedInArea(x1, y1, z1, x2, y2, z2) end

-- [+] 0x705A844002B39DC0
function IsNavmeshRequiredRegionOwnedByAnyThread() end

-- [+] 0xAA135F9482C82CC3
function IsPedActiveInScenario(ped) end

-- [+] 0x90A09F3A45FED688
function IsPedBeingArrested(ped) end

-- [~] 0x863B23EFDE9C5DF2
function IsPedBeingStealthKilled(ped) end

-- [+] 0x74E559B3BC910685
function IsPedCuffed(ped) end

-- [+] 0x2A74E1D5F2F00EEC
function IsPedGettingUp(ped) end

-- [+] 0xDEB6D52126E7D640
function IsPedInWrithe(ped) end

-- [~] 0xFD4CCDBCC59941B7
function IsPedPerformingStealthKill(ped) end

-- [+] 0x621C6E4729388E41
function IsPedPlayingBaseClipInScenario(ped) end

-- [~] 0x47E4E977581C5B55
function IsPedRagdoll(ped) end

-- [+] 0xC5286FFC176F28A2
function IsPedRunning(ped) end

-- [+] 0x3DC52677769B4AE0
function IsPedRunningArrestTask(ped) end

-- [~] 0xE3B6097CC25AA69E
function IsPedRunningRagdollTask(ped) end

-- [+] 0x57E457CD2C0FC168
function IsPedSprinting(ped) end

-- [+] 0xAC29253EEF8F0180
function IsPedStill(ped) end

-- [+] 0xE45B7F222DE47E09
function IsPedStrafing(ped) end

-- [+] 0xDE4C184B2B9B071A
function IsPedWalking(ped) end

-- [+] 0xB8EBB1E9D3588C10
function IsPlayingPhoneGestureAnim(ped) end

-- [+] 0x125BF4ABFC536B09
function IsPointOnRoad(x, y, z, vehicle) end

-- [+] 0x367A09DED4E05B99
function IsScenarioGroupEnabled(scenarioGroup) end

-- [+] 0x788756D73AC2E07C
function IsScenarioOccupied(p0, p1, p2, p3, p4) end

-- [+] 0x3A815DB3EA088722
function IsScenarioTypeEnabled(scenarioType) end

-- [+] 0x921CE12C489C4C41
function IsTaskMoveNetworkActive(ped) end

-- [+] 0x30ED88D5E0C56A37
function IsTaskMoveNetworkReadyForTransition(ped) end

-- [+] 0x46E9AE36D8FA6417
function IsThreadActive(threadId) end

-- [+] 0x26B0E73D7EAAF4D3
function IsValidInterior(interior) end

-- [+] 0x1EAF30FCFBF5AF74
function IsVehicleNodeIdValid(vehicleNodeId) end

-- [+] 0xE03B3F2D3DC59B64
function IsWaypointPlaybackGoingOnForPed(p0) end

-- [+] 0xF5134943EA29868C
function IsWaypointPlaybackGoingOnForVehicle(vehicle) end

-- [+] 0x80E4A6EDDB0BE8D9
function LoadAllPathNodes(keepInMemory) end

-- [+] 0xB1577667C3708F9B
function LockLoadingScreenButtons() end

-- [+] 0xA36BFB5EE89F3D82
function OpenPatrolRoute(patrolRoute) end

-- [+] 0xE8854A4326B9E12B
function OpenSequenceTask(Any) end

-- [+] 0x295E3CCEC879CCD7
function PedHasUseScenarioTask(ped) end

-- [+] 0x2CA429C029CCF247
function PinInteriorInMemory(interior) end

-- [+] 0x748040460F8DF5DC
function PlayAnimOnRunningScenario(ped, animDict, animName) end

-- [+] 0x7FB218262B810701
function PlayEntityAnim(entity, animName, animDict, fBlendDelta, bLoop, bHoldLastFrame, bDriveToPose, fStartPhase, iFlags) end

-- [+] 0x77A1EEC547E7FCF1
function PlayEntityScriptedAnim(p0, p1, p2, p3, p4, p5) end

-- [+] 0xC77720A12FE14A86
function PlaySynchronizedEntityAnim(entity, syncedScene, animName, animDictName, fBlendInDelta, fBlendOutDelta, iFlags, fMoverBlendInDelta) end

-- [+] 0xB9C54555ED30FBC4
function PlaySynchronizedMapEntityAnim(x, y, z, radius, Any) end

-- [+] 0xF4080490ADC51C6F
function ProcessEntityAttachments(entity) end

-- [+] 0x41F37C3427C75AE0
function RefreshInterior(interiorID) end

-- [+] 0x0ABF535877897560
function RemoveAirDefenseZone(zoneId) end

-- [+] 0x1E45B34ADEBEE48E
function RemoveAllAirDefenseZones() end

-- [+] 0xDB6708C0B46F56D8
function RemoveAllCoverBlockingAreas() end

-- [+] 0xF25DF915FA38C5F3
function RemoveAllPedWeapons(ped, p1) end

-- [+] 0xFC52E0F37E446528
function RemoveAllProjectilesOfType(weaponHash, explode) end

-- [+] 0xAE287C923D891715
function RemoveCoverPoint(coverpoint) end

-- [+] 0x61B6775E83C0DB6F
function RemoveForcedObject(p0, p1, p2, p3, p4) end

-- [+] 0xD9E3006FB3CBD765
function RemoveModelHide(Any) end

-- [+] 0x033C0F9A64E229AE
function RemoveModelSwap(x, y, z, radius, oldModelHash, newModelHash, bLazy) end

-- [+] 0x46399A7895957C0E
function RemoveNavmeshBlockingObject(p0) end

-- [+] 0x916F0A3CDEC3445E
function RemoveNavmeshRequiredRegions() end

-- [+] 0x7FF548385680673F
function RemoveScriptFire(fireHandle) end

-- [+] 0xFF1B8B4AA1C25DC8
function RemoveWaypointRecording(name) end

-- [+] 0xAA08EF13F341C8FC
function RemoveWeaponAsset(weaponHash) end

-- [+] 0x1E8BE90C74FB4C09
function RemoveWeaponComponentFromPed(ped, weaponHash, componentHash) end

-- [+] 0xF7D82B0D66777611
function RemoveWeaponComponentFromWeaponObject(weaponObject, Any) end

-- [+] 0x4899CB088EDF59B8
function RemoveWeaponFromPed(ped, weaponHash) end

-- [+] 0x07FB139B592FA687
function RequestPathsPreferAccurateBoundingstruct(x1, y1, x2, y2) end

-- [+] 0x6EB5F71AA68F2E8E
function RequestScript(scriptName) end

-- [+] 0xD62A67D26D9653E6
function RequestScriptWithNameHash(scriptHash) end

-- [+] 0xD01015C7316AE176
function RequestTaskMoveNetworkStateTransition(ped, name) end

-- [+] 0x9EEFB62EB27B5792
function RequestWaypointRecording(name) end

-- [+] 0x9B1E824FFBB7027A
function ResetEntityAlpha(Any) end

-- [+] 0x4202BBCB8684563D
function ResetExclusiveScenarioGroup() end

-- [~] 0x9FA4664CF62E47E8
function ResetPedRagdollTimer(ped) end

-- [+] 0xDD902D0349AFAD3A
function ResetScenarioGroupsEnabled() end

-- [+] 0x0D40EE2A7F2B2D6D
function ResetScenarioTypesEnabled() end

-- [+] 0x30B4FA1C82DD4B9F
function ScriptThreadIteratorGetNextThreadId() end

-- [+] 0xDADFADA5A20143A8
function ScriptThreadIteratorReset() end

-- [+] 0xF74B1FFA4A15FBEA
function SetAiGlobalPathNodesType(type) end

-- [+] 0x228E5C6AD4D74BFD
function SetAllPathsCacheBoundingstruct(toggle) end

-- [+] 0x0B919E1FB47CC4E0
function SetAmbientPedRangeMultiplierThisFrame(multiplier) end

-- [+] 0x70033C3CC29A1FF4
function SetAnimLooped(p0, p1, p2, p3) end

-- [+] 0xDDF3CB5A0A4C0B49
function SetAnimPhase(entity, p1, p2, p3) end

-- [+] 0x032D49C5E359C847
function SetAnimRate(p0, p1, p2, p3) end

-- [+] 0x207F1A47C0342F48
function SetAnimWeight(p0, p1, p2, p3, p4) end

-- [+] 0xE12ABE5E3A389A6C
function SetCanAutoVaultOnEntity(entity, toggle) end

-- [+] 0xA80AE305E0A3044F
function SetCanClimbOnEntity(entity, toggle) end

-- [+] 0x571FEB383F629926
function SetCargobobForceDontDetachVehicle(cargobob, toggle) end

-- [+] 0x5C9B84BD7D31D908
function SetDriveTaskCruiseSpeed(driver, cruiseSpeed) end

-- [+] 0xDACE1BE37D88AF67
function SetDriveTaskDrivingStyle(ped, drivingStyle) end

-- [+] 0x404A5AA9B9F0B746
function SetDriveTaskMaxCruiseSpeed(p0, p1) end

-- [+] 0xE5B302114D8162EE
function SetDrivebyTaskTarget(shootingPed, targetPed, targetVehicle, x, y, z) end

-- [+] 0x44A0870B7E92D7C0
function SetEntityAlpha(entity, alphaLevel) end

-- [+] 0xACAD101E1FB66689
function SetEntityAlwaysPrerender(entity, toggle) end

-- [+] 0x8339643499D1222E
function SetEntityAngularVelocity(entity, x, y, z) end

-- [+] 0x4487C259F0F70977
function SetEntityAnimCurrentTime(entity, animDictionary, animName, time) end

-- [+] 0x28D1A16553C51776
function SetEntityAnimSpeed(entity, animDictionary, animName, speedMultiplier) end

-- [+] 0xAD738C3085FE7E11
function SetEntityAsMissionEntity(entity, scriptHostObject, bGrabFromOtherScript) end

-- [+] 0xB736A491E64A32CF
function SetEntityAsNoLongerNeeded(entity) end

-- [+] 0x1760FFA8AB074D66
function SetEntityCanBeDamaged(entity, toggle) end

-- [+] 0xE22D8FDE858B8119
function SetEntityCanBeDamagedByRelationshipGroup(entity, bCanBeDamaged, relGroup) end

-- [+] 0xD3997889736FD899
function SetEntityCanBeTargetedWithoutLos(entity, toggle) end

-- [+] 0x3910051CCECDB00C
function SetEntityCleanupByEngine(entity, toggle) end

-- [+] 0x1A9205C1B9EE827F
function SetEntityCollision(entity, toggle, keepPhysics) end

-- [+] 0x9EBC85ED0FFFE51C
function SetEntityCompletelyDisableCollision(entity, toggle, keepPhysics) end

-- [+] 0x06843DA7060A026B
function SetEntityCoords(entity, xPos, yPos, zPos, alive, deadFlag, ragdollFlag, clearArea) end

-- [+] 0x239A3351AC1DA385
function SetEntityCoordsNoOffset(entity, x, y, z, keepTasks, keepIK, doWarp) end

-- [+] 0x621873ECE1178967
function SetEntityCoordsWithoutPlantsReset(entity, xPos, yPos, zPos, alive, deadFlag, ragdollFlag, clearArea) end

-- [+] 0x2C2E3DC128F44309
function SetEntityDecalsDisabled(entity, p1) end

-- [+] 0x1718DE8E3F2823CA
function SetEntityDynamic(entity, toggle) end

-- [+] 0x4A4722448F18EEF5
function SetEntityHasGravity(entity, toggle) end

-- [+] 0x8E2530AA8ADA980E
function SetEntityHeading(entity, heading) end

-- [+] 0x6B76DC1F3AE6E6A3
function SetEntityHealth(entity, health) end

-- [+] 0x3882114BDE571AD4
function SetEntityInvincible(entity, toggle) end

-- [+] 0xEA02E132F5C68722
function SetEntityIsTargetPriority(entity, p1, p2) end

-- [+] 0x7CFBA6A80BDF3874
function SetEntityLights(entity, toggle) end

-- [+] 0x0DC7CABAB1E9B67E
function SetEntityLoadCollisionFlag(entity, toggle) end

-- [+] 0x5927F96A78577363
function SetEntityLodDist(entity, value) end

-- [+] 0x166E7CF68597D8B5
function SetEntityMaxHealth(entity, value) end

-- [+] 0x0E46A3FCBDE2A1B1
function SetEntityMaxSpeed(entity, speed) end

-- [+] 0x295D82A8559F9150
function SetEntityMotionBlur(entity, toggle) end

-- [+] 0xA53ED5520C07654A
function SetEntityNoCollisionEntity(entity1, entity2, thisFrameOnly) end

-- [+] 0x0A27A7827347B3B1
function SetEntityNoCollisionWithNetworkedEntity(entity1, entity2) end

-- [+] 0x79F020FF9EDC0748
function SetEntityOnlyDamagedByPlayer(entity, toggle) end

-- [+] 0x7022BD828FA0B082
function SetEntityOnlyDamagedByRelationshipGroup(entity, p1, relationshipHash) end

-- [+] 0xFAEE099C6F890BB8
function SetEntityProofs(entity, bulletProof, fireProof, explosionProof, collisionProof, meleeProof, steamProof, p7, drownProof) end

-- [+] 0x77B21BE7AC540F07
function SetEntityQuaternion(entity, x, y, z, w) end

-- [+] 0x0A50A1EEDAD01E65
function SetEntityRecordsCollisions(entity, toggle) end

-- [+] 0x730F5F8D3F0F2050
function SetEntityRenderScorched(entity, toggle) end

-- [+] 0x694E00132F2823ED
function SetEntityRequiresMoreExpensiveRiverCheck(entity, toggle) end

-- [+] 0x8524A8B0171D5E07
function SetEntityRotation(entity, pitch, roll, yaw, rotationOrder, bDeadCheck) end

-- [+] 0x57C5DB656185EAC4
function SetEntityTrafficlightOverride(entity, state) end

-- [+] 0x1C99BB7B6E96D16F
function SetEntityVelocity(entity, x, y, z) end

-- [+] 0xEA1C610A04DB6BBB
function SetEntityVisible(entity, toggle, unk) end

-- [+] 0x535E97E1F7FC0C6A
function SetExclusiveScenarioGroup(scenarioGroup) end

-- [+] 0x8F390AC4155099BA
function SetFireSpreadRate(p0) end

-- [+] 0x6C6B148586F934F7
function SetGlobalMinBirdFlightHeight(height) end

-- [+] 0xDC20483CD3DD5201
function SetGpsDisabledZone(Any) end

-- [+] 0xD0BC1C6FB18EE154
function SetGpsDisabledZoneAtIndex(x1, y1, z1, x2, y2, z2, index) end

-- [+] 0x8C825BDC7741D37C
function SetHighFallTask(ped, duration, p2, p3) end

-- [+] 0x72751156E7678833
function SetIgnoreNoGpsFlag(toggle) end

-- [+] 0x1FC289A0C3FF470F
function SetIgnoreSecondaryRouteNodes(toggle) end

-- [+] 0xC1F1920BAF281317
function SetInteriorEntitySetColor(interior, entitySetName, color) end

-- [+] 0xCCD892192C6D2BB9
function SetMountedWeaponTarget(shootingPed, targetPed, targetVehicle, x, y, z) end

-- [+] 0xF1B9F16E89E2C93A
function SetNextDesiredMoveState(p0) end

-- [+] 0x5262CC1995D07E09
function SetNoLoadingScreen(toggle) end

-- [+] 0x3AE22DEB5BA5A3E6
function SetObjectAsNoLongerNeeded(object) end

-- [+] 0xC313379AF0FCEDA7
function SetParachuteTaskTarget(ped, x, y, z) end

-- [+] 0x0729BAC1B8C64317
function SetParachuteTaskThrust(ped, thrust) end

-- [+] 0x2595DD4236549CE3
function SetPedAsNoLongerNeeded(ped) end

-- [+] 0x8FD89A6240813FD0
function SetPedCanPlayAmbientIdles(ped, bBlockIdleClips, bRemoveIdleClipIfPlaying) end

-- [~] 0xB128377056A54E2A
function SetPedCanRagdoll(ped, toggle) end

-- [~] 0xDF993EE5E90ABA25
function SetPedCanRagdollFromPlayerImpact(ped, toggle) end

-- [+] 0x1E982AC8716912C5
function SetPedDesiredMoveBlendRatio(ped, p1) end

-- [+] 0x4455517B28441E60
function SetPedPathAvoidFire(ped, avoidFire) end

-- [+] 0xE361C5C71C431A4F
function SetPedPathCanDropFromHeight(ped, Toggle) end

-- [+] 0x8E06A6FE76C9EFF4
function SetPedPathCanUseClimbovers(Any) end

-- [+] 0x77A5B103C87F476E
function SetPedPathCanUseLadders(Any) end

-- [+] 0x88E32DB8C1A4AA4B
function SetPedPathClimbCostModifier(ped, modifier) end

-- [+] 0xF35425A4204367EC
function SetPedPathMayEnterWater(ped, mayEnterWater) end

-- [+] 0x38FE1EC73743793C
function SetPedPathPreferToAvoidWater(ped, avoidWater) end

-- [+] 0xE04B48F2CC926253
function SetPedPathsBackToOriginal(p0, p1, p2, p3, p4, p5) end

-- [+] 0x34F060F4BF92E018
function SetPedPathsInArea(x1, y1, z1, x2, y2, z2, unknown) end

-- [~] 0x01F6594B923B9251
function SetPedRagdollForceFall(Any) end

-- [~] 0xF0A4F1BBF4FA7497
function SetPedRagdollOnCollision(ped, toggle) end

-- [~] 0xAE99FB955581844A
function SetPedToRagdoll(ped, minTime, maxTime, ragdollType, bAbortIfInjured, bAbortIfDead, bForceScriptControl) end

-- [~] 0xD76632D99E4966C8
function SetPedToRagdollWithFall(ped, minTime, maxTime, nFallType, dirX, dirY, dirZ, fGroundHeight, grab1X, grab1Y, grab1Z, grab2X, grab2Y, grab2Z) end

-- [+] 0xED98E10B0AFCE4B4
function SetPedWaypointRouteOffset(p0, p1, p2, p3) end

-- [+] 0xD7B80E7C3BEFC396
function SetPickUpByCargobobDisabled(entity, Any) end

-- [~] 0x26695EC767728D84
function SetRagdollBlockingFlags(ped, flags) end

-- [+] 0x1EE7063B80FFC77C
function SetRoadsBackToOriginal(p0, p1, p2, p3, p4, p5) end

-- [+] 0x0027501B9F3B407E
function SetRoadsBackToOriginalInAngledArea(x1, y1, z1, x2, y2, z2, width) end

-- [+] 0x1A5AA1208AF5DB59
function SetRoadsInAngledArea(x1, y1, z1, x2, y2, z2, width, unknown1, unknown2, unknown3) end

-- [+] 0xBF1A602B5BA52FEE
function SetRoadsInArea(x1, y1, z1, x2, y2, z2, nodeEnabled, unknown2) end

-- [+] 0x02C8E5B49848664E
function SetScenarioGroupEnabled(scenarioGroup, p1) end

-- [+] 0xEB47EC4E34FB7EE1
function SetScenarioTypeEnabled(scenarioType, toggle) end

-- [+] 0xC90D2DCACD56184C
function SetScriptAsNoLongerNeeded(scriptName) end

-- [+] 0xC5BC038960E9DB27
function SetScriptWithNameHashAsNoLongerNeeded(scriptHash) end

-- [+] 0x58C70CF3A41E4AE7
function SetSequenceToRepeat(taskSequenceId, repeats) end

-- [+] 0xB0A6CFD2C69C1088
function SetTaskMoveNetworkSignalBool(ped, signalName, value) end

-- [+] 0xD5BB4025AE449A4E
function SetTaskMoveNetworkSignalFloat(ped, signalName, value) end

-- [+] 0xCC665AAC360D31E7
function SetTaskVehicleChaseBehaviorFlag(ped, flag, set) end

-- [+] 0x639B642FACBE4EDD
function SetTaskVehicleChaseIdealPursuitDistance(ped, distance) end

-- [+] 0x1F9FB66F3A3842D2
function SetVehicleActAsIfHighSpeedForFragSmashing(vehicle, actHighSpeed) end

-- [+] 0x629BFA74418D6239
function SetVehicleAsNoLongerNeeded(vehicle) end

-- [+] 0xDC6F8601FAF2E893
function SetWaitForCollisionsBeforeProbe(entity, toggle) end

-- [+] 0x078EBE9809CCD637
function ShutdownLoadingScreen() end

-- [+] 0x9E5B5E4D2CCD2259
function SmashVehicleWindow(Any) end

-- [+] 0xF6A9D9708F6F23DF
function StartEntityFire(entity) end

-- [+] 0x6B83617E04503888
function StartScriptFire(X, Y, Z, maxChildren, isGasFire) end

-- [+] 0xEE08C992D238C5D1
function StopAnimPlayback(ped, p1, p2) end

-- [+] 0x97FF36A1D40EA00A
function StopAnimTask(ped, animDictionary, animationName, animExitSpeed) end

-- [+] 0x28004F88151E03E0
function StopEntityAnim(entity, animation, animGroup, p3) end

-- [+] 0x7F0DD2EBBB651AFF
function StopEntityFire(entity) end

-- [+] 0x056A8A219B8E829F
function StopFireInRange(x, y, z, radius) end

-- [+] 0x43D3807C077261E3
function StopSynchronizedEntityAnim(entity, p1, p2) end

-- [+] 0x11E79CAB7183B6F5
function StopSynchronizedMapEntityAnim(p0, p1, p2, p3, p4, p5) end

-- [+] 0x93B93A37987F1F3D
function TaskAchieveHeading(ped, heading, timeout) end

-- [+] 0x19D1B791CB3670FE
function TaskAgitatedAction(ped, ped2) end

-- [+] 0x6671F3EEC681BDA1
function TaskAimGunAtCoord(ped, x, y, z, time, bInstantBlendToAim, bPlayAimIntro) end

-- [+] 0x9B53BB6E8943AF53
function TaskAimGunAtEntity(ped, entity, duration, bInstantBlendToAim) end

-- [+] 0x7A192BE16D373D00
function TaskAimGunScripted(ped, scriptTask, bDisableBlockingClip, bInstantBlendToAim) end

-- [+] 0x8605AF0DE8B3A5AC
function TaskAimGunScriptedWithTarget(ped, targetPed, x, y, z, Any) end

-- [+] 0xF3B9A78A178572B1
function TaskArrestPed(ped, target) end

-- [+] 0x15C86013127CE63F
function TaskBoatMission(ped, boat, vehicleTarget, pedTarget, x, y, z, missionType, speed, drivingStyle, radius, missionFlags) end

-- [+] 0x8C338E0263E4FD19
function TaskChatToPed(ped, target, p2, p3, p4, p5, p6, p7) end

-- [+] 0x95A6C46A31D1917D
function TaskClearDefensiveArea(p0) end

-- [+] 0x0F804F1DB19B9689
function TaskClearLookAt(ped) end

-- [+] 0x89D9FCC2435112F1
function TaskClimb(ped, unused) end

-- [+] 0xB6C987F9285A3814
function TaskClimbLadder(ped, p1) end

-- [+] 0x7BF835BB9E2698C8
function TaskCombatHatedTargetsAroundPed(ped, radius, p2) end

-- [+] 0x2BBA30B854534A0C
function TaskCombatHatedTargetsAroundPedTimed(p0, p1, p2, p3) end

-- [+] 0x4CF5F55DAC3280A0
function TaskCombatHatedTargetsInArea(ped, x, y, z, radius, p5) end

-- [+] 0xF166E48407BAC484
function TaskCombatPed(ped, targetPed, p2, p3) end

-- [+] 0x944F30DCB7096BDE
function TaskCombatPedTimed(p0, ped, p2, p3) end

-- [+] 0x3EB1FE9E8E908E15
function TaskCower(ped, duration) end

-- [+] 0x2F8AF0E82773A171
function TaskDriveBy(driverPed, targetPed, targetVehicle, targetX, targetY, targetZ, distanceToShoot, pedAccuracy, p8, firingPattern) end

-- [+] 0xC20E50AA46D09CA8
function TaskEnterVehicle(ped, vehicle, timeout, seatIndex, speed, flag, p6) end

-- [+] 0x7F93691AB4B92272
function TaskEveryoneLeaveVehicle(vehicle) end

-- [+] 0x79B258E397854D29
function TaskExitCover(p0, p1, p2, p3, p4) end

-- [+] 0x1E7889778264843A
function TaskExtendRoute(x, y, z) end

-- [+] 0x841142A1376E9006
function TaskFlushRoute() end

-- [+] 0x15D3A79D4E44B913
function TaskFollowNavMeshToCoord(ped, x, y, z, moveBlendRatio, time, radius) end

-- [+] 0x17F58B88D085DBAC
function TaskFollowNavMeshToCoordAdvanced(ped, x, y, z, speed, timeout, unkFloat, unkInt, unkX, unkY, unkZ, unk_40000f) end

-- [+] 0x595583281858626E
function TaskFollowPointRoute(ped, speed, routeMode) end

-- [+] 0x304AE42E357B8C7E
function TaskFollowToOffsetOfEntity(ped, entity, offsetX, offsetY, offsetZ, movementSpeed, timeout, stoppingRange, persistFollowing) end

-- [+] 0x0759591819534F7B
function TaskFollowWaypointRecording(p0, p1, p2, p3, p4) end

-- [+] 0x4F056E1AFFEF17AB
function TaskForceMotionState(ped, state, p2) end

-- [+] 0x9C00E77AF14B2DFF
function TaskGetOffBoat(ped, boat) end

-- [+] 0xD76B57B44F1E6F8B
function TaskGoStraightToCoord(ped, x, y, z, speed, timeout, targetHeading, distanceToSlide) end

-- [+] 0x61E360B7E040D12E
function TaskGoStraightToCoordRelativeToEntity(entity1, entity2, p2, p3, p4, p5, p6) end

-- [+] 0xA55547801EB331FC
function TaskGoToCoordAndAimAtHatedEntitiesNearCoord(pedHandle, goToLocationX, goToLocationY, goToLocationZ, focusLocationX, focusLocationY, focusLocationZ, speed, shootAtEnemies, distanceToStopAt, noRoadsDistance, unkTrue, unkFlag, aimingFlag, firingPattern) end

-- [+] 0x5BC448CB78FA3E88
function TaskGoToCoordAnyMeans(ped, x, y, z, fMoveBlendRatio, Any) end

-- [+] 0x1DD45F9ECFDB1BC9
function TaskGoToCoordAnyMeansExtraParams(ped, x, y, z, speed, p5, p6, walkingStyle, p8, p9, p10, p11) end

-- [+] 0xB8ECD61F531A7B02
function TaskGoToCoordAnyMeansExtraParamsWithCruiseSpeed(ped, x, y, z, speed, p5, p6, walkingStyle, p8, p9, p10, p11, p12) end

-- [+] 0x11315AB3385B8AC0
function TaskGoToCoordWhileAimingAtCoord(ped, x, y, z, aimAtX, aimAtY, aimAtZ, moveSpeed, shoot, p9, p10, p11, flags, p13, firingPattern) end

-- [+] 0xB2A16444EAD9AE47
function TaskGoToCoordWhileAimingAtEntity(ped, x, y, z, entityToAimAt, moveSpeed, shoot, targetRadius, slowDistance, useNavMesh, navFlags, instantBlendAtAim, Any) end

-- [+] 0x6A071245EB0D1882
function TaskGoToEntity(entity, target, duration, distance, speed, p5, p6) end

-- [+] 0x04701832B739DCE5
function TaskGoToEntityWhileAimingAtCoord(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11) end

-- [+] 0x97465886D35210E9
function TaskGoToEntityWhileAimingAtEntity(ped, entityToWalkTo, entityToAimAt, speed, shootatEntity, p5, p6, p7, p8, firingPattern) end

-- [+] 0xA9DA48FAB8A76C12
function TaskGotoEntityAiming(ped, target, distanceToStopAt, StartAimingDist) end

-- [+] 0xE39B4FF4FDEBDE27
function TaskGotoEntityOffset(ped, entity, duration, seekRadius, seekAngleDeg, moveBlendRatio, gotoEntityOffsetFlags) end

-- [+] 0x338E7EF52B6095A9
function TaskGotoEntityOffsetXy(ped, entity, duration, targetRadius, offsetX, offsetY, moveBlendRatio) end

-- [+] 0xD2A207EEBDF9889B
function TaskGuardAssignedDefensiveArea(p0, p1, p2, p3, p4, p5, p6) end

-- [+] 0x4A58A47A72E3FCB4
function TaskGuardCurrentPosition(p0, p1, p2, p3) end

-- [+] 0xC946FE14BE0EB5E2
function TaskGuardSphereDefensiveArea(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) end

-- [+] 0xF2EAB31979A7F910
function TaskHandsUp(ped, duration, facingPed, p3, p4) end

-- [+] 0xAC83B1DB38D0ADA0
function TaskHeliChase(pilot, entityToFollow, x, y, z) end

-- [+] 0xB385523325077210
function TaskHeliEscortHeli(pilot, heli1, heli2, p3, p4, p5) end

-- [+] 0xDAD029E187A2BEB4
function TaskHeliMission(ped, heli, vehicleTarget, pedTarget, x, y, z, missionType, speed, radius, heading) end

-- [+] 0x0AE4086104E067B1
function TaskJump(ped, unused) end

-- [+] 0x504D54DF3F6F2247
function TaskLeaveAnyVehicle(ped, p1, flags) end

-- [+] 0xD3DBCE61A490BE02
function TaskLeaveVehicle(ped, vehicle, flags) end

-- [+] 0x6FA46612594F7973
function TaskLookAtCoord(entity, x, y, z) end

-- [+] 0x69F4BE8C8CC4796C
function TaskLookAtEntity(ped, lookAt, duration, unknown1, unknown2) end

-- [+] 0xD5B35BEA41919ACB
function TaskMoveNetworkAdvancedByName(ped, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, animDict, flags) end

-- [+] 0x2D537BA194896636
function TaskMoveNetworkByName(ped, task, multiplier, p3, animDict, flags) end

-- [+] 0x3D45B0B355C5E0C9
function TaskMoveNetworkByNameWithInitParams(ped, p1, data, p3, p4, animDict, flags) end

-- [+] 0x965791A9A488A062
function TaskOpenVehicleDoor(ped, vehicle, timeOut, seat, speed) end

-- [+] 0xD2F1C53C97EE81AB
function TaskParachute(ped, p1) end

-- [+] 0xB33E291AFA6BD03A
function TaskParachuteToTarget(ped, x, y, z) end

-- [+] 0xBDA5DF49D080FE4E
function TaskPatrol(ped, p1, p2, p3, p4) end

-- [+] 0xE73A266DB0CA9042
function TaskPause(ped, ms) end

-- [+] 0xD04FE6765D990A06
function TaskPedSlideToCoord(ped, x, y, z, heading, duration) end

-- [+] 0x5A4A6A6D3DC64F52
function TaskPedSlideToCoordHdgRate(ped, x, y, z, heading, p5, p6) end

-- [+] 0x5ABA3986D90D8A3B
function TaskPerformSequence(Any) end

-- [+] 0x89221B16730234F0
function TaskPerformSequenceFromProgress(ped, taskIndex, progress1, progress2) end

-- [+] 0x8C33220C8D78CA0D
function TaskPerformSequenceLocally(ped, taskSequenceId) end

-- [+] 0x2D2386F273FF7A25
function TaskPlaneChase(pilot, entityToFollow, x, y, z) end

-- [+] 0xF7F9DCCA89E7505B
function TaskPlaneGotoPreciseVtol(ped, vehicle, p2, p3, p4, p5, p6, p7, p8, p9) end

-- [+] 0xBF19721FA34D32C0
function TaskPlaneLand(pilot, plane, runwayStartX, runwayStartY, runwayStartZ, runwayEndX, runwayEndY, runwayEndZ) end

-- [+] 0x23703CD154E83B88
function TaskPlaneMission(ped, vehicle, targetVehicle, targetPed, fTargetCoordX, fTargetCoordY, fTargetCoordZ, iMissionIndex, fCruiseSpeed, fTargetReachedDist, fOrientation) end

-- [+] 0x92C360B5F15D2302
function TaskPlaneTaxi(pilot, aircraft, Any) end

-- [+] 0x965FEC691D55E9BF
function TaskPlantBomb(ped, x, y, z, heading) end

-- [+] 0xEA47FE3719165B94
function TaskPlayAnim(ped, animDictionary, animationName, blendInSpeed, blendOutSpeed, duration, flag, playbackRate, lockX, lockY, lockZ) end

-- [+] 0x83CDB10EA29B370B
function TaskPlayAnimAdvanced(ped, animDictionary, animationName, posX, posY, posZ, rotX, rotY, rotZ, blendInSpeed, blendOutSpeed, duration, flag, animTime, p14, p15) end

-- [+] 0x8FBB6758B3B3E9EC
function TaskPlayPhoneGestureAnimation(ped, animDict, animation, boneMaskType, p4, p5, p6, p7) end

-- [+] 0x4172393E6BE1FECE
function TaskPutPedDirectlyIntoCover(ped, x, y, z, timeout, p5, p6, p7, p8, p9, p10) end

-- [+] 0x1C6CD14A876FFE39
function TaskPutPedDirectlyIntoMelee(ped, meleeTarget, p2, p3, p4, p5) end

-- [+] 0xEAF66ACDDC794793
function TaskRappelDownWall(ped, x1, y1, z1, x2, y2, z2, minZ, ropeId, clipset, p10) end

-- [+] 0x09693B0312F91649
function TaskRappelFromHeli(ped) end

-- [+] 0x72C896464915D1B1
function TaskReactAndFleePed(ped, fleeTarget) end

-- [+] 0x62D2916F56B9CD2D
function TaskReloadWeapon(ped, unused) end

-- [+] 0x126EF75F1E17ABE5
function TaskScriptedAnimation(ped, p1, p2, p3, p4, p5) end

-- [+] 0x84D32B3BEC531324
function TaskSeekCoverFromPed(ped, target, duration, p3) end

-- [+] 0x75AC2B60386D89F2
function TaskSeekCoverFromPos(ped, x, y, z, duration, p5) end

-- [+] 0x39246A6958EF072C
function TaskSeekCoverToCoords(ped, x1, y1, z1, x2, y2, z2, p7, p8) end

-- [+] 0xD43D95C7A869447F
function TaskSeekCoverToCoverPoint(p0, p1, p2, p3, p4, p5, p6) end

-- [+] 0x90D2156198831D69
function TaskSetBlockingOfNonTemporaryEvents(ped, toggle) end

-- [+] 0xEB8517DDA73720DA
function TaskSetDecisionMaker(ped, p1) end

-- [+] 0x933C06518B52A9A4
function TaskSetSphereDefensiveArea(p0, p1, p2, p3, p4) end

-- [+] 0x60A19CF85FF4CEFA
function TaskSharkCircleCoord(ped, x, y, z, moveBlendRatio, radius) end

-- [+] 0x452419CBD838065B
function TaskShockingEventReact(ped, eventHandle) end

-- [+] 0x46A6CC01E0826106
function TaskShootAtCoord(ped, x, y, z, duration, firingPattern) end

-- [+] 0x08DA95E8298AE772
function TaskShootAtEntity(entity, target, duration, firingPattern) end

-- [+] 0x7AA80209BDA643EB
function TaskShuffleToNextVehicleSeat(ped, vehicle) end

-- [+] 0x601736CFE536B0A0
function TaskSkyDive(ped) end

-- [+] 0x94587F17E9C365D5
function TaskSmartFleeCoord(ped, x, y, z, distance, time, p6, p7) end

-- [+] 0x22B0D0E37CCB840D
function TaskSmartFleePed(ped, fleeTarget, distance, fleeTime, p4, p5) end

-- [+] 0xAE032F8BBA959E90
function TaskStandGuard(ped, x, y, z, heading, scenarioName) end

-- [+] 0x919BE13EED931959
function TaskStandStill(ped, time) end

-- [+] 0xFA4EFC79F69D4F07
function TaskStartScenarioAtPosition(ped, scenarioName, x, y, z, heading, timeToLeave, playIntro, warp) end

-- [+] 0x142A02425FF02BD9
function TaskStartScenarioInPlace(ped, scenarioName, timeToLeave, playIntroClip) end

-- [+] 0xE5DA8615A6180789
function TaskStayInCover(ped) end

-- [+] 0xAA5DC05579D60BD9
function TaskStealthKill(killer, target, actionType, p3, p4) end

-- [+] 0x3FA00D4F4641BFAE
function TaskStopPhoneGestureAnimation(ped) end

-- [+] 0xC22B40579A498CA4
function TaskSubmarineGotoAndStop(p0, submarine, x, y, z, p5) end

-- [+] 0xA21C51255B205245
function TaskSwapWeapon(ped, p1) end

-- [+] 0x2047C02158D6405A
function TaskSweepAimEntity(ped, anim, p2, p3, p4, p5, vehicle, p7, p8) end

-- [+] 0x7AFE8FDC10BC07D2
function TaskSweepAimPosition(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) end

-- [+] 0xEEA929141F699854
function TaskSynchronizedScene(ped, scene, animDictionary, animationName, speed, speedMultiplier, duration, flag, playbackRate, p9) end

-- [+] 0x7285951DBF6B5A51
function TaskThrowProjectile(ped, x, y, z) end

-- [+] 0xAC96609B9995EDF8
function TaskToggleDuck(p0, p1) end

-- [+] 0x1DDA930A0AC38571
function TaskTurnPedToFaceCoord(ped, x, y, z, duration) end

-- [+] 0x5AD23D40115353AC
function TaskTurnPedToFaceEntity(ped, entity, duration) end

-- [+] 0xBD2A8EC3AF4DE7DB
function TaskUseMobilePhone(ped, p1) end

-- [+] 0x5EE02954A14C69DB
function TaskUseMobilePhoneTimed(ped, duration) end

-- [+] 0x9FDA1B3D7E7028B3
function TaskUseNearestScenarioChainToCoord(p0, p1, p2, p3, p4, p5) end

-- [+] 0x97A28E63F0BA5631
function TaskUseNearestScenarioChainToCoordWarp(p0, p1, p2, p3, p4, p5) end

-- [+] 0x277F471BA9DB000B
function TaskUseNearestScenarioToCoord(ped, x, y, z, distance, duration) end

-- [+] 0x58E2E0F23F6B76C3
function TaskUseNearestScenarioToCoordWarp(ped, x, y, z, radius, p5) end

-- [+] 0x447C1E9EF844BC0F
function TaskVehicleAimAtCoord(ped, x, y, z) end

-- [+] 0xE41885592B08B097
function TaskVehicleAimAtPed(ped, target) end

-- [+] 0x3C08A8E30363B353
function TaskVehicleChase(driver, targetEnt) end

-- [+] 0xE2A2AA2F659D77A7
function TaskVehicleDriveToCoord(ped, vehicle, x, y, z, speed, p6, vehicleModel, drivingMode, stopRange, p10) end

-- [+] 0x158BB33F920D360C
function TaskVehicleDriveToCoordLongrange(ped, vehicle, x, y, z, speed, drivingStyle, stopRange) end

-- [+] 0x480142959D337D00
function TaskVehicleDriveWander(ped, vehicle, speed, drivingStyle) end

-- [+] 0x0FA6E4B75F302400
function TaskVehicleEscort(ped, vehicle, targetVehicle, mode, speed, drivingStyle, minDistance, p7, noRoadsDistance) end

-- [+] 0xFC545A9F0626E3B6
function TaskVehicleFollow(driver, vehicle, targetEntity, speed, drivingStyle, minDistance) end

-- [+] 0x3123FAA6DB1CF7ED
function TaskVehicleFollowWaypointRecording(ped, vehicle, WPRecording, p3, p4, p5, p6, p7, p8, p9) end

-- [+] 0x195AEEB13CEFE2EE
function TaskVehicleGotoNavmesh(ped, vehicle, x, y, z, speed, behaviorFlag, stoppingRange) end

-- [+] 0x1E09C32048FEFD1C
function TaskVehicleHeliProtect(pilot, vehicle, entityToFollow, targetSpeed, p4, radius, altitude, p7) end

-- [+] 0x659427E0EF36BCDE
function TaskVehicleMission(ped, vehicle, vehicleTarget, missionType, speed, drivingStyle, radius, straightLineDist, DriveAgainstTraffic) end

-- [+] 0xF0AF20AA7731F8C3
function TaskVehicleMissionCoorsTarget(ped, vehicle, x, y, z, missionType, speed, drivingStyle, radius, straightLineDist, DriveAgainstTraffic) end

-- [+] 0x9454528DF15D657A
function TaskVehicleMissionPedTarget(ped, vehicle, pedTarget, missionType, speed, drivingStyle, radius, straightLineDist, DriveAgainstTraffic) end

-- [+] 0x0F3E34E968EA374E
function TaskVehiclePark(ped, vehicle, x, y, z, heading, mode, radius, keepEngineOn) end

-- [+] 0x69F5C3BD0F3EBD89
function TaskVehiclePlayAnim(vehicle, animationSet, animationName) end

-- [+] 0x5190796ED39C9B6D
function TaskVehicleShootAtCoord(ped, x, y, z, p4) end

-- [+] 0x10AB107B887214D8
function TaskVehicleShootAtPed(ped, target, p2) end

-- [+] 0xC429DCEEB339E129
function TaskVehicleTempAction(driver, vehicle, action, time) end

-- [+] 0xE054346CA3A0F315
function TaskWanderInArea(ped, x, y, z, radius) end

-- [+] 0x6919A2F136426098
function TaskWanderSpecific(p0, p1, p2, p3) end

-- [+] 0xBB9CE077274F6A1B
function TaskWanderStandard(ped, p1, p2) end

-- [+] 0x6E01E9E8D89F8276
function TaskWarpPedDirectlyIntoCover(ped, time, canPeekAndAim, forceInitialFacingDirection, forceFaceLeft, coverIndex) end

-- [+] 0x9A7D091411C5F684
function TaskWarpPedIntoVehicle(ped, vehicle, seatIndex) end

-- [+] 0xCDDC2B77CE54AC6E
function TaskWrithe(ped, target, time, p3) end

-- [+] 0x1090044AD1DA76FA
function TerminateThisThread() end

-- [+] 0xC8B189ED9138BCD4
function TerminateThread(threadId) end

-- [+] 0x5AE99C571D5BBE5D
function TriggerScriptEvent(eventGroup, eventData, eventDataSize, playerBits) end

-- [+] 0x67406F2C8F87FC4F
function UncuffPed(ped) end

-- [+] 0x261CCE7EED010641
function UnpinInterior(interior) end

-- [+] 0x109E99373F290687
function UpdateNavmeshBlockingObject(object, posX, posY, posZ, scaleX, scaleY, scaleZ, heading, flags) end

-- [+] 0x9724FB59A3E72AD0
function UpdateTaskAimGunScriptedTarget(p0, p1, p2, p3, p4, p5) end

-- [+] 0xA98FCAFD7893C834
function UpdateTaskHandsUpDuration(ped, duration) end

-- [+] 0xE4973DBDBE6E44B3
function UpdateTaskSweepAimEntity(ped, entity) end

-- [+] 0xBB106883F5201FC4
function UpdateTaskSweepAimPosition(p0, p1, p2, p3) end

-- [+] 0x5A353B8E6B1095B5
function UseWaypointRecordingAsAssistedMovementRoute(name, p1, p2, p3) end

-- [+] 0x121F0593E0A431D7
function VehicleWaypointPlaybackOverrideSpeed(vehicle, speed) end

-- [+] 0x8A4E6AC373666BC5
function VehicleWaypointPlaybackPause(vehicle) end

-- [+] 0xDC04FCAA7839D492
function VehicleWaypointPlaybackResume(vehicle) end

-- [+] 0x5CEB25A7D2848963
function VehicleWaypointPlaybackUseDefaultSpeed(vehicle) end

-- [~] 0xF9800AA1A771B000
function WasPedKilledByStealth(ped) end

-- [~] 0x7F08E26039C7347C
function WasPedKilledByTakedown(ped) end

-- [+] 0x701375A7D43F01CB
function WaypointPlaybackGetIsPaused(p0) end

-- [+] 0x7D7D2B47FA788E85
function WaypointPlaybackOverrideSpeed(p0, p1, p2) end

-- [+] 0x0F342546AA06FED5
function WaypointPlaybackPause(p0, p1, p2) end

-- [+] 0x244F70C84C547D2D
function WaypointPlaybackResume(p0, p1, p2, p3) end

-- [+] 0x8968400D900ED8B3
function WaypointPlaybackStartAimingAtCoord(p0, p1, p2, p3, p4) end

-- [+] 0x20E330937C399D29
function WaypointPlaybackStartAimingAtPed(p0, p1, p2) end

-- [+] 0x057A25CFCC9DB671
function WaypointPlaybackStartShootingAtCoord(p0, p1, p2, p3, p4, p5) end

-- [+] 0xE70BA7B90F8390DC
function WaypointPlaybackStartShootingAtPed(p0, p1, p2, p3) end

-- [+] 0x47EFA040EBB8E2EA
function WaypointPlaybackStopAimingOrShooting(p0) end

-- [+] 0x6599D834B12D0800
function WaypointPlaybackUseDefaultSpeed(p0) end

-- [+] 0xB629A298081F876F
function WaypointRecordingGetClosestWaypoint(name, x, y, z, point) end

-- [+] 0x2FB897405C90B361
function WaypointRecordingGetCoord(name, point, coord) end

-- [+] 0x5343532C01A07234
function WaypointRecordingGetNumPoints(name, points) end

-- [+] 0x005622AEBC33ACA9
function WaypointRecordingGetSpeedAtPoint(name, point) end

-- [+] 0xEE5D2A122E09EC42
function WouldEntityBeOccluded(entityModelHash, x, y, z, p4) end
