-- ====================================================================================--
-- CHARACTER LIFECYCLE MANAGEMENT - CONSOLIDATED
-- ====================================================================================--
--
-- ⚠️ THIS FILE HAS BEEN DEPRECATED AND CONSOLIDATED
--
-- All character event handlers have been moved to _character_lifecycle.lua to:
--  ✓ Eliminate duplicate handler registrations
--  ✓ Improve organization and maintainability
--  ✓ Add comprehensive documentation and flow diagrams
--
-- MIGRATION DETAILS:
--  - Duplicate events removed from this file
--  - Cleaner versions retained in _character_lifecycle.lua
--  - Better structured with clear stage separation
--
-- TODO: Remove this file and _character.lua from fxmanifest.lua
--
-- ====================================================================================--

-- This file should be removed from fxmanifest.lua
-- All handlers are now in: server/[Events]/_character_lifecycle.lua