-- ====================================================================================--
-- Character NUI Callbacks - CONSOLIDATED
-- ====================================================================================--
-- IMPORTANT: All character NUI callbacks have been consolidated in:
-- nui/lua/NUI-Client/character-select.lua
--
-- Moved callbacks:
--   - NUI:Client:CharacterCreate
--   - NUI:Client:CharacterPlay
--   - NUI:Client:CharacterDelete
--
-- DO NOT register callbacks here - they are centralized in nui/lua/NUI-Client/character-select.lua
-- See that file for the proper implementation
-- ====================================================================================--
