-- ====================================================================================--
-- NUI Close Event Handlers - CONSOLIDATED
-- ====================================================================================--
-- IMPORTANT: All NUI callbacks have been consolidated in nui/lua/NUI-Client/
-- 
-- Moved callbacks:
--   - chatSubmit → nui/lua/NUI-Client/_chat.lua (NUI:Client:ChatSubmit)
--   - chatClose → nui/lua/NUI-Client/_chat.lua (NUI:Client:ChatClose)
--   - NUI:Client:MenuClose → nui/lua/NUI-Client/_menu.lua
--   - NUI:Client:InputClose → nui/lua/NUI-Client/_input.lua
--   - NUI:Client:ContextClose → nui/lua/NUI-Client/_context.lua
--   - NUI:Client:BankingClose → nui/lua/NUI-Client/_banking.lua
--   - NUI:Client:AppearanceClose → nui/lua/NUI-Client/_appearance.lua
--   - NUI:Client:TargetClose → nui/lua/NUI-Client/_target.lua
--   - NUI:Client:GarageClose → nui/lua/NUI-Client/_garage.lua
--   - NUI:Client:CharacterSelectClose → nui/lua/NUI-Client/character-select.lua
--
-- DO NOT register callbacks here - they are centralized in nui/lua/NUI-Client/
-- See those files for the proper implementation
-- ====================================================================================--
